### ISSUE TITLE
Rebase spec against 2.10

### ISSUE THREAD

**Issue by shalako** [openservicebrokerapi/servicebroker#101]
The spec is out of date. Rebase against latest changes in https://github.com/cloudfoundry/docs-services, including changes for v2.10 of the spec.

**Comment by duglin** [comment]
is this related to https://github.com/openservicebrokerapi/servicebroker/pull/99 or does https://github.com/openservicebrokerapi/servicebroker/pull/99 just clean stuff up?

**Comment by duglin** [comment]
if #99 doesn't cover this issue, is there a diff some place between v2.9 and v2.10?

**Comment by shalako** [comment]
#99 does not cover this issue. The source of truth is  https://github.com/cloudfoundry/docs-services. In terms of a diff, your guess is as good as mine. Maybe find out when the content was forked and look at all the changes in the docs-services repo from then until present.

Thinking about this today, I am now quite skeptical that the approach being taken here (fork and munge) is viable. The source of truth for the spec continues to be docs-services and that repo is frequently updated. Because the structure of the spec in this repo has been significantly altered, continuously rebasing will be tedious.

I can see a path forward by editing docs-services in place:
- we abandon this repo temporarily
- modify docs-services in place into the new structure while keeping the CF references
- extract the CF content into separate doc files in docs-services
- at that point we could fork the common content and replace it in docs-services with a link

Alternatively, continue to rebase here until we're ready to submit a big PR to docs-services. That PR would include all the extracted CF content and a link to this repo for the common content. 

This will leave the CF docs with a pretty poor user experience. We'll have to explore how to minimize the disruption and maximize usability. I wonder if this is all premature, given no other platform supports the spec yet.

**Comment by shalako** [comment]
Closing this, as we're making the broker docs in CF generic, while preserving CF context. Then we'll move that generic doc here.
