### ISSUE TITLE
Remove K8 development from this repo

### ISSUE THREAD

**Issue by shalako** [openservicebrokerapi/servicebroker#102]
This github repo should be for development of the broker api specification. Example brokers could be in separate repos.  

I would suggest that the only things that should be in this repo now are a README, license file, and the spec (w/images)

**Comment by shalako** [comment]
@duglin What do you think?

**Comment by duglin** [comment]
If its a K8s-only impl then I agree. I was hoping that the code here would be more like a reference implementation that could support multiple-backends (CF, K8s, ....) via plug-ins.  But if the code isn't generic then I agree it should be removed.  If we could make it more like a reference impl would you be ok with that?

**Comment by avade** [comment]
Reference impl of a broker or of a service controller? I think both would be too opinionated, we should simply point to example service controllers (CF's / K8's as example implementations) and OSS brokers.

**Comment by avade** [comment]
Reference impl of a broker or of a service controller? I think both would be too opinionated, we should simply point to example service controllers (CF's / K8's as example implementations) and OSS brokers.

**Comment by avade** [comment]
Reference impl of a broker or of a service controller? I think both would be too opinionated, we should simply point to example service controllers (CF's / K8's as example implementations) and OSS brokers.

**Comment by avade** [comment]
Reference impl of a broker or of a service controller? I think both would be too opinionated, we should simply point to example service controllers (CF's / K8's as example implementations) and OSS brokers.

**Comment by shalako** [comment]
At the very least, I believe this repo should be for documentation of the spec only. Our most immediate milestone should be to replace https://github.com/cloudfoundry/docs-services as the source for the API docs. Until then we are chasing a moving target.

Reference implementations are good, and we could consider hosting samples in other repos of this github organization. However, as @avade mentioned, there are many reference implementations of brokers in OSS already, and we link to a few of them from the docs. 

If you're interested in reference implementations of a service controller, we should link to the CF cloud controller. When Kubernetes or another platform has a service controller, we can link to those. 

If you are interested in developing some generic service controller library, that enables development of additional service controllers, that should be an effort independent from the specification docs but could potentially be another repo hosted in the same org.

**Comment by angarg12** [comment]
I agree that this repo should contain exclusively the API spec. Sample implementations are valuable and can reside in other repo, either inside or outside this org. Then these reference implementations can be linked from the docs, just like Cloud Foundry does with their spec currently.

On a similar note, it could be useful to rename this repo servicebrokerapi or something similar, to stress that it contains the spec and no code.

**Comment by duglin** [comment]
Based on today's call, I'll remove all non-spec stuff from this repo.
