### ISSUE TITLE
Improved authentication for security and federated provisioning

### ISSUE THREAD

**Issue by ozevren** [openservicebrokerapi/servicebroker#103]
Given that a standardized API will be implemented and consumed by more parties, possibly accessed over the open Internet, does it make sense to allow and/or standardize on other auth mechanisms (i.e. such as OAuth?). The Spec currently specifies Basic Auth as the only mechanism for authentication.

**EDIT by @avade**

Working document: https://docs.google.com/document/d/1XLPMLJbf_lRXIdMg1XUyKNZUd2--fDROGvdEm25tMjc/edit

**Comment by avade** [comment]
This is something we at Pivotal are interested in but I have not had time to write up a proposal for the group yet. It would be good to spend 10 minutes discussing this on the WG call today @shalako.

**Comment by avade** [comment]
I believe the action from the call was for @ozevren to draft a proposal doc.

I have reached out to some of the CF community to see if anyone is already working on this.

**Comment by ozevren** [comment]
https://docs.google.com/document/d/196-LCfWwObkF1upI2byIXgvMs8FZgYn7iB06dXDhAXE

Here is some preliminary investigation on the topic. Feel free to comment on the document or here.

**Comment by duglin** [comment]
@fraenkel has also written down some of his thoughts and a proposal:
https://docs.google.com/document/d/1w4swx_5erf_NmPtfcCW2fn2jbEBfRHf2xLVhWpc1PLM/edit

**Comment by gberche-orange** [comment]
See also the related ["Service Broker User delegation during provisionning"](https://docs.google.com/document/d/1DoAbJa_YiGIJbOZ_zPzakh7sc4TB9Tmadq41cfSX0dw/edit?ts=56427027# ) proposal document which was [exchanged late 2015](http://cf-dev.70369.x6.nabble.com/cf-dev-service-broker-user-delegation-beyond-service-dashboard-tt2658.html). I'll comment the other specs as well.

**Comment by shalako** [comment]
On our call today we discussed that the use cases @ozevren's proposal addresses are independent from those addressed by proposals from @fraenkel and @gberche-orange. 

- I have updated the title of this issue to focus our discussion on use cases for federated authority that require token-based authentication.
- I created #110 to address the use cases raised in proposals by @fraenkel and @gberche-orange and provided links to those proposals there
- To avoid confusion, I've removed @duglin and @gberche-orange's comments in this issue referring to the proposals we believe address different use cases.

**Comment by avade** [comment]
https://docs.google.com/document/d/1XLPMLJbf_lRXIdMg1XUyKNZUd2--fDROGvdEm25tMjc/edit

New doc from Matt & Paul.

**Comment by mattmcneeney** [comment]
@petereberlein I have added a **[Use Cases](https://docs.google.com/document/d/1XLPMLJbf_lRXIdMg1XUyKNZUd2--fDROGvdEm25tMjc/edit#heading=h.797yte5nbf6l)** section to that doc. Would you be able to add your current use cases for this when you have a moment? Thanks!

**Comment by petereberlein** [comment]
@mattmcneeney Actually I don't really have own use cases or an urgent need to change anything about the existing basic authentication mechanism. But I can follow the requirement raised by others that customers don't like basic auth and would prefer some stronger form of authentication.
To that end I added to bullets to the new use cases section, although I believe that it should be actually just one for both approaches (OAuth and client cert), but we can still merge them later.

**Comment by mattmcneeney** [comment]
OK that's great, thanks @petereberlein. We'll try to pull out some more CF use cases to make sure we can make as informed a decision as we can about the implementation.

**Comment by duglin** [comment]
Thoughts?  https://github.com/openservicebrokerapi/servicebroker/compare/master...duglin:issue103

**Comment by mattmcneeney** [comment]
@duglin I think that branch looks good. It keeps the implementation out of this spec which is sensible as there are so many ways it could be done.

**Comment by mattmcneeney** [comment]
We'll probably want to put some "recommendations" together, but it's probably worth writing those up _after_ a platform has attempted to implement something other than Basic Auth.
