### ISSUE TITLE
basic notes from 2016-11-15 meeting

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#105]
courtesy of @duglin. not sure if these all require action, but I put them into a checklist

 - [x] action: @duglin to remove non-spec stuff from repo
 - [x] topic: spec in our repo vs cf repo
 - [ ] proposal: generate HTML docs from our repo’s src (md).  Platforms can then decide whether to point to our HTML or to pull it into their docs
 - [ ] proposal: convert existing CF docs into single page format ; move that single page to our repo ; CF then issues PRs against our repo instead of CF’s for v2.11 changes.
 - [x] action: shannon/CF-folks to see how to get the single page format in CF and remove CF-isms.

https://github.com/cloudfoundry/docs-services  this is the current source of truth

**Comment by angarg12** [comment]
@duglin you may as well close all the issues related to k8s in this repo. Thanks!

**Comment by duglin** [comment]
@angarg12 I think I got 'em - let me know if I missed any

**Comment by shalako** [comment]
@MHBauer @duglin I think this can be closed?

**Comment by duglin** [comment]
ye closing
