### ISSUE TITLE
How to handle metadata/community driven standards

### ISSUE THREAD

**Issue by angarg12** [openservicebrokerapi/servicebroker#113]
I'm not sure if this has been discussed yet but I tough it is interesting to define what to do with the current metadata and community driven standards in OpenSB.

Currently Cloud Foundry SB API has a metadata field. As part of the docs, some community driven standards are included.

http://docs.cloudfoundry.org/services/catalog-metadata.html

This is positive because:

- It defines data that is generally interesting for users.
- Since it is outside the spec, providers are not forced to support them.

Issue #94 raises the point that this data may need a pass of refinement at the moment. But then that raises the bigger question about what to do with this spec in the migration to OpenSB. 

Should it also be migrated and kept as an accessory document?

**Comment by duglin** [comment]
I think opening an issue on this, so we can at least not forget to discuss it, would be good.

To the specific point... it seems reasonable to me that we might include something like this as part of our spec work.  We already talked about possibly defining “profiles” for platform specific data that goes into the (yet to be agreed to) “context” property, so a doc attempting to get some kind of agreement on these other extensions makes a lot of sense to me.

-Doug

**Comment by mattmcneeney** [comment]
@angarg12 @duglin I think we've addressed this by including the `profiled.md` file. Can we close this issue?
