### ISSUE TITLE
instance_id should be precisely specified

### ISSUE THREAD

**Issue by mayrstefan** [openservicebrokerapi/servicebroker#118]
The spec leaves open what service broker authors have to accept as a valid instance_id.
When we look at the following request:

> PUT /v2/service_instances/:instance_id

- which charset is allowed?
- which encoding is used in the request url?
- how lang is the instance_id allowed to be?
E.g. all of that is relevant when persisting a new instance in a relational database.

On some places the specs explicitly uses a guid .

> /v2/service_instances/:guid/...

In my opinion the spec could more precise when we reduce the instance_id to only guid values allowed and a specific representation (dashes, lowercase letters, ...)

That's also true for some other id fields where the spec currently says a "GUID is recommended".

**Comment by shalako** [comment]
Good idea. I'd recommend UUIDs everywhere.

**Comment by mattmcneeney** [comment]
@shalako We still don't have any requirements into the spec as to what `instance_id` and `binding_id` must be (only that they are a "globally unique identifier"). Do you still think we should add this clarification to the spec?

**Comment by duglin** [comment]
just today we came across a case in kube where someone had a broker that use a dot in their ID ( https://github.com/kubernetes-incubator/service-catalog/pull/1038 ) and it worries me that if we tighten up the language here we'll break people. I'm not sure how we do this w/o considering it a breaking change.

One other point to consider... why tighten it?  Ignoring the question about the charset, why should it matter what the string looks like?

**Comment by shalako** [comment]
@duglin This is `instance_id`, which is a platform provided identifier. I believe you may be referring to `service_id` or `plan_id`, which are broker provided identifiers.

I recommend we update the spec to set expectations for broker authors that platforms will send UUIDs.

**Comment by duglin** [comment]
what's the difference between those two sets of IDs aside from which side is creating it?

**Comment by shalako** [comment]
The difference is that platforms aren't sending anything besides UUIDs for `instance_id` and `binding_id`. As there's no variability in the wild (as there is for `service_id` and `plan_id`) we can be explicit in our language without breaking the contract.

**Comment by duglin** [comment]
ah, because CF is the only existing impl - lucky :-)

**Comment by duglin** [comment]
PR: https://github.com/openservicebrokerapi/servicebroker/pull/270
