### ISSUE TITLE
missing billing reference

### ISSUE THREAD

**Issue by mayrstefan** [openservicebrokerapi/servicebroker#119]
The service catalog can provide plans with costs. When a service is provided from a third party there is no specification or recommendation how to pass billing or account information to the service provider.

A possible solution could be to extend the plan metadata by required parameters for the service creation

Plan Metadata Field:
```
"metadata":{
   ...
   "requires": [ "accountNumber" ],
  ...
}
```

When creating a service instance:
```
{
 ....
  "parameters":        {
    "accountNumber": 123456789
  }
}
```

**Comment by angarg12** [comment]
For record, how to include pricing, billing and other business operations in the spec was discussed, and my understanding is that it won't be considered for the time being. Another spec effort focused on this kind of operations is being discussed, and it would be compatible with SB to handle specifically these situations.

Metadata and community driven are strictly speaking not part of the spec, so how much we should get involved on them is ill defined at the time. Please refer to #113 for more information.

**Comment by mayrstefan** [comment]
Even if the metadata fields are moved from the core specs into some community standard or profile: if there are costs there should be at least a recommendation on how to bill a service. Duglins comment looks like these community standards could be included in this repo aside the core servicebroker spec. This issue  should remain as a marker until something specific is decided on the location.

Maybe the idea to use a metadata field to mark some parameters as mandatory for service creation is generic enough to be included in the spec independent of the cost/billing issue. That could be split into a separate ticket if needed.

**Comment by angarg12** [comment]
If you mean marking input parameters as mandatory, that is included in the input parametrization proposal using JSON schema. The discussion is in #59.

**Comment by gberche-orange** [comment]
@mayrstefan @angarg12 This specific use-case of a service broker author requiring an account number was specifically drafted as part of the ["catalog-attached schema" proposal](https://docs.google.com/document/d/1-IKI-PwPnhtbK0su1UzWA_UoyaCjL8S2d6ky3Xmuwvg/edit#heading=h.g87gk1t0z7p0) with [example schemas](https://github.com/orange-cloudfoundry/servicebroker/tree/dialogue-http-schema/tests/schema/use_cases/billing_account) supporting this [use-case](https://github.com/orange-cloudfoundry/servicebroker/blob/dialogue-http-schema/tests/schema/use_cases/billing_account/billing-account.feature)

As there are current discussions on pros and cons of each input schema proposals it might be worth providing feedback related to the accounting use-case, and possibly join the call planned on thursday 1/11

/CC @bmelville @avade

**Comment by mattmcneeney** [comment]
CF currently handles billing outside of this spec. If there are no immediate desired for a platform to resolve this, should we close this issue? @angarg12 @shalako

**Comment by angarg12** [comment]
If this becomes a concern in the future we will create a new proposal.
