### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by mayrstefan** [openservicebrokerapi/servicebroker#120]
The spec contains some links that result in a 404 not found
- "Application Log Streaming" app-log-streaming.md
- "Route Services" route-services.md
- "Volume Services" volume-services.md
- "Service Metadata" catalog-metadata.md
- "Dashboard SSO feature" dashboard-sso.md
- "Binding Credential" binding-credentials.md
- "Manage Application Requests with Route Services" route-binding.md
- "service broker v2.10 format for volume mounts" volume-services-v2.10.md
- "Quota Plans" external link to docs.cloudfoundry.org
- "Example Service Brokers" examples.md
- "v1 broker API" api-v1.md
- "Service Broker API" api.md

Some of the links are part of a paragraph that looks like it is referencing itself or an incomplete paragraph.
E.g. #application-log-streaming

> Application Log Streaming
> ...
> For details, see Application Log Streaming.

**Comment by duglin** [comment]
@mayrstefan thanks for the issue but the spec is in the process of being totally redone from the CF's source repo - that's why no edits have gone in recently. I expect most (if not all) of these links to be fixed when that work is completed.

We can keep this open to make sure we get 'em though.

**Comment by angarg12** [comment]
I'll close this issue as the spec has changed heavily ever since. If there are new broken links in the current version, either this issue or a new one can be opened.
