### ISSUE TITLE
Differentiate endpoint information in binding credentials

### ISSUE THREAD

**Issue by bmelville** [openservicebrokerapi/servicebroker#121]
Bindings return several pieces of information as part of the credential response. One key set of data is endpoint information necessary for connecting to the service. There is currently no way of differentiating this information, but it is critical to be able to access from an automated system for establishing network connectivity in various ways as part of the binding consumption process.

This problem is exacerbated by the fact that many different brokers expose endpoint information under different field names, e.g., `ip`, `host`, `hostname`, `address`.

We need the ability to understand endpoint information about a binding, including both address/hostname and port, whether it is by annotation in a schema (requires #116), or by making these concrete fields. 

Proposal is introduced as part of the proposal for #116: https://docs.google.com/document/d/1JbsJgqgNtqthcfYwK_KbS6C8sjElrZNgoLhu40dUPAs/edit?usp=sharing

**Comment by arschles** [comment]
:+1:. My preference would be to at _least_ include some concrete fields. A schema could add more information to the returned data.

**Comment by bmelville** [comment]
I have introduced two proposals here: https://docs.google.com/document/d/1JbsJgqgNtqthcfYwK_KbS6C8sjElrZNgoLhu40dUPAs/edit?usp=sharing

**Comment by duglin** [comment]
on 8/29 call we decided to defer this for now

**Comment by mattmcneeney** [comment]
I believe this is going to be covered by #392, so closing this one
