### ISSUE TITLE
Reference implementation & Test suite

### ISSUE THREAD

**Issue by timjacobi** [openservicebrokerapi/servicebroker#125]
Hi Guys,

Really like seeing this effort taking place. I was wondering if there is or should be a reference implementation and a test suite that can be run against brokers implementing the spec?

**Comment by angarg12** [comment]
Yes, there is/will be reference implementations that will be acknowledged such as Cloud Foundry and Kubernetes. You can check the latter here:

https://github.com/kubernetes-incubator/service-catalog

Regarding tests, as far as I know it has been discussed. I am not aware that anything is on place right now.

**Comment by avade** [comment]
I think we should have a section of the site/repo with links to reference service brokers and cloud platform implementations.

There is interest in the group to create conformance test suite. 

For now, you can take a look at a service broker for Redis:

https://github.com/pivotal-cf/cf-redis-broker

**Comment by gberche-orange** [comment]
@timjacobi there was also this early effort https://github.com/cloudfoundry-incubator/cf-swagger#running-tck of a compatibility test suite

**Comment by timjacobi** [comment]
Thanks for info. If the idea of having a conformance test suite is going forward I would be interested in getting involved.

**Comment by mattmcneeney** [comment]
If the #252 PR (getting started page) resolves this, we should close this issue (@avade @angarg12)

**Comment by angarg12** [comment]
Closed by #252.
