### ISSUE TITLE
What is a plan?

### ISSUE THREAD

**Issue by jmrodri** [openservicebrokerapi/servicebroker#128]
The term *plan* is mentioned several times in the spec but it isn't clearly defined. It would be good to have it explained in the spec.

**Comment by angarg12** [comment]
Coming from Cloud Foundry, there are some concepts that are implicitly understood, but may be confusing for someone coming from outside. We can rephrase your question as a proposal, and then we can add some text in the API Overview explaining what a plan is.

If you find other confusing terms or concepts in the spec please add them to the list.

**Comment by shalako** [comment]
I submitted a PR to add a definition for service plan.
