### ISSUE TITLE
Service Object `requires` property uses permissions that seem CF-specific

### ISSUE THREAD

**Issue by martinmaly** [openservicebrokerapi/servicebroker#130]
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#-service-objects-

The `requires` property lists (currently limited) set of `syslog_drain`, `route_forwarding` and `volume_mount`. The permissions appear CF-specific. Is there plan to either extend this property to allow more general set of permissions, even implementation-specific ones, or is this field being removed as part of making the API more generic?

**Comment by angarg12** [comment]
#116 is a proposal that will generally address this. On the bigger picture, we want to support parametrised output for the binding operation. You can also check out #115 as an effort to remove (or at least deprecate) CF-only fields from the spec.

Please check if those efforts overlap with your request.

**Comment by martinmaly** [comment]
Thanks for the additional pointers. Hopefully even though the #115 doesn't seem to explicitly mention the `requires` property, it will be included and then replaced by binding schemas (and perhaps some additional mechanism, unless binding schemas also address issue of permissions).

**Comment by mattmcneeney** [comment]
I'm going to close this in favour of #392 which should open the door to having bindings defined by schemas rather than the `requires` property in the catalog.
