### ISSUE TITLE
Metadata spec appears to be missing from the spec

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#144]
Likely removed inadvertently in #131

**Comment by pmorie** [comment]
@shalako can we get this added back in?

**Comment by shalako** [comment]
Are you referring to this: http://docs.cloudfoundry.org/services/catalog-metadata.html

**Comment by vaikas-google** [comment]
The question was more about treatment of it, should we assume in the OSB that there are some expected fields, or should the entire object be treated as an opaque blob. We discussed this during the meeting today and it is a blob, little more details in the agenda doc.

**Comment by duglin** [comment]
I think this can be closed now due to #235 being merged.

Reopen if I'm mistaken.
