### ISSUE TITLE
Determine which metadata fields should be hoisted to top level.

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#152]
In the #144 and the discussions around it, it was decided that the Metadata (both service / plan) will be opaque. There are however some well known fields defined by the community and during discussions it was decided that we should investigate which of these fields should be lifted from the Metadata to one level up (Service / Plan). This bug is tracking that work.
Here are some examples for existing fields:
https://docs.cloudfoundry.org/services/catalog-metadata.html#services-metadata-fields
metadata.displayName
metadata.imageUrl

And:
https://docs.cloudfoundry.org/services/catalog-metadata.html#plan-metadata-fields
metadata.bullets
metadata.displayName

**Comment by mattmcneeney** [comment]
These fields are now tracked in the profile document, so closing this issue
