### ISSUE TITLE
Plan name format is ambiguous

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#154]
The plan name format should be spelled out in more detail; it is currently ambiguous whether underscores are allowed (they appear to be).  Preferably we would provide a regex in the spec for each type of name field.

**Comment by mattmcneeney** [comment]
Guidance was recently added to the spec for this:
`Therefore, this specification defines a "CLI-friendly" string as a short string that MUST only use alphanumeric characters, periods, and hyphens, with no spaces.`

Closing
