### ISSUE TITLE
Proposal: API versioning scheme 

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#161]
This dovetails with #158, which is about making a single version of the spec that has the accepted but not released features in it for broker authors to look over.  There is a similar need for implementers of both brokers and consuming platforms to be able to work with features that are not yet released in an explicit way.  The model of implementing an API feature fully in an unreleased version of a platform is not something that will be durable as we add consuming platforms.  For example, in the Kubernetes world, we are building out something which is still relatively immature from a technology standpoint.  It is not feasible for us to maintain a branch of the Kubernetes service catalog where we implement new features in the broker API while we continually release from another branch.  In Kubernetes, it is preferable to be able to incorporate 'alpha' features into our APIs and delineate them as being alpha, so that anyone from the community can try them out.

Another related need is for consuming platforms to work with brokers at different levels of the API.  For example, it seems likely that at some point, we will need to make a breaking change to the OSB API, necessitating a 3.x version of the API.  We cannot assume that all broker authors will update their brokers at the same rate, and therefore platforms that consume the API need to be able to determine what version of the API a broker speaks.

To be explicit, I propose that we solve the following problems:

1.  It should be possible for v2.x brokers to indicate which released version of the API they support
2.  v2.x brokers should be able to indicate when they support features that are 'accepted but not released' - which I will call 'experimental' in the remainder of this issue for brevity
3.  v2.x brokers that support experimental features should be able to indicate which specific experimental features they support
4.  It should be possible to individually version experimental features to express when such a feature is refined due to feedback/issues discovered during implementation

For now, I'm not proposing specific changes to solve these problems.  My goal is only to establish a consensus that as a group we understand these needs and feel like solving them is a worthy goal.

**Comment by angarg12** [comment]
Related to #98

**Comment by avade** [comment]
If you look at how the async create/update/delete feature was introduced [1] you see that the platform advertises if it will support async responses from the service broker for a given request.

Any service broker that is updated to support the version of the spec that this feature was in will understand this query parameter and can thus leverage the feature.

This is a fully backwards compatible approach to introducing a significant new feature.

The problem I see with this approach is that the discovery of the behaviour is discovered at request time, which may make it difficult for consuming clients to generate a UI.

Another pro of this approach is that it requires no change to existing brokers and these brokers will continue to work on any platform that supports v2 service brokers.

> 4. It should be possible to individually version experimental features to express when such a feature is refined due to feedback/issues discovered during implementation. 

Agree on this, we need a clear way to introduce and version experimental features in isolation.

[1] https://docs.cloudfoundry.org/services/api.html#asynchronous-operations

**Comment by duglin** [comment]
@avade The issue with the async approach is that this only works for optional features. And in particular, only in cases where the client is ok with the server ignoring the new flags. And in some cases there may not even be a way for the client to know if the flags were ignored or not, for example, in cases where the flag doesn't results in any visible change to the response message. Which means in the worst case, it needs to assume the flag was ignored and act as if it wasn't sent/used.  Not saying we can't use it for some new feature, just something to be aware of.

**Comment by mattmcneeney** [comment]
Is this still a problem for you @pmorie or any others?
