### ISSUE TITLE
dashboard_url and asynchronous provisioning

### ISSUE THREAD

**Issue by luksa** [openservicebrokerapi/servicebroker#170]
The spec requires the broker to return the `dashboard_url` immediately, even when it uses asynchronous provisioning. What if the URL isn't know at that point? There's currently no way to return it later.

**Comment by avade** [comment]
Have you got a use case at the moment of when the URL couldn't be predicted in advance? I can imagine use cases for this, but I haven't come across a solid need yet.

In Pivotal services, we often use the Go Router to handle dashboard routes and place them on a system domain, and these can be reserved in advance.

**Comment by pmorie** [comment]
Regardless of where we settle on this, we should make the spec clearer
about it.

**Comment by avade** [comment]
Agree we should call out that this is the ONLY chance to return dashboard URL. Want to make the PR?

**Comment by pmorie** [comment]
I'd be happy to make the PR once we sort out what @luksa needs to do

**Comment by luksa** [comment]
Nevermind. I thought I couldn't get the URL at that point yet. Turns out I can.

+1 on stating explicitly that's when the broker must return the URL

**Comment by pmorie** [comment]
Cool, I'll cut a PR for this momentarily.

**Comment by bmelville** [comment]
I think this issue remains, as in some services, the URL contains dynamically provisioned IP addresses or ports, which are not known until some time in the async process (e.g., provisioning wordpress instances, kubernetes clusters, etc. will need to provision an IP address before knowing the dashboard_url).

**Comment by mattmcneeney** [comment]
The spec now allows the `dashboard_url` to be fetched in the GET service instances endpoint, so this can be closed.
