### ISSUE TITLE
purpose of dashboardclient field?

### ISSUE THREAD

**Issue by bparees** [openservicebrokerapi/servicebroker#173]
It's not entirely clear to me how https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#dashboard-client-object- is intended to be used.

Since it is part of the catalog entry, and not a specific service instance, it would seem to assume that all service instances for a given catalog entry are going to share the same dashboard infrastructure, but that doesn't seem like a valid assumption.

Am I understanding the field(and implied limitations) correctly?

@pmorie

**Comment by duglin** [comment]
I suspect this it meant to be an admin thing, not a normal end user thing since most users don't actually see the output of the /v2/catalog request - just the platform does. So I'm guessing this URL is meant to be used by platform admins to do some kind of admin action on all of the instances/services that are related to the platform.

But perhaps @avade can weigh-in here.

**Comment by mcelep** [comment]
@bparees , [this](https://docs.cloudfoundry.org/services/dashboard-sso.html#registering-dashboard-client) explains what it is for.

**Comment by avade** [comment]
I think some of that CF content could be added to the spec.

@bparees if the link @mcelep provided answers your question, then I will PR an update to the spec.

**Comment by duglin** [comment]
I find that explanation to be confusing - are those creds really meant to be shared with ALL CF users?

**Comment by avade** [comment]
@shalako or @zrob  - can you clarify the use case?

**Comment by zrob** [comment]
CF specific answer: 

This value is how the broker requests to have an oauth client added to UAA.  That client is used to allow service broker dashboards to use SSO with the UAA. 

Given a broker has a UAA client and each service instance has an individualized service dashboard url.  When a user goes to that dashboard url they can be redirected to the UAA login page for SSO to the dashboard.  Now the user is signed in within the platform context and based on the permissions the user granted to the dashboard at sign in, the dashboard can apply permissions within the platform context.  Remember that brokers don't have a concept of space/org, so it must ask CF  for information regarding user permissions on a service instance.

**Comment by bparees** [comment]
thanks @zrob.  So effectively it's information related to the configuration of service instance dashboard SSO via UAA.

**Comment by avade** [comment]
@zrob so the CC currently takes the `dashboard_client` in the response and creates a UAA client that the broker can use to verify tokens provided in the SSO flow? Does the token also contain the scopes of the CF user?

**Comment by zrob** [comment]
Think of the SSO flow you see when you use google or facebook to sign into some third party.  The first time you sign in it asks you what things you'll allow the third party to see: ie email address, home address, make posts on user behalf. The same thing is true here, the dashboard can ask for the user to allow certain things, the user can say yes or no, then based on those choices the dashboard can act as the user up to the level of granted permission.

**Comment by mattmcneeney** [comment]
`dashboard_client` has been moved to the [CF Catalog Extensions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#catalog-extensions) section of the profile doc, so closing this
