### ISSUE TITLE
Define a process for rotating credentials on bindings.

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#176]
Currently the way to rotate credentials on a binding is through the unbind/rebind process. Depending on what the unbind / bind operation does, this could be an unacceptable solution. If for example on a multi-tenant process, binding creates DB tables, then recreating them is not a good solution. As per the spec it's left at the discretion of the broker writer on how heavy the division of labor is between create instance and create binding which means it's difficult to know if unbind/rebind is an ok solution for rotating credentials.
There has been some work on returning a reference to a credential (credhub by CF) and presumably something like Vault could be used here for the same purpose. Just seems like we should at the very least provide guidance, if not find a way to provide support for this in the broker API itself.

**Comment by nilebox** [comment]
A relevant question. What is expected to happen if all the credentials of a particular service broker have been compromised? Should it nuke all the existing bindings? How does marketplace get notified about such changes? Probably having a GET request on bindings would be useful to re-sync the state of the bindings.

**Comment by duglin** [comment]
In addition to some way for the new creds to be provided to the platform, it might be good if there were a way for the platform to request new creds be created. For example, security policy for certain companies require passwords to be rotated every X days, or one of the users of a component has left the company and for security purposes they need to rotate the creds to make sure that ex-employee can't access the instances.

**Comment by mattmcneeney** [comment]
I'm not sure if this is still an issue for anyone, or if they have got around this by creating a new binding when they want to rotate credentials. Any thoughts?

**Comment by nilebox** [comment]
There is still no guidance for credential rotation process OSB, the question is whether OSB spec should have one? If there's no specific support for this process in OSB API (apart from unbind/bind), probably not? It should be up to a particular marketplace implementation.

**Comment by mattmcneeney** [comment]
From my perspective, allowing credential rotation via bind/unbind is OK for now. CF would actually struggle to do this today as we do not save the parameters that are sent on a bind request, but we have some brokers interfacing directly with a credentials store to enable these kind of workflows.

In the future, if we wanted to support this for any broker, I imagine we would simply save the parameters used for each binding so that we could replay the request.

**Comment by duglin** [comment]
One thing that I've never gotten a good handle on is when certain actions could involve $ and therefore asking people to do it may not be possible. I think creating Instances is an easy to associate with some potential cost and therefore asking someone to delete-n-recreate is probably a bad thing to suggest. Bindings however are iffy to me. On the one hand if you view it just as asking for some additional creds to access a service then it should seem like no big deal, and free. But, if you view it as an additional "user license" then $ might be a factor.

No answer, just thinking out loud...

**Comment by duglin** [comment]
We talked about this internally and for now we're ok with cred rotation being done via the creation of a new Bindings. This works well for CF today and I think it'll work well for Kube too. One of the advantages of doing it this way is that we don't get into the business of determining when the old creds are no longer valid - the platform (or user) can decide that on their own and let the Broker know by deleting the old Binding.

So, we're ok with closing this issue for now.
