### ISSUE TITLE
Scope/use of org, space and appGUID

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#183]
While we've agreed that org and space are too CF specific, and are in the process of replace them with "context", appGUID and CF's use of these three fields are things we should probably discuss.

In particular, CF will not allow the same app to bind to the same service instance more than once. Because of this, today's service brokers do not need to worry about things like seeing two different createBinding() requests that share the same org, space and appGUID.  The question is, should they care? Should the spec ban this situation?

I can't really think of a good reason why the spec should codify CF's current usage pattern with respect to this.  I think it might be fair, for some reason I can't think of right now, for a broker to reject two requests with the same values for org/space/appGUID - but that's an impl choice.

I'd like to see the spec add some text around this, something that says:
- the spec places no restrictions on how many bindings for the same instance an app can have
- brokers are free to use context & appGUID for whatever purpose they want. Including contacting the platform and using those fields to specify the context of the request, or using it to limit the usage pattern (e.g. only one binding per app)

Related to this though is the question of appGUID.  Right now the spec doesn't really place any restrictions on this property, ie. must it be unique? And it doesn't really define what an "app" is either.  

I suspect we probably can't be too prescriptive here since an "app" may mean different things in different platforms.  In CF is clear. In Kube its less clear.  It could mean a set of replicated images/containers, or it could mean a set of unrelated containers that just happen to share the same label. Or it could even be a namespace. The scope to which the binding applies may need to remain open.

My proposal for this would be to add text that says something like:
- "app" is meant to represent a platform specific scope to which a binding applies. And give some examples like CF's app, Kube's Deployments, Kube's namespaces....  The definition of what an app's scope is platform specific and not required to be static across all binding requests.  For example, in one it might refer to a namespace, but in another it might refer to a Deployment. Its a platform impl choice.
- app_guid MUST be unique within the platform

Thoughts?

**Comment by petereberlein** [comment]
In CF the app_guid is unique, independent of org and space. This makes sense as it is a GUID and it would be really strange if two apps - independent if where they are deployed - share the same GUID.

So +1 for documenting that the app_guid is globally unique.

A binding represents a 1:1 relationship between an app and a service instance. I think this is a reasonable restriction as the binding is used to communicate credentials to a service instance to an app. Why would I need to get two different sets of credentials to the same instance? Apps are free to bind to several instances of the same service, which I think should be sufficient - unless someone has a good use case that cannot be covered by this.

I'm not too familiar with the entities on Kubernetes but the motivation of bindings is somehow that every consumer gets their own set of credentials; for shared use of a service instance, they would all bind to that instance and get separate credentials, which is the cleaner solution than sharing the binding among different consumers.

**Comment by mattmcneeney** [comment]
I also only just noticed that `app_guid` (or `bind_resource.app_guid`) isn't a required field. Are there any use cases where this _shouldn't_ be sent? As @petereberlein says, the `app_guid` is the only field the broker can use to differentiate bindings for different 'apps' (or whatever relationship a binding represents in the calling platform).

**Comment by petereberlein** [comment]
Yes. If you create a Service Key instead of a binding, the app_guid field is not set. Service Keys are kind of "anonymous binding", ie. they provide the same credentials but they are not injected into an app environment; instead, you can read them from the command line and copy&paste to some application living outside of CF.
But brokers do always get a binding id, so they have a unique mandatory field to differentiate bindings (including Service Keys) from each other.

**Comment by duglin** [comment]
I agree with @petereberlein that CF and (to some degree the spec) push the idea of a 1:1 relationship between an app and an instance, and I can't think of a good reason why someone would want to create more than one binding between the two, but does that necessarily mean the spec should ban it?

As was mentioned, if you create a Service Key, or in spec terms create a binding w/o an app_guid,  the broker doesn't get to see the app_guid at all, so there's clearly a way around a 1:1 requirement we may put in the spec - so is it worth trying to codify it?

@petereberlein you talked about each consumer getting its own set of credentials, which is true, but what's kind of odd about the spec today is that the uniqueness of the consumer isn't unique itself :-) .   By that I mean, each binding has, potentially, 4 fields that make up the identity of the consumer:  binding-id, org-id, space-id and app_guid.  That's a lot, and its not clear what each is used for.  Which are brokers supposed to use for any kind of scope check? Are they supposed to (or allowed to) do any kind of scope checking at all?  The spec is vague on the true purpose of these fields - aside from each binding must have its a unique binding ID.

If I were starting from scratch I would say that the binding-id is all that should be needed to determine that a new consumer wants some creds. The org, space and app IDs are all just noise that the broker might find useful in some situations (like talking back to the platform) but they really should not be used for any kind of scope check to reject the createBinding request. I say this because its really the platform that should decide the scope of what an app is and the scope of the binding - the broker can't make that decision.

**Comment by petereberlein** [comment]
There can be many bindings to one service instance, so there can also be many Service Keys for one instance. But for one specific app there can be only one binding. 
I don't think that it would be a huge change to allow multiple bindings to the same app (the CF Controller experts may correct me) but it is certainly easier to rely on this as CF does today. So without need I would not go for changing this.

I agree that the binding id is the one relevant for mapping to a specific consumer. In the past you could have used the app_guid as well but when Service Keys were introduced this field became optional and you are left with the binding id.

Other information like org, space and app_guid are to be used for different purposes. For example. you use these fields when writing metering information to Abacus, the CF metering solution. Or do some other stuff like you already mentioned (e.g. adjust security groups of a space to give it access to the service instance). I agree that they are not to be used for scope checks to reject the createBinding request.
