### ISSUE TITLE
Preventing other operations during an ongoing async op

### ISSUE THREAD

**Issue by luksa** [openservicebrokerapi/servicebroker#184]
The spec says:

> For example, if a broker is in the process of provisioning an instance asynchronously, the marketplace can not allow any update, bind, unbind, or deprovision requests to be made through the platform. A user who attempts to perform one of these actions while an operation is already in progress MUST receive an HTTP 400 response with the error message: Another operation for this service instance is in progress.

The second sentence is probably trying to say the _broker_ must return 400? (The first sentence talks about the platform preventing users from doing this, so it's not clear whether the second sentence is talking about the platform returning 400 or the broker.)

Also, "a user MUST _receive_" is kinda weird in itself.

**Comment by mattmcneeney** [comment]
I agree, and this kind of ties in with #193. I don't think we should be stating that platforms MUST do anything, only what they SHOULD do in different circumstances.

Brokers MUST return XXX in various situations is definitely a better way of stating this.

**Comment by mattmcneeney** [comment]
I believe this has now been fixed in the spec (see [PR](https://github.com/openservicebrokerapi/servicebroker/pull/300)). Closing.
