### ISSUE TITLE
Add catalog management text

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#189]
See: https://docs.cloudfoundry.org/services/managing-service-brokers.html#catalog-validation

I think our spec needs some of this text, in particular the stuff from the "Catalog Validation Behaviors" section.

**Comment by mattmcneeney** [comment]
Note that the possible errors section states that a HTTP 500 should be returned for invalid basic auth credentials, but our spec (correctly IMO) that an HTTP 401 is returned.

It raises an interesting question of how much we want the spec to detail what platforms _should_ do (like validating catalogs). The same question came up with the JSON schemas work.

**Comment by pmorie** [comment]
> It raises an interesting question of how much we want the spec to detail what platforms should do (like validating catalogs). The same question came up with the JSON schemas work.

My subjective opinion: platforms need to handle the fundamentals of interacting with the API correctly.  One example: in the kubernetes SIG, it wasn't immediately clear to us that we could not use the name of a service/plan as a coordinate for it.  This would be helpful for platform implementers.

Up until this point, the spec seems to be mostly for people implementing brokers.  Now that we have multiple platforms implementing the API from the consuming end, I think it would make sense to either have a platform-implementer spec or be specific in the main spec about what content is intended for the platform author and what is intended for the broker author.

**Comment by duglin** [comment]
I think https://github.com/openservicebrokerapi/servicebroker/pull/288 should cover this
