### ISSUE TITLE
Stopping an async, or any, request

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#196]
While working on https://github.com/openservicebrokerapi/servicebroker/pull/193 and https://github.com/openservicebrokerapi/servicebroker/issues/195 it dawned on me that the spec doesn't really talk much about what to do when things get stuck. For example, what if during a createInstance() call things just hang?  Regardless of whether its an async or sync request.  What is the platform to do?  The current spec doesn't provide any help because it mandates that the platform can not send ANY other request while there's an outstanding request being processed. 

That's part of the reason I worded #193 the way I did - I wanted to loosen it a bit. I wanted to allow for the platform to send a DELETE at any time in order to recover from a hung request. The broker is always free to reject the DELETE request, but this at least gives the platform a way to try to kick/stop things.

This only helps in the createXXX() cases. For ops that can/should not be fixed via a DELETE we'll have to find some other solution, but I wanted to start with the easier problem first... the creates.

So, before I opened a PR I wanted to know what people thought about adding some text to make it clear that:
- a platform is free to send a DELETE at any time - not just because its done but also to stop the processing of an outstanding create() op
- a broker is free to reject the DELETE if its busy with a related op (point to text in #193)

Thoughts?

**Comment by SimyungYang** [comment]
I also ran into such a case. In my case, SB provision operation is processed in an async way, and I didn't implement the last_operation command in a proper way. The service creation was in progress forever. I eventually delete the service instance by "purge-service-instance".

LGTM on the assumption that cf platform will not send a DELETE after createXXX() command is successfully executed. If it does, SB cannot distinguish whether the command is called by cf platform or the user.

In case SB is working on a related job and it doesn't have a proper info(OrderId or VMId) to perform DELETE, it can reject the command.

**Comment by duglin** [comment]
> LGTM on the assumption that cf platform will not send a DELETE after createXXX() command is successfully executed. If it does, SB cannot distinguish whether the command is called by cf platform or the user.

But that's how it deletes it when it wants to remove it.  Also, in the spec there is no distinction between a platform and a user - its really just a platform (or broker client).

**Comment by SimyungYang** [comment]
I thought the cf platform, itself will send a DELETE at anytime after a certain period of time for the management reason to an unsuccessful service instance creation. Not by user's "cf delete-service" execution. That's what I meant. 

> a platform is free to send a DELETE at any time - not just because its done but also to stop the processing of an outstanding create() op

If the above means that DELETE command is called by user through API or cli command, I think it is okay.

**Comment by arschles** [comment]
We have a use case for this in [service-catalog](https://github.com/kubernetes-incubator/service-catalog). We have a Kubernetes resource called and `Instance` that says "the provisioning is ongoing, please check back later." When the provisioning is done, the status of the `Instance` changes to "done".

There are some cases where the provisioning needs to be cancelled -- one notable one is if the user decides to delete the `Instance`, service-catalog needs to cancel the provisioning. If the spec added the ability to send a `DELETE` to the broker even while an async provision is ongoing, that would be enough functionality to solve this use-case.

**Comment by arschles** [comment]
@duglin any objections to me writing a design proposal for cancelling async (de)provision for now? We can extend it to async (un)binding as a follow-up.

**Comment by duglin** [comment]
@arschles go for it.  I'm assuming it'll cover #278 too

**Comment by mattmcneeney** [comment]
@duglin / @arschles is this still a priority for either of you?
