### ISSUE TITLE
Consider adding appguid to unbind and space/org to deprovision

### ISSUE THREAD

**Issue by youngm** [openservicebrokerapi/servicebroker#201]
I have run into cases where this information comes in handy at unbind.  Today I have to query the cloud controller for this data.  If sent in during bind/provision why not send them during unbind/deprovision as well?

I know the new spec is looking at changing the way these cloud specific values are sent.  i don't think this request would get in the way.

**Comment by mattmcneeney** [comment]
@youngm is this still a problem for you?

**Comment by youngm** [comment]
@mattmcneeney I still think it would be useful to have this information.  Though, I can see how it may be technically tricky to send a context object on DELETE.

I still have the same workarounds today that I had before.  Either hold the state in the broker on provisioning or query the CC.  So, I'm not held in my broker creation by the lack of this feature.

**Comment by mattmcneeney** [comment]
That makes sense, thanks for the quick reply. This isn't the first time having contextual information on DELETE requests has come up; but as you say, we just haven't found a neat solution for this yet.

Any thoughts @duglin ?

**Comment by fmui** [comment]
If nobody comes up with a good solution, we will close this issue soon.
