### ISSUE TITLE
Consider providing a sample broker in the repo

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#204]
I think we should provide a sample implementation of a broker for at least these reasons:
 1. Spec without some code is always weaker
 2. Could provide the 'reference implementation' or conformance 
 3. Would make it easier for prospective SB writers to get started with some code laying around.

**Comment by bparees** [comment]
we're attempting to do so here:
https://github.com/openshift/open-service-broker-sdk

(it's somewhere in between a sample/reference implementation, and an SDK)

**Comment by bparees** [comment]
(PR to provide a better explanation of how to use it here: https://github.com/openshift/open-service-broker-sdk/pull/18)

**Comment by mattmcneeney** [comment]
One of the pros of moving to Swagger was that code could be generated in a range of languages automatically from the spec. Would we want to have the example broker in the same repository as the spec?

**Comment by mattmcneeney** [comment]
@vaikas-google Can we close this issue now that we're adding a sample brokers page to the repo in #252 ?

**Comment by avade** [comment]
https://github.com/openservicebrokerapi/servicebroker/blob/master/gettingStarted.md is the page closing
