### ISSUE TITLE
Can a service have zero plans?

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#206]
If yes then we should say so in the spec and perhaps give a reason for it.
If not then we should mandate that the list can't be empty.

**Comment by pmorie** [comment]
As far as I understand, it cannot, because plan ID is required when provisioning.

**Comment by mattmcneeney** [comment]
If you register a service in CF today with no plans, I think we just hide it from the marketplace. I can't think of any reason for a service broker to either have no services, or a service with no plans, as I don't think we have a use case for which this would be useful for platforms.

I'd be keen to explicitly state that a broker must expose at least one service, and that services must expose at least one plan.

**Comment by avade** [comment]
> I'd be keen to explicitly state that a broker must expose at least one service, and that services must expose at least one plan.

Agreed - want to draft a PR?

**Comment by mattmcneeney** [comment]
Done!

**Comment by duglin** [comment]
Closing since this was addressed in PR #212
