### ISSUE TITLE
Expand spec to allow for "no changes" semantics to be returned by brokers

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#209]
Currently when a catalog is fetched from the broker, the broker returns the entire catalog. There might be cases where generating the catalog is expensive, or the catalog returned is quite large. Some controllers might also refetch the catalog on regular basis (like kubernetes service catalog), and having a way for the controller to specify what the latest version (or the time it last fetched it) and having a broker respond with no changes would make it easier for controller writers to just check the response without doing diffs on existing vs. new catalog.
Seems like with the if-match and if-not-modified-since or if-not-modified-since as optionally being allowed to be returned by a broker would achieve this.

**Comment by avade** [comment]
If the catalog was versioned this would be an easy query for the broker.

**Comment by pmorie** [comment]
This is important to us at RH; I think versioning the catalog and adding an endpoint to get the latest catalog version is probably a good approach.

**Comment by pmorie** [comment]
Also related to this: deltas-only catalog payload
