### ISSUE TITLE
Verify that the service broker CLI API aligns with CF's defintion

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#22]
This is for the client->service registry flow.

I'm referring to the following CF `cf` calls:

```
service-brokers List service brokers
create-service-broker Create a service broker
update-service-broker Update a service broker
delete-service-broker Delete a service broker
rename-service-broker Rename a service broker
purge-service-offering Recursively remove a service and child objects from Cloud Foundry database without making requests to a service broker
```

**Comment by duglin** [comment]
https://docs.cloudfoundry.org/services/api.html

**Comment by duglin** [comment]
service-brokers                        List service brokers
   create-service-broker                  Create a service broker
   update-service-broker                  Update a service broker
   delete-service-broker                  Delete a service broker
   rename-service-broker                  Rename a service broker
   purge-service-offering                 Recursively remove a service and child objects from Cloud Foundry database without making requests to a service broker

too

**Comment by duglin** [comment]
add unit testcases too

**Comment by duglin** [comment]
create-service-broker one is completed.

**Comment by MHBauer** [comment]
In terms of the new client, is `create-service-broker`
`sc brokers create SB_NAME SB_URL -u SB_USER -p SB_PASSWORD`

**Comment by vaikas-google** [comment]
yep.
