### ISSUE TITLE
accepts_incomplete within service instance request body

### ISSUE THREAD

**Issue by dizz** [openservicebrokerapi/servicebroker#220]
Looking at the spec it appears that ```accepts_incomplete``` should always be a query string parameter, yet in the [service instance request spec](https://github.com/openservicebrokerapi/servicebroker/blame/v2.11/spec.md#L359) it says that this should be part of the body. This is a little inconsistent but perhaps it's an oversight or tight RFC2616 compliance (even though a body is supplied). Anyone got a comment on this?

**Comment by duglin** [comment]
This has been fixed in the latest version of the spec:  https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md

**Comment by dizz** [comment]
Thanks @duglin
