### ISSUE TITLE
What are the requirements for compliant brokers?

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#224]
On today's Kube svc-cat weekly call there was a question about what the requirements are for brokers beyond compliance with the RFC2119 keywords in the spec.  The specific example raised related to the idea of whether its ok for a Broker to be written such that it can only talk with one particular platform, instead of being able to provide services for **any** platform.  For example, is it ok for the broker to only understand CF's profiled version of "context" but not Kubernete's?

My take on this is that yes this is ok. There are lots of optional things in the spec and for some implementations (either platform or broker) these optional things might be required because they want to do some advanced, or certain, things - such as support routing services.  To me, the specifics of the "context" property is just one of those things.  For example, a broker could choose to treat it as an opaque blob and then it can probably talk to any platform, or it could choose to only know what kubernetes "namespaces" are and therefore only work with kube because the features it wants to support only work in a kube environment (e.g. volume management). 

Having said all of that, I do certainly understand the desire for 100% interop where any broker can work on against any platform, and while its possible to do that (if you avoid the optional aspects of the spec), I think in practice we've seen too many cases where brokers will need to know the specifics of the platform, and only work in certain environments with certain features, and therefore we can't guarantee 100% interop in all cases.

Anyway.... I said I'd raise the issue over here so we can discuss it and see if there's anything we want to say in the spec about this.

/cc @martinmaly

**Comment by mattmcneeney** [comment]
ping @duglin is this still relevant?
