### ISSUE TITLE
Require service brokers to be stateful?

### ISSUE THREAD

**Issue by nilebox** [openservicebrokerapi/servicebroker#225]
Requiring all service brokers to be **stateful** would make the API and spec much cleaner and remove the ambiguity from it, and make it easier to support from the marketplace side:

- Idempotency
As mentioned in https://github.com/openservicebrokerapi/servicebroker/issues/195, the OSB REST API was designed with idempotency in mind, which simply cannot be achieved without statefulness of service brokers.
    - It solves the orphans handling issue: https://github.com/openservicebrokerapi/servicebroker/issues/182
    - It allows us to correctly handle not only request timeouts, but also finishing the provisioning/binding after recovering from the network issue, or the downtime of marketplace or service broker

- `GET` requests support
Currently there is no way to sync the state of the system once request has timed out (or connection was lost). It would also be valuable if something has changed inside broker itself (for example, credentials were revoked) and we have a signal to resync the state in the marketplace.

- Remove the need to pass all the information previously provided by the marketplace to the service broker, for example `previous_values`

- Replacing `lastoperation` with `operation/{operationId}`
It's natural to provide the history of the operations happened in the past.

This change is probably going to break the backward compatibility with existing _stateless_ CF-flavoured service brokers (stateful brokers won't be affected), but doesn't require any change in the REST API itself. As I said, the API itself feels like it is _idempotent_, but it's clearly not from reading the spec, which is very confusing.

**Comment by nilebox** [comment]
Just found another ambiguous section in the spec: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#blocking-operations

> The marketplace MUST ensure that service brokers do not receive requests for a service instance while an asynchronous operation is in progress. For example, if a broker is in the process of provisioning a service instance asynchronously, the marketplace can not allow any update, bind, unbind, or deprovision requests to be made through the platform.

How does marketplace know if there is an ongoing asynchronous operation if the request has timed out and there is no `GET` endpoint? Also, this requirement contradicts already mentioned "Orphans" section, where it clearly says that marketplace must `DELETE` (deprovision) the service instance, if the provisioning request has timed out.

Again, making service broker stateful, and adding features mentioned above, solves this problem.

**Comment by shalako** [comment]
From a marketplace author perspective, it would be so much easier if brokers were stateful. Historically, we have added conveniences to enable some brokers to be stateless and more recently these conveniences have grown. The line for how much state the marketplace is responsible for is pushing more and more on the marketplace. 

Part of why this API is attractive is that it is easy for service producers to implement. Whenever we put the burden of more state on them, it becomes more complex. If this API isn't easy to implement, adoption may suffer.

**Comment by avade** [comment]
@nilebox "How does marketplace know if there is an ongoing asynchronous operation if the request has timed out and there is no GET endpoint? Also, this requirement contradicts already mentioned "Orphans" section, where it clearly says that marketplace must DELETE (deprovision) the service instance, if the provisioning request has timed out."

For async requests the platform is polling [last-operation](https://docs.cloudfoundry.org/services/api.html#polling) until a result is given. Cloud Foundry by default will do this for a week.

Cloud Foundry keeps track of service instances with unresolved async operations.

**Comment by nilebox** [comment]
@avade makes sense. What about the **synchronous** provisioning request which times out though? Is it assumed not having any ongoing operation straight away?

Is there orphan mitigation for synchronous requests in CF at all?

**Comment by shalako** [comment]
@nilebox Yes, CF does orphan mitigation for both synchronous and asynchronous operations. Example: if a synchronous provision requests times out, CF considers the request failed and sends a delete request to attempt to clean up the resource on the broker side.

**Comment by mattmcneeney** [comment]
I don't think this requirement is viable (at least not until we do v3) - so I've added it to the [Ideas for v3](https://github.com/openservicebrokerapi/servicebroker/wiki/Ideas-for-v3) wiki page and will close this here.
