### ISSUE TITLE
Deprovision when provision failed

### ISSUE THREAD

**Issue by jim-minter** [openservicebrokerapi/servicebroker#247]
I couldn't find an answer to this question in the spec: if a broker returns an error on provision, does the spec define whether deprovision may/should be called?
I think that the broker should expect to be able to handle such a deprovision call, but I'm not sure if a compliant caller should be expected to call deprovision in this case, or whether it should be allowed to.

**Comment by duglin** [comment]
see: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans  it kind of depends on the error returned by the broker.  Which error were you thinking of?

**Comment by arschles** [comment]
Ref https://github.com/openservicebrokerapi/servicebroker/pull/254, as that patch sharpens up some of the relevant language

**Comment by pmorie** [comment]
I believe this is resolved by https://github.com/openservicebrokerapi/servicebroker/pull/353 - does anyone disagree?

**Comment by jim-minter** [comment]
I'm happy for this issue to be closed.
