### ISSUE TITLE
platform unique names

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#249]
In the spec we have `This MUST be globally unique within a platform marketplace` for service name. Its odd to place this requirement on the broker when, in theory, it has no idea what other services are available in the platform's marketplace.

I think it would be better to make this a (sort of) requirement on the platform - something like:
```
This MUST be unique across all services objects returned in this response.
Platforms will typically use this value as an input parameter from their users to indicate which service they want to instantiate. To ensure the value is unique across all services from all brokers in their marketplace, Platforms might need to modify these values before presenting them to their users to ensure there are not conflicts. This specification places no requirements on how Platforms use this value.
```

Wanted to hear what people thought before I opened a PR for this.

**Comment by nilebox** [comment]
@duglin agreed, we can only require service broker to provide uniqueness within itself, not across the entire marketplace.

**Comment by mattmcneeney** [comment]
@duglin Do we want to provide a little extra guidance here following the conversation we had at the Office Hours at CF Summit?

Broker names usually contain the name of the service itself (ie. mysql) prefixed by the name of a company/product. For example, all Pivotal services start with `p-`, so a Pivotal MySQL service broker would be named `p-mysql`.

As of today, I'm not sure if any platform will automatically change the name (and we discussed that broker authors probably would not want that), and in a CF world it will just fail to register a second broker with the same name, so the more guidance we can provide here to encourage unique naming, the better!

**Comment by avade** [comment]
Adding this will make the specification clearer, so I would LGTM a PR for this. 

The other option we discussed at summit was a first-class supplier/vendor identity field in the catalog that could be used by platforms as a composite identifier for services `$supplier-$service-name`.
