### ISSUE TITLE
Orphan handling for deprovisioning and unbinding

### ISSUE THREAD

**Issue by arschles** [openservicebrokerapi/servicebroker#255]
The [unbinding section](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#unbinding) and [deprovisioning section](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#deprovisioning) both have language that indicates HTTP responses with status codes not in the respective tables in those sections indicate that instance or binding will remain in the system, respectively. 

Would it be possible to add some optional behavior that allows the marketplace to re-try the deprovision/unbind operation (maybe N more times)? This would be nice behavior because intermittent errors in brokers could cause a temporary "unexpected" error code, and a retry could succeed.

**Comment by nilebox** [comment]
That's actually surprising given that in  https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans section it requires to continuously retry deleting/deprovisioning:
> To mitigate orphan service instances and bindings, the marketplace SHOULD attempt to delete resources it cannot be sure were successfully created, and SHOULD keep trying to delete them until the broker responds with a success.

It's exactly the same request, and I don't see why it should be abandoned with remaining instance in case of any failure

**Comment by arschles** [comment]
@nilebox agree. note that there's also explicit language in the [deprovision](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-6) and [unbinding](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-5) sections that say that instances/bindings will be orphaned on any error. For example:

>Responses with any other status code will be interpreted as a failure and the service instance will remain in the marketplace database. Brokers can include a user-facing message in the description field; for details see Broker Errors.

Since the orphans section contradicts that language, this issue may be related to https://github.com/openservicebrokerapi/servicebroker/pull/254, which removes the section altogether.

**Comment by avade** [comment]
@zrob what do we do in CF?

**Comment by zrob** [comment]
There's quite a bit of code to dig through to understand the orphan mitigation behaviors, but here's my current understanding.

There are two forms of orphan mitigation that CC attempts.
1. exponential backoff retried requests to a broker
1. one-time fire and forget request to a broker

The fire and forget cleanups  are called when "create" operations fail -- provision, bind
The retry cleanups are called for "destroy" operation failures -- deprovision, unbind

I'm not sure I entirely understand the reason though.  I suspect it is because in the destroy case, we can assume we successfully have a broker record, so retrying makes sense.  For the create case, we may not know if the create succeeded on the broker side or not and we may not have a record on the CC side, so we make a one-off attempt just in case.

**Comment by nilebox** [comment]
@zrob this doesn't look consistent.

Even though we don't know for sure whether broker succeeded creating a record (i.e. provisioning), it could lead to abandoned provisioned resources wasting money (and that's what CF is trying hard to prevent with orphan mitigation, if I understand correctly). It is safer to try deleting a potentially provisioned resource, and correctly handle the case when broker record didn't exist.

The fire-and-forget one-time request could easily fail, so I wouldn't consider it to be reliable at all. It is basically an "at _most_ once" semantics request which provide no guarantee.

**Comment by zrob** [comment]
@nilebox you're correct, i took a deeper dive into the implementation and updated my original comment

In response to the issue, I'm not sure I would consider this an orphan issue or even an issue that should be called out in the spec.  If a platform encounters an error from the broker then it should keep its record of the instance or binding and there is therefore no orphan.  If a platform chooses to implement retries, then that seems like a valid implementation orthogonal to the spec, so long as the platform does not remove its own reference to the instance or binding if the broker is not returning successful responses.

**Comment by nilebox** [comment]
> Fire and forget is attempted for provision in the following cases:
> - Valid broker response, but CC fails to to record database changes

This doesn't look right either - for consistency the platform should create a database record _before_ it sends a request to broker, and thus it should be able to retry and cleanup no matter at which stage it happens. If it fails to record database changes, it should just perform a cleanup at the beginning of the next retry iteration.

Whether this should be part of the spec at all - not sure.

**Comment by mattmcneeney** [comment]
I believe the new orphan mitigation section makes this behaviour much clearer. Please reopen if I am mistaken.
