### ISSUE TITLE
Incorrect http status code listing for orphan handling

### ISSUE THREAD

**Issue by rajanra** [openservicebrokerapi/servicebroker#256]
The list of http status codes for handling orphans recommends anything other than 200 and 201 to be interpreted by platform as failure. This is in contrary to what is specified for provision  API where a 202 is a valid response from service broker(for asynchronous handling). 

The table in the orphan section should be updated to treat 202 as a success response for which there is no need to initiate an orphan mitigation.

**Comment by duglin** [comment]
@arschles perhaps we can cover this issue as part of the work in https://github.com/openservicebrokerapi/servicebroker/pull/254  ?

**Comment by arschles** [comment]
@duglin @rajanra this will indeed be covered by #254

**Comment by mattmcneeney** [comment]
Thanks @rajanra - it sounds like this is going to be covered by #254. Does someone from the PMC want to close this a duplicate?

**Comment by duglin** [comment]
closing as #254 should cover it. If it doesn't then we'll reopen it.
