### ISSUE TITLE
Allow paths as suffixes for broker request URLs

### ISSUE THREAD

**Issue by bmelville** [openservicebrokerapi/servicebroker#257]
### Goal
We have several scenarios where brokers need to be exposed from endpoints that are not just a base hostname/port pair, but also contain path elements. We would like to be able to expose the broker API endpoints as path suffixes on an existing base path, and include the path as part of the broker URL when registering it with the platform.

### Current model
Currently brokers must be registered as root hosts, e.g.,

```
Broker: http://mybroker.mycompany.com:8080
Username: me
Password: supersecret
```

Calls must always be made to broker spec paths as the root path, e.g., `http://mybroker.mycompany.com:8080/v2/catalog`. This is because they are specified in the spec as HTTP calls like `GET /v2/catalog`.

### Proposed change
We would like to be able to register brokers including a base path, such as

```
Broker: http://mybroker.mycompany.com:8080/some/base/path
Username: me
Password: supersecret
```

Broker spec paths are then appended to whatever broker URI has been registered, e.g., `http://mybroker.mycompany.com:8080/some/base/path/v2/catalog`.

**Comment by arschles** [comment]
Worth noting that I believe this is already achievable in Kubernetes service-catalog because you submit a base URL for each broker, which may include a path.

**Comment by bmelville** [comment]
Yes you are correct, each broker path is a format string prefixed by the provided broker URL.

**Comment by arschles** [comment]
Agreed

**Comment by mattmcneeney** [comment]
This is also possible today in Cloud Foundry. Like Kubernetes service-catalog, you can just submit a base URL for each broker which may include a path.

Is there somewhere in the spec that needs updating to make this clear?

**Comment by bmelville** [comment]
The spec is defined as raw HTTP calls for each method, e.g.,

```
GET /v2/catalog
PUT /v2/service_instances/:instance_id
```

However! I just happened upon this section from the spec, and perhaps is sufficient for my request.

> A platform marketplace may expose services from one or many service brokers, and an individual service broker may support one or many platform marketplaces using different URL prefixes and credentials.

So the main question is: is the intention to allow prefix URLs as part of the spec? And is the section I quoted intended to convey that?

**Comment by bmelville** [comment]
I am actually going to reopen this. It would be good to have this be more explicit in the spec to specify that path prefixing is required by the platform.

I am happy to draft this change.

**Comment by avade** [comment]
@bmelville yes, I think it is worth clarifying that API paths can be prefixed. Can you explain the problem that having a base path solves for you?

I think the design problem of supporting multiple platforms from multiple vendors is one we could provide guidance/patterns for.

**Comment by bmelville** [comment]
A concrete use-case is a broker which exposes a different catalog of managed services based on the path. For example, `broker.foo.com/catalog1/v2/catalog` and `broker.foo.com/catalog2/v2/catalog` expose different catalogs of services, and are thus managed as logically separate brokers.

This is slightly different from a single broker supporting multiple platforms, and I might call it more of a "multi-tenant" broker platform.

**Comment by mattmcneeney** [comment]
@bmelville I agree that it would be better to have this more explicitly stated in the spec. Do you want to have a go at drafting the change?

**Comment by bmelville** [comment]
Yes I plan to give it some thought and hopefully have a PR for review this week!

**Comment by mattmcneeney** [comment]
I believe this is resolved by this line in the spec:
```
A Platform MAY expose services from one or many Service Brokers, and an individual Service Broker MAY support one or many Platforms using different URL prefixes and credentials.
```
Closing!
