### ISSUE TITLE
Provide broker with token for accessing the PaaS API

### ISSUE THREAD

**Issue by cnelson** [openservicebrokerapi/servicebroker#262]
It would be useful if when registering a service broker, we  could request that a scoped token that could be used to make API requests against the PaaS be provided when an operation is requested. 

In CF this would be a token with a very limited lifetime, and a given set of scopes;  in the k8s world, perhaps a temporary user, or secret would be provided.

## Use case:
We frequently want our brokers to be aware of the PaaS it is  brokering services for  in order to perform actions on the PaaS on behalf of the user that are related to the service being provisioned.  

For example, we may want to add an application security group (or someday, dynamic egress) to the space a service is being provisioned for to provide access to [services that don't support other kinds of auth](https://cloudfoundry.slack.com/archives/C0JV2NPJ4/p1499723661995432).  Or we may want to [examine the configuration of an org/space before allowing service provisioning to continue
](https://github.com/18F/cf-cdn-service-broker/blob/df3131d512ebcd501837f4f8a7e0f866d7171d57/broker/broker.go#L285-L297)

Currently we handle this by provisioning a client and providing it to the broker as part of it's configuration but given that this frequently requires admin level permissions so it can act on all orgs and spaces, we'd like to see a more dynamic and temporary way of giving the broker access to the PaaS API.

Thoughts? cc: @jmcarp

**Comment by mattmcneeney** [comment]
Hey @cnelson,

Although we generally try to treat the API as one-directional, there are definitely use cases that require this (like autoscaling services that want to call back into the platform to scale an app).

There is an open issue ( #110 ) for brokers that require user identity to perform operations on a users' behalf, and we're also investigating how an auth flow other than Basic Auth would work ( #103 - I can see how an oAuth2 implementation could also help with this use case).

But, for your use case described above, we've been discussing another implementation option whereby when provisioning a service or binding, the request returns network policies that are required for any app to talk to the service instance. This leaves it up to the platform to decide whether or not to abide by the provided network policy, which IMO provides better security than allowing any service broker (how do you police this?) to make changes to network policies which could have terrible consequences.

What are your thoughts on that kind of solution?

**Comment by cnelson** [comment]
Sounds like #110 and having a way for the brokers to request network changes to the platform would solve our use-cases for now (and if others come up, I'm sure whatever is implemented for networking policies would be the right place to thinking about extending it if other admin-level use cases come up in the future)

I'll close this issue --  is there a proposal document or issue we can  follow for the networking configuration discussion?
