### ISSUE TITLE
Returning richer errors in operations

### ISSUE THREAD

**Issue by bmelville** [openservicebrokerapi/servicebroker#267]
A pattern we've used in the past that can be very beneficial is explicitly returning errors in failed operations. An optional extension is to also be able to return warning messages in "successful" operations for informational or actionable messaging (e.g., something being used is deprecated and should be updated).

### Problem
Currently the operation object has two fields, `state` and `description`, and relies on description to provide any message flow of errors or warnings. This has a few possible problems:

- Not explicit that `description` contains error/warning messaging
- Does not support multiple errors/warnings
- Does not support rich error/warning message metadata

### Proposal
I'd like to suggest the introduction of an explicit field for error messages, and if we choose, a similar field for warnings.

| Response field | Type | Description |
| --- | --- | --- |
| state* | string | Valid values are `in progress`, `succeeded`, and `failed`. While `"state": "in progress"`, the platform SHOULD continue polling. A response with `"state": "succeeded"` or `"state": "failed"` MUST cause the platform to cease polling. |
| description | string | A user-facing message displayed to the platform API client. Can be used to tell the user details about the status of the operation. If present, MUST be a non-empty string. |
| errors | array-of-objects | An array of JSON object containing error information about the operation. Only present when operation `"state": "failed"`. |
| warnings | array-of-objects | An array of JSON object containing warning information about the operation. Only present when operation is completed. |

The field(s) are arrays to allow for multiple distinct messages to be returned, and are objects to allow for richer metadata We would want to think through the actual structure of the objects, or whether it's sufficient to just be arrays of strings.

**Comment by jmrodri** [comment]
Why not group the errors and warnings into a single array-of-objects?

**Comment by bmelville** [comment]
What would that field be called? How would you differentiate the two in the event that both are surfaced from the same operation?

**Comment by mattmcneeney** [comment]
@bmelville Should the arrays of errors and warnings be arrays of strings? If we expect platforms to do something with these fields we should standardise what they look like. Arrays of strings makes most sense to me for now.

**Comment by bmelville** [comment]
String is definitely the easiest first step. We've seen situations where an error may benefit from more structure as well, so one possibility that leaves the door open to extensibility later is to have something like this:

```
type Operation {
  Errors []OperationInfo
  Warnings []OperationInfo
}

type OperationInfo {
  Message string
}
```

An operation response would look like:

```
operation:
  errors:
  - message: First error encountered.
  - message: There was also a second error...
  warnings:
  - message: ...and also a warning.
```

**Comment by martinmaly** [comment]
I support the OperationInfo style structure with a string message. A field that comes to mind as worth adding is an enum value indicating what type of error/warning it is, ideally from some canonical set. 

@jmrodri - combining errors and warnings into a single array-of-object (and adding a severity field - error, warning, ...) would have the downside that to find error the client needs to scan the whole array. That is why I would advocate for the 2-field solution (errors, warnings) that @bmelville sketched above (even if they are otherwise functionally equivalent)

**Comment by jmrodri** [comment]
@martinmaly that makes sense.

**Comment by mattmcneeney** [comment]
It's almost been 2 years since this came up - is this still top of mind for any folks or can we close it?

**Comment by jmrodri** [comment]
@mattmcneeney I'd vote close
