### ISSUE TITLE
Spec does not define expected status code when required fields are absent

### ISSUE THREAD

**Issue by krancour** [openservicebrokerapi/servicebroker#274]

**Comment by duglin** [comment]
While I'm not sure we need to say when to use all possible http error codes, I think this is a good one to call out and I'm thinking that a "400 Bad Request" is appropriate.

**Comment by krancour** [comment]
@duglin and that is how I've implemented it in the broker I am currently working on (because that seems the most common sense response), but like you, I do believe the spec should be explicit in this regard.

**Comment by duglin** [comment]
PR:  https://github.com/openservicebrokerapi/servicebroker/pull/275
