### ISSUE TITLE
Define more expected response codes for provisioning

### ISSUE THREAD

**Issue by krancour** [openservicebrokerapi/servicebroker#277]
The spec is clear that if a request to provision instance `x` is received, and the attributes of that request match an existing instance, then the broker should respond with a 200 or 202, depending on whether provisioning is complete or ongoing. If the attributes are different, it's a conflict-- 409.

What's conspicuously absent is any expectation of what is returned if the attributes of the new provisioning request match an existing instance, _but that instance is currently being deprovisioned._ This scenario _might_ not manifest with a well-behaved client, but for completeness, I believe the expected return code _should_ be explicitly defined for this scenario.

Personally, I find a 409 to be the most reasonable option for this case.

**Comment by duglin** [comment]
409 seems reasonable to me.

**Comment by mattmcneeney** [comment]
I believe with the new `ConcurrencyError` error code this is now resolved.
