### ISSUE TITLE
Define expected behavior for deprovisioning an instance in a "provisioning" state

### ISSUE THREAD

**Issue by krancour** [openservicebrokerapi/servicebroker#278]
Suppose provisioning is (asynchronously) ongoing for service instance `x`. Expected behavior is undefined if an attempt is made to deprovision an instance in such a state.

The easy answer is to say this equates to a conflict-- 409. However, I do believe there's probably room here to permit individual brokers to optimize. i.e. Some brokers may be capable of aborting provisioning.

Maybe we could say that brokers _may_ return a 409 in this case, or _may_ return a 200 or 202 if they are able to abort provisioning and immediately handle or accept, respectively, the deprovisioning request? This is just a though-- this scenario may require some discussion.

**Comment by duglin** [comment]
related: https://github.com/openservicebrokerapi/servicebroker/issues/196
