### ISSUE TITLE
Verify the cf cli APIs for user-defined services aligns with CF's defintion

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#28]
- [ ] Service Brokers
- [ ] Service Instances
- [ ] Service Bindings
- [ ] Services
- [ ] Service Plans

**Comment by duglin** [comment]
add unit testcases too

**Comment by bmelville** [comment]
I'm not sure if this is the right issue, but I have a PR in progress that aligns the service_controller API with the cloud controller API as defined here: https://apidocs.cloudfoundry.org/239/

**Comment by bmelville** [comment]
The RESTful path surface is aligned (for the methods we support). Remaining work I've seen is:

1) Align Request/Response object model,
2) Identify remaining methods to support in the open service controller.

This is probably not a comprehensive list though.

**Comment by shalako** [comment]
This does not appear to be related to the Open Broker API specification. Can we close it?

**Comment by duglin** [comment]
if we remove the code then yes, but let's resolve https://github.com/openservicebrokerapi/servicebroker/issues/102 first
