### ISSUE TITLE
If plan IDs are unique, why are service IDs required when provisioning?

### ISSUE THREAD

**Issue by krancour** [openservicebrokerapi/servicebroker#280]
This is one of several fronts on which brokers could potentially do what they need to do, while requiring less information from clients.

**Comment by duglin** [comment]
One of the base assumptions for OSB API is that brokers might be stateless, which means they may not have a mapping from plan to service.

**Comment by krancour** [comment]
@duglin, let us assume some broker is stateless. If that broker can serve the `/v2/catalog` endpoint (which is required, of course), then that broker knows (or _could_ know, if implemented appropriately) what plans are associated to what services. Statefulness isn't a pre-requisite for that.

**Comment by duglin** [comment]
I'm sure the Pivotal guys will give a better answer :-)  but my guess is that a broker querying all of the backends to get the info for a catalog request might be too expensive to do on each request for a new instance just to find the plan of interest.  (wild guess :-) )

**Comment by duglin** [comment]
ping @shalako - any thoughts on this one?

**Comment by mattmcneeney** [comment]
Brokers can also offer many services, so I guess it could make their logic cheaper too. @zrob may know why this was added to the service broker API in CF?

**Comment by nilebox** [comment]
@krancour actually, the Plan ID is unique only within a service, not globally unique: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-2
> 

plan_id* | string | The ID of the plan (from the catalog) for which the service instance has been requested. MUST be unique within the service. MUST be a non-empty string.

**Comment by nilebox** [comment]
But in the plan definition its ID is required to be globally unique... https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#plan-object

I guess we need to update the doc to choose one.

**Comment by nilebox** [comment]
Raised https://github.com/openservicebrokerapi/servicebroker/issues/306

**Comment by krancour** [comment]
@nilebox adding another datapoint to this... plan ids (like service ids) tend to be uuids, and that _implies_ global uniqueness. (This is assuming no one willfully reuses a uuid.)

**Comment by mattmcneeney** [comment]
I've added this to the [Ideas for v3](https://github.com/openservicebrokerapi/servicebroker/wiki/Ideas-for-v3) wiki page. Closing here.
