### ISSUE TITLE
instance & binding IDs being UUID is problematic

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#285]
In the latest version of the spec we now require the instance and binding IDs to be UUIDs and this is problematic for us.  We have certain service brokers that require extra information from the platform on each call because they either can't, or don't want, to store it themselves. This means their only option is to call back into the platform each time to retrieve this extra information.  As a result of this we encode this extra info into the instance and binding IDs and are using CRN's to do it.

We thought about using the new 'context' object but that's not sent on a DELETE - so that won't work.

We'd like to revert this change and let it just be a unique non-empty string of the platform's choosing.

I'll add this to the agenda for Monday's call so we can discuss it.

cc: @phanziii

**Comment by duglin** [comment]
cc @bkmartin

**Comment by angarg12** [comment]
I'm ok with undoing this change, at least for the time being.

Would including the context object in the DELETE operation make sense, and avoid such problems in the future?

**Comment by duglin** [comment]
We did discuss that during a previous F2F but including a Body on a DELETE wasn't really an option because while the HTTP spec allows it, the consensus was that there are too many http servers that would just not work with it.

**Comment by fmui** [comment]
If we return to a non-empty string, we should exclude a few characters, though. For example, a slash can be problematic in a URL, even it is encoded.

**Comment by mattmcneeney** [comment]
There is a discussion in another thread about having a pre-defined set of characters for things like this (`[A-Za-z0-9\-\+]` or something). I'd be up for doing a sweeping change removing any requirements for IDs etc causing issues and defining a standard set of allowed characters and lengths.

**Comment by fmui** [comment]
If data is encoded in these IDs, we should support URL-safe Base64 here. That is, we should add `_` and maybe also `.` to the list of allowed characters.

**Comment by duglin** [comment]
I get nervous about trying to restrict the character set in situations like this because 1) it often leads to implementation choices influencing the spec, and 2) we just don't know what people will want/need to do with these strings.  Just a few examples of "resource names" that I found with a quick google search:

http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html
https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/resource-names.html

In IBM's case one naming pattern we follow is:
`crn:version:cname:ctype:service-name:region:scope:service-instance:resource-type:resource`

IMO, a spec needs to be pretty permissive on stuff like this because often these things will include IDs that are for backend systems that are out of the control of the the layer that implements the spec.

My preferred approach is to follow the URL spec itself ( https://www.ietf.org/rfc/rfc1738.txt ) and just tell people that if they want to use questionable characters then they'll need to URL-escape them.

However, any talk about restricting the characters right now would probably be a breaking change and would need to wait for v3. In the meantime, for v2.x I think the best we can do is add text about URL-escaping characters (along with removing the UUID requirements we added).

**Comment by duglin** [comment]
Based on today's call there was no objection with heading the direction of reverting the UUID requirement.  There will probably be a secondary issue opened to deal with the question of whether or not we want to restrict the valid chars of these IDs in general though.
