### ISSUE TITLE
How and where can the end user find out the provisioning params 

### ISSUE THREAD

**Issue by JarreyZhou** [openservicebrokerapi/servicebroker#292]
I have not found any definition of the provisioning params and binding params in the service, how can the end user know what params should be provided when provisioning an instance?

**Comment by pmorie** [comment]
@JarreyZhou there is a new feature which we are about to add into the spec which allows the broker to send a parameter schema for creating and uodating service instances and creating bindings. See:

https://github.com/openservicebrokerapi/servicebroker/pull/165

Let me know if that's what you're looking for.

**Comment by JarreyZhou** [comment]
@pmorie thanks very mary, it is just what I am looking for.
