### ISSUE TITLE
Open Service Broker to track service instances and bindings it grants

### ISSUE THREAD

**Issue by Haishi2016** [openservicebrokerapi/servicebroker#294]
It seems to me OSB API should be extended to offer lifetime management of service instances and bindings. Currently, these capabilities are implemented in corresponding service catalogs in different platforms. It could be a good idea to centralize these common capabilities into the API itself.

**Comment by Haishi2016** [comment]
There seems to be a "as stateless as possible" desire in the spec. I get the benefits of such desire, but I think it's harming the API design. For example, unbinding requests mandates service id and plan id to be passed along with the binding id. I see this as a side-effect of "as stateless as possible" instead of a logical/intuitive design. I'm okay with the parameters passed in as hints, but they should not be specified as mandatory.

**Comment by duglin** [comment]
@Haishi2016 can you elaborate on what you mean by the spec should offer "lifetime management"? Do you mean like people should be able to specify a TTL for resources?

**Comment by Haishi2016** [comment]
Hi @duglin. I was not talking about TTL. What I meant was a Service Broker should remember service instances and bindings it grants to clients. Now I see the spec requires the platform marketplace (or catalog service) holds the truth for service instance and bindings. I think I'm okay with that. 

I'll close the issue. Thank you for your reply.
