### ISSUE TITLE
Potential V3 changes

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#298]
This issue contains a list of potential work items and spec changes that people would like to consider for v3. This is just a random list of items w/o any guarantee of any of them being added to any future version of the spec. This saves us from having to have a long list of open issues that won't be touched for a long time.

**Comment by duglin** [comment]
Should we consider adding text to the spec to restrict the valid chars used in IDs. Since IDs will sometimes appear in URLs, and while they can always be URL encoded, this could be problematic for some systems and might be easier if we just restricted it so that we don't allow for URL-problematic chars like slashes and question marks.

**Comment by angarg12** [comment]
Since v3 will be a backwards incompatible version, we want to reasonably pack as many breaking changes as we can together.

I created a v3 Github tag that we can apply to current open issues so that we don't lose track of them. If you agree with can proceed with it, or maybe create a new v3 Github milestone.

**Comment by duglin** [comment]
There was some concern about having a ton of issues that we won't touch for a long time so I was thinking we could close all of the v3 issues and just add pointers to them in this issue.  But if people are ok with individual v3 issues that linger, then we can close this one. I'm fine with either way - we just need to decide. I'll add it to the agenda for today's call.

**Comment by duglin** [comment]
we agreed to open up separate issues for each one and then just tag them with "v3"
