### ISSUE TITLE
Allow service instances to be shared across spaces/namespaces

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/servicebroker#302]
_Note: In this issue, I will use the term **space** to refer to both CloudFoundry **spaces** and Kubernetes **namespaces**._

## The Problem
On most platforms, developers are responsible for managing service instances that are typically provided to them via a marketplace that is built using service brokers that have been registered on the platform. Developers can provision these services in a space they have access to and consume them from applications running in that space. However, there are many use cases where applications in different spaces want to consume the same service, i.e. config servers, messaging queues and backing databases. This is not possible today without generating bindings to obtain credentials, and then sharing these in an out-of-band way.

## Proposed Solution
To solve the use cases above, it would be great if service instances could be shared across spaces. In CF, this could look like `cf share-service SERVICE_INSTANCE ORG SPACE`. This is predominantly a platform issue and wouldn't require a change to the spec. However, our research has shown that some service brokers would not be able to support this workflow. An example of this is an autoscaling service that calls back into the platform to do something to an application that resides in the same space as the service instance. The autoscaling service would need to know _where_ the binding came from ( #289 ) and would need to have logic to use that information.

To prevent introducing a change to the platform that could break some existing service brokers, it would be better if we allowed service brokers to opt in to this feature.

A new field could be added to the [Service Object](https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#service-objects) that would declare support for specific workflows like this, for example:
```
{
  "services": [{
    "name": "fake-service",
    "id": "acb56d7c-XXXX-XXXX-XXXX-feb140a59a66",
    "description": "fake service",
    "supports": [ "sharing" ]
}
```

---

Any feedback on this would be appreciated. We are working on adding this functionality to Cloud Foundry now, and when this was raised on last nights call, folks from Kubernetes suggested that this is something they are likely going to look into in the future, and so adding this into the specification would be the best next step.

**Comment by duglin** [comment]
Some questions, and some are CF specific - not spec related:
- when you share an instance are you simply making it visible to the other space or are you creating a new resource (like an "alias") with its own lifecycle?  E.g. if the 2nd space tries to delete what it sees, will it vanish from both spaces or just the 2nd? And if you delete it from the 1st space does it vanish from the 2nd? Can you just remove it from the 1st space's visibility w/o harming the 2nd space?
- does the decision from the first bullet need to be known to the broker and the spec? I don't think so.
- if the sharing of an instance across spaces is strictly a platform feature, and the broker/spec, doesn't need to know about it then I'm not sure what the "sharing" flag is indicating that the broker will do. IOW, there are two cases I think we're talking about:
  - service that doesn't need to reach back to the platform. In this case the space really shouldn't matter much at all.  The service could choose to look at the space or not - same as today.
  - service reaches back into the platform. It seems that in this case its really the platform that needs to decide whether this type of service can manage two apps across two different spaces, no? Almost as if the platform should be the one providing this flag to the broker - but if it didn't support it then it could just block a 2nd binding request from a 2nd space (maybe).

**Comment by mattmcneeney** [comment]
- You're simply making it visible to the other space. Developers in the other space can only bind and unbind to the instance. If you unshare or delete it from the original space, it disappears from the shared space (but client facing tools should warn developers that this could break applications using that service instance)
- This is platform-specific, so I'd say this isn't related to the spec. The platform will control what endpoints developers in the shared space can hit.
- This is the crux of whether we need to add something to the spec. There are brokers today that _will_ break if we released this in CF, and we want to avoid that happening. It is hard for platforms to know if brokers will reach back into the platform, or even if they don't _want_ to support sharing for some other reason. This decision (and the broker's capabilities) are known to the broker, hence I believe an "opt in" via a flag in the spec would be nice. The difference of this flag versus the other flags we have in the spec right now is the other flags specify if endpoints are supported (i.e. `bindable`), whereas we want to allow a broker to declare to the platform whether it is happy to accept bindings from different spaces/namespaces.

Let me know if that doesn't make sense. Part of me thinks it seems odd that the broker needs to declare support for something that is so platform related, but I can't think of a better approach.

**Comment by duglin** [comment]
Can you elaborate on how brokers might fail, and why, if they're given two different spaces on two different bindings for the same instance? I'm not questioning that they might - just trying to understand why they do so.

**Comment by mattmcneeney** [comment]
Of course. I had initially hoped that all brokers would _just work_ with this change, but feedback on [this cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/JHQXYGC4ZCZWAJDAVWW4E3GAXKLBDGQA/) has shown otherwise.

One of the use cases raised in that mailing list is a service broker that, upon receiving a binding, calls back into the Cloud Controller to modify the Application Security Group rules (firewall rules) for that space. Today, as per the spec, service brokers don't know where a binding request came from. If we turned on instance sharing today and that broker was registered to a platform, a binding from another space would trigger the broker to modify the firewall of the space the instance was created in, rather than the space the binding came from.

One solution would be for the broker to be updated after #289 is merged to use the context object in a binding request, but that would still require the broker to be updated in all platforms it is registered in. Otherwise, if the platform is updated and sharing is enabled, the broker wouldn't work.

I think there are other examples of this behaviour with auto-scaling services (that call back into the platform to scale applications in a space). This service would also break if sharing were enabled and the broker hadn't been updated accordingly.

Does that make any more sense?

**Comment by pmorie** [comment]
I am not sure that this has meaning to anything besides cloud foundry yet.
We do not yet have either namespaced brokers/services in k8s or the ability
to share any resource across a namespace in this manner. :-/

**Comment by mattmcneeney** [comment]
OK. Is this something you think will be interesting in the future?

**Comment by mattmcneeney** [comment]
Closing this!
