### ISSUE TITLE
Restrict the valid chars for properties that can appear in URLs

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#303]
Should we consider adding text to the spec to restrict the valid chars used in IDs. Since IDs will sometimes appear in URLs, and while they can always be URL encoded, this could be problematic for some systems and might be easier if we just restricted it so that we don't allow for URL-problematic chars like slashes and question marks.

For reference see:
https://github.com/openservicebrokerapi/servicebroker/issues/273
https://github.com/openservicebrokerapi/servicebroker/pull/299

**Comment by mattmcneeney** [comment]
I'm supportive of this and would welcome a PR that starts to address this (especially if we can do it in a non-breaking way!).

**Comment by mattmcneeney** [comment]
Added this to the [Ideas for v3](https://github.com/openservicebrokerapi/servicebroker/wiki/Ideas-for-v3) wiki page. Closing here.
