### ISSUE TITLE
Get metadata on service parameters

### ISSUE THREAD

**Issue by Haishi2016** [openservicebrokerapi/servicebroker#304]
I'm authoring a service catalog as well as a client-side tooling experience for Azure Service Fabric. I'm facing a problem of not knowing what the expected parameters are for a particular service type. For my client-side tools, I want to be able to guide the user to provide correct/necessary parameters when they try to provision a new service instance. However, because the broker is not authored by me, the only way I can find out the parameters is to talk to the team or look at their source code. And I'm afraid if they decided to change parameters my client-side tool will break.

I think there should be a metadata endpoint or alike that allows query parameters of a service class. What are your thoughts on this?

**Comment by mattmcneeney** [comment]
Hi @Haishi2016 

Check out this open PR that we expect to be merged soon: #165 

Using JSON schemas, service brokers will be able to declare the configuration parameters that can be used for provisioning/updating a service instance and creating a service binding.

I'll close this issue for now, but please feel free to re-open it if that PR doesn't resolve your query. Thanks!
