### ISSUE TITLE
service/plan names can be "-"

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#305]
we should probably add something about how "-" isn't a good choice for a name :-)

**Comment by nilebox** [comment]
While for service this concern is valid, for the plans it most probably just means that the service has one and only "default" plan.

If we want a better UX for such services, we can probably make plan list optional?

**Comment by angarg12** [comment]
As mentioned in #154, would it make sense to eventually include a regex of valid names and ID's? 

Regexes can be ugly, but I think we have spent way too much time already discussing which character/formats should be allowed.

**Comment by duglin** [comment]
Unfortunately I don't think we can ban it via a MUST NOT, but I think some guidance text against it would be good. I'll work on it.

**Comment by angarg12** [comment]
For v3 do we want a backwards-incompatible change that forbids these kind of names?

**Comment by duglin** [comment]
Maybe a little bit yes - e.g. restrict it to [a-z0-9][-a-z0-9]*  wouldn't be overly restrictive.  But we can discuss when we get to v3.
