### ISSUE TITLE
Plan ID - globally unique or unique within the service?

### ISSUE THREAD

**Issue by nilebox** [openservicebrokerapi/servicebroker#306]
There is a discrepancy in the requirements for Plan ID:
1. in the plan object doc:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#plan-object
> id* | string | An identifier used to correlate this plan in future requests to the broker. This MUST be globally unique. MUST be a non-empty string. Using a GUID is RECOMMENDED.

2. In the provisioning request doc:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-2
> plan_id* | string | The ID of the plan (from the catalog) for which the service instance has been requested. MUST be unique within the service. MUST be a non-empty string.

**Comment by angarg12** [comment]
Nice catch. I vote for unique within the service. Since service id's are globally unique and required on each request, this would make it simpler and unambiguous.

**Comment by nilebox** [comment]
@angarg12 agreed. Also, it is probably redundant to describe the format of the plan id in the provisioning request, since it is already described in the catalog endpoint where broker returns a list of plans.

**Comment by mattmcneeney** [comment]
In CF we require plan IDs to be _globally_ unique. Changing this to unique within a service would cause issues with our API. But obviously I agree the discrepancy needs fixing, and I'd vote for globally unique.

**Comment by duglin** [comment]
I think that's a bug. While it may feel a bit inconsistent to have the name be scoped to the service while the ID is globally unique, I think it makes a lot more sense from a UX and coding perspective.

I'll open a PR to fix it.

**Comment by nilebox** [comment]
> I'll open a PR to fix it.

@duglin are you still planning on opening a PR? :)

**Comment by duglin** [comment]
yea, its on my todo list - I'll try to get to it later today

**Comment by duglin** [comment]
just looked at this and I think its been fixed already. The uniqueness text in the provision section have been removed, thus removing the inconsistency.

It still says it must be globally unique during the retrieval of the catalog, which is what we agreed to, and really the only spot it needs to be talked about since that's where the ID is generated. The provision just uses it and can't control its uniqueness at that point.

**Comment by duglin** [comment]
Going to close this.  We can reopen if needed.
