### ISSUE TITLE
add CF community standards stuff to our spec

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#316]
I thought we already had an issue but I can't seem to find it....

we should consider adding:
https://docs.cloudfoundry.org/services/binding-credentials.html
and
https://docs.cloudfoundry.org/services/catalog-metadata.html
to our spec or profile.

**Comment by angarg12** [comment]
Related to #152.

Should we close that one and focus the conversation here?

My vote on the topic would be to move the metadata to a new file and reference it from the spec, or even copy it directly to the wiki.

**Comment by mattmcneeney** [comment]
@duglin Catalog metadata is already in [profile.md](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md) I believe.

The binding credentials information isn't - do you want to raise a PR to pull that into the profile file too?

**Comment by mattmcneeney** [comment]
Closing as I think this is done?
