### ISSUE TITLE
are extensions allowed in the dashboard client object

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#317]
https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#dashboard-client-object  doesn't say if extension json properties are allowed or not.  Seems like it would be nice to allow them. Might be true for other objects as well.

**Comment by angarg12** [comment]
Actually that's a good point, and it applies to other objects as well.

We may want to explicitly specify for each object which ones allow or not extensions, how does that sound?

**Comment by duglin** [comment]
perhaps use a well-defined property/grouping, or ask for a prefix to be used.
Look for other spots where we may need this.
See if we can make a general statement for the entire spec.

**Comment by mattmcneeney** [comment]
These extensions are now being tracked in profile.md (see catalog extensions). Closing.
