### ISSUE TITLE
Allow parameters for deprovisioning an instance

### ISSUE THREAD

**Issue by jakkahub** [openservicebrokerapi/servicebroker#319]
If deprovisioning an instance required some input parameters or a payload, there is no option. Some service instances may need some parameters for delete, similar to provisioning. Our cloud services need a payload to delete and we are looking for this option.

**Comment by pmorie** [comment]
I'd really like to know more about this use-case.  This is likely not easy to implement on some platforms.

**Comment by jakkahub** [comment]
We have a service manager that can provision/deprovision services on our cloud platform. We are extending our service manager operations to CloudFoundry with an Open Service broker. Cloud Foundry user can provision/deprovision our services through Open Service Broker API. 

Deprovision a service on our cloud platform needs a payload that contains some service specific parameters.

When a CF user delete our service instance from CloudFoundry, CF calls our OSB api 
`DELETE /v2/service_instances/:instance_id`
However, CF user cannot pass a payload or some parameters to it.

We are looking for something like this:

`cf delete-service SERVICE_INSTANCE [-c PARAMETERS_AS_JSON]`

```
$ curl 'http://username:password@broker-url/v2/service_instances/:instance_id?accepts_incomplete=true
  &service_id=service-id-here&plan_id=plan-id-here -d '{
  "parameters": {
    "parameter1": 1,
    "parameter2": "foo"
  }
}' -X DELETE -H "X-Broker-API-Version: 2.12" -H "Content-Type: application/json"
```

**Comment by duglin** [comment]
are those parameters specific to your platform, the org/space, or the service instance?

**Comment by jakkahub** [comment]
Yes, those parameters are specific to our service instance.

Example:
```
"parameters": {
  "dbaName": "string",
  "dbaPassword": "string",
  "forceDelete": true,
  "skipBackupOnTerminate": true
}
```
We are trying to find way for CF user to send them to open service broker from CloudFoundry client.

**Comment by duglin** [comment]
I have my doubts that we'll be able to do this because some HTTP servers can't deal with DELETEs having bodies very well, which is why we put the Context header as a header instead of into the Body.  Any reason why you can't put them as extra URL query parameters?  For a DELETE that's really the only (best) spot to put "extra stuff".

**Comment by jakkahub** [comment]
How can I pass extra URL query parameters to broker endpoints? CF is calling the broker endpoints here.

**Comment by duglin** [comment]
That's a CF question, not a spec question. You'd have to see if the CF folks would be willing to extend the CLI to allow for extra info to be passed in that would then be placed as query parameters on the delete.

**Comment by pmorie** [comment]
I am not at all sure we have a good way to do this in k8s either.

**Comment by mattmcneeney** [comment]
I have followed up with @jakkahub on the [cf-release](https://github.com/cloudfoundry/cf-release/issues/1246) issue. Closing this one.

**Comment by Kiemes** [comment]
@mattmcneeney Do you still remember what the solution to this problem was? The linked issue is not visible anymore. We would have the same question or similar use case. Is it ok to add more request parameters to the delete request? Or would that not be compliant with the OSBAPI spec? Adding should still be compatible, right?

**Comment by mattmcneeney** [comment]
@Kiemes I can't quite remember to be honest. I believe the recommended option was to add additional information using headers but that would fall outside the scope of the specification. cc @Samze in case you remember anything on this one!
