### ISSUE TITLE
Spec major versions support and lifecycle?

### ISSUE THREAD

**Issue by angarg12** [openservicebrokerapi/servicebroker#320]
I was thinking today about the future v3 of the spec, and then it came to my mind that, as far as I know, we haven't defined or discussed a lifecycle plan for major versions.

If we make a version 3 release, what will happen to the latest release of version 2? Will we backport new features and fixes to version 2? For how long will we support it?

@avade maybe the experience from Cloud Foundry moving from v1 to v2 could help here?

**Comment by duglin** [comment]
I've been assuming that once we create a v3 we'd stop all work on v2, except perhaps "hot fixes" for critical things, but mainly full stop.

**Comment by angarg12** [comment]
My line of thought was that brokers may wish to support both major versions for a short while to give their clients time to migrate to the new one.

In any case it could be a good idea to explicitly write down our policy, something along the lines "when a new major version is released, development of the previous version will cease. Previous versions will receive fixes for 6 months after the release of a new major version.".

**Comment by angarg12** [comment]
Acknowledged! I will look into this and write a proposal.
