### ISSUE TITLE
Add support for custom header parameters for broker endpoints

### ISSUE THREAD

**Issue by jakkahub** [openservicebrokerapi/servicebroker#321]
We have a service manager that can provision/deprovision services on our cloud platform. We are extending our service manager operations to CloudFoundry with an Open Service broker. 

When our service broker is registered with CF platform to make our services and plans available to end users, CF calls our broker endpoint
`GET /v2/catalog`

Our service broker running on our service manager expects an header parameter for authentication along with basic auth parameter. Without the extra header parameter, our endpoints are not accessible and return 401.

We are looking for a solution on how to pass custom header parameters to broker endpoints during registration, so that platform sends it to every endpoint in subsequent requests to broker.

`PUT /v2/service_instances/:instance_id`
`PUT /v2/service_instances/:instance_id/service_bindings/:binding_id`

**Comment by mattmcneeney** [comment]
Followed up on cf-release - closing here.
