### ISSUE TITLE
No read operation defined

### ISSUE THREAD

**Issue by henrytk** [openservicebrokerapi/servicebroker#331]
## Example scenario

* A user provisions a service instance.
* The user then updates the instance. The change is one that **does not** involve changing the plan. The OSB API allows for arbritrary update parameters, and so supports making changes which are not a change in plan.
* The user wants to make a further change to the service instance but needs to assert the instance's current state first. This information is not available via the OSB API.

## The problem

The Open Service Broker API does not provide a way of reading the state of an existing service instance.

## Suggested solution

Provide an endpoint for reading the state of a service instance. It returns arbitrary data about the instance.

**Comment by duglin** [comment]
Weird - I could have sworn we opened an issue to add optional GET endpoints, but I can't seem to find it.

**Comment by mattmcneeney** [comment]
This is being covered by #159 

Closing this issue - please reopen if you believe this is in error :)
