### ISSUE TITLE
Investigate relaxing 4XX error codes

### ISSUE THREAD

**Issue by vaikas** [openservicebrokerapi/servicebroker#338]
There are some cases where a broker is being implemented on a frameworks that handle authnz. In those systems, for example 401 / 403 are distinct error codes. Currently the spec:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#authentication

specifies that the request must be failed with 401 if authnz fails. As mentioned some platforms distinguish between 401 / 403. Could we relax the MUST return a 401?

"If authentication is used, the service broker MUST authenticate the request using the predetermined authentication mechanism and MUST return a 401 Unauthorized response if the authentication fails."

**Comment by vaikas-google** [comment]
Put together a PR to allow for 403 to return. @mattmcneeney to check with Cloud Controller to make sure there's no blockers from their side.

**Comment by mattmcneeney** [comment]
@vaikas-google Do you remember what happened to this PR!?

**Comment by vaikas** [comment]
lol, no idea :(

**Comment by mattmcneeney** [comment]
Fair enough, it was a _long_ time ago! Going to close this for now. Please reopen if anyone is getting blocked on this!
