### ISSUE TITLE
Clarify what should happen to bindings when a plan is updated.

### ISSUE THREAD

**Issue by vaikas** [openservicebrokerapi/servicebroker#340]
If a Service Instance is created, followed by a Binding with plan XYZ. Then a Service Instance is updated to plan ZYX, what should happen to bindings, since part of the body for creating them has a PlanID that's now invalid. Should we clarify that plan is updateable only if it does not invalidate / modify bindings. Or ??

**Comment by n3wscott** [comment]
I question why plan_id is in the binding request.

**Comment by vaikas-google** [comment]
I think it was used for routing requests. But regardless of it, semantics of plan update and what happens to bindings should be clarified. If for example the pricing of a plan changes, this could cause existing bindings to see an increase in their costs.

**Comment by vaikas-google** [comment]
The spec is definitely bit loose in that case, will look at tightening it up.
Investigate making plan_id deprecated.

**Comment by avade** [comment]
I am going to mail CF Dev to see if anyone has a broker that uses plan_id to influence the binding.

@shalako do you have any history?

**Comment by n3wscott** [comment]
Any update on this? I'm really interested in the finer nuances of plan_updatable now that we get into this. Some questions that come to mind are:

1) Does updating an instance's plan also cause its bindings to be updated? Seems like that might be the case in some situations
2) If so, does this require all bindings in a plan_updatable service to have the same parameter schema?
3) If not, how do bindings to an instance get updated when its plan is updated?

**Comment by duglin** [comment]
From 11/17 call, @vaikas-google will write-up a proposal for this.

**Comment by avade** [comment]
CF Dev mail sent: https://lists.cloudfoundry.org/g/cf-dev/message/7702

**Comment by duglin** [comment]
We need clarity on whether plan/param/etc... updates to an instance impact existing bindings at all. And it if not, then can we say it MUST NOT in the spec?

(from a slack chat)
