### ISSUE TITLE
There should be a health check end point for services that are provisioned

### ISSUE THREAD

**Issue by ncameronbritt** [openservicebrokerapi/servicebroker#344]
As a user I would want to know that a service I provisioned, which exists outside of my namespace, has a problem.

**Comment by mattmcneeney** [comment]
Hi @ncameronbritt 

#333 is dealing with adding GET endpoints to fetch service instances and service bindings. The response for these endpoints could be extended in the future to include health information.

The key here is that, if we want this information to be useful across all platforms, we would have to define in the spec what this health information would look like. This will require some research into both what informations platforms would want to show in their interfaces, and what information service brokers would want to return (and have access to) from their underlying service instances and bindings.

**Comment by ncameronbritt** [comment]
Sounds reasonable, @mattmcneeney.

**Comment by duglin** [comment]
We should consider health-check APIs for both brokers and service instances.

**Comment by mattmcneeney** [comment]
@duglin This is high up on my list of challenges I'd like us to face. I've added it to the F2F agenda!

**Comment by mattmcneeney** [comment]
This is being tracked elsewhere (#431) so closing this issue.
