### ISSUE TITLE
Clarify the expectations of a platform when a resource fails to get created

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#348]
When a resource fails to get created, say Service Instance is being asked to be provisioned, and after polling the Broker, broker returns a failure. The spec does not seem to be clear on what the expectation is on the platform side for the expected state of the resource being created. This has led to following issue:
https://github.com/kubernetes-incubator/service-catalog/issues/1461

Spec should clarify what happens here.

**Comment by avade** [comment]
@mattmcneeney to report on CF behaviours when provision fails for snyc & async.

**Comment by mattmcneeney** [comment]
Current CF behaviours are as follows:
* If a synchronous provision fails with a 5XX status code, then a deprovision request is automatically sent to brokers.
* If an asynchronous provision fails _immediately_ with a 5XX status code (i.e. the provision call fails), then a deprovision request is automatically sent to brokers
* If an asynchronous request fails _sometime later_ with a 5XX status code (i.e. last operation returns `"status": "fails"`), then no deprovision request is sent to brokers.

**Comment by duglin** [comment]
@mattmcneeney in the last case I think it might also return a 200 on the last_operation call, but have "failed" for "status".  Do you still NOT send a deprovision in that case?

**Comment by mattmcneeney** [comment]
I don’t think last operation is called in the last case but I can double
check.

**Comment by duglin** [comment]
Returning a 5xx on last_operation, to me, would indicate that the last_operation operation itself failed, not the provision - and the spec says it should keep polling.

**Comment by pmorie** [comment]
> If an asynchronous request fails sometime later with a 5XX status code (i.e. last operation returns "status": "fails"), then no deprovision request is sent to brokers.

However, when the user says that the service should be deprovisioned, CF does send the deprovision request, right?

**Comment by mattmcneeney** [comment]
Yes it does @pmorie (for the record on this issue)

**Comment by avade** [comment]
The action is with @duglin to use his supreme spec writing skills to propose a clarification based on the current CF behaviours.

**Comment by mattmcneeney** [comment]
Closing this as it is being done in #354
