### ISSUE TITLE
Clarify status of an Instance when Updating fails

### ISSUE THREAD

**Issue by staebler** [openservicebrokerapi/servicebroker#358]
It is not specified in the spec what the status of an Instance is when an update of the Instance fails. Must the instance be left in a usable state? Must the instance be left in the same state in the broker that it was in prior to the request being made, as if the request had not been made at all? Or does an update failure leave the Instance in a failed state where the only valid future operation is a deprovision?

**Comment by duglin** [comment]
I'd vote for the resource to return to its previous state - anything else means random behavior and we'd be forced to delete the resource. That would be bad from a UX perspective.

**Comment by mattmcneeney** [comment]
Agreed. @duglin can you add text for this under #354 ?

**Comment by pmorie** [comment]
I'd be very curious to know what happens in CF in this case.

**Comment by mattmcneeney** [comment]
@pmorie It's up to the broker whether it 'resets' to how it was before the update. In CF we tell app devs the update failed but, since there is no way of 'getting' a service instance right now, that's the only information we have to offer.

**Comment by staebler** [comment]
Requiring the broker to retain the previous state seems to me to be inconsistent with what we require of the broker for failed provisions and binds. In the provision/bind cases, we allow the broker to leave whatever state around that it wants and force the platform to send a deprovision or bind request to clean everything up. In the update case, we would require that the broker make no changes (or clean up itself whatever changes were made). If the broker were capable of doing that, then why wouldn't we require that for provision and bind?

**Comment by duglin** [comment]
@staebler overall I agree that the provision/bind should clean-up after itself upon failure but we can't get agreement on that yet. :-(

However, the update case is different to me. In the provision/bind cases you are asking for something new and so the user can't be doing work on/with a yet-to-be-created resource. In the updating an instance case we already have a resource that people are probably interacting with, and so allowing it to be in an unusable state probably means bad things will occur as they continue to use it. E.g. lost data.

But we should discuss this on the call before I add text to #354 or to a new PR.

**Comment by pmorie** [comment]
Some notes from the November 28 F2F:

In CF:

- When updating fails CF shows that the last operation on the instance failed
- The instance is reset to the old state before the update
- The user is still able to deprovision the instance after this happens

**Comment by pmorie** [comment]
Also - when a plan change isn't supported the broker should return 422.  Eventually we might have an error code for the broker to indicate the exact nature of the failure.

**Comment by edbartsch** [comment]
As OSB API allows changing of service instance parameters for update call, it can happen that some parameters are applied and some not. Same can happen in case of a composite change where a new service plan and new parameters are supplied simultaneously. It may be impossible or very hard for the broker to roll back all changes. The instance may still be usable but the metadata (plan and parameters) will be inconsistent between service broker and CF Cloud Controller or Service Manager. 

What if along with signalling "instance_corrupt", a service broker may also signal "metadata_resync_needed" in case the instance is still usable? When getting this flag back on failed update, the CF Cloud Controller or Service Manager would have to retrieve the actual active set of parameters from the service broker. Same can be done for the service plan.

If we follow up the above path, it may be also interesting to allow service brokers to signal altered parameters after succeful create/update operations.

**Comment by mattmcneeney** [comment]
This will be solved by #566 so closing here.
