### ISSUE TITLE
Feature Request: Diagram

### ISSUE THREAD

**Issue by cholick** [openservicebrokerapi/servicebroker#361]
Old documentation for the spec used to include an overview of the API calls (happy path) in a sequence diagram:
https://docs.pivotal.io/pivotalcf/1-8/services/api.html#api-overview

The short sequence diagram with an instance and binding's lifecycle was a really clear way to get a handle on what was going on quickly.

Could the spec repo include a similar/updated diagram?

**Comment by duglin** [comment]
I'm sure we could probably abstract it so its not CF specific - sounds like a good idea. Anything to help clarify things for people....

**Comment by mattmcneeney** [comment]
We have a diagram now, so closing this issue.
