### ISSUE TITLE
The term "orphan" has become ambiguous

### ISSUE THREAD

**Issue by kibbles-n-bytes** [openservicebrokerapi/servicebroker#369]
With the addition of the text about platforms sending a deprovision request for every resource that has attempted to be provisioned, the term "orphan" has become quite muddied. The orphan mitigation section of the spec specifically highlights the situation where the platform is unsure whether a resource has been successfully created or not. In this context, an "orphan" is specifically an instance that has been provisioned *successfully*, but the platform doesn't know about it or has given up on it. However, with the latest changes, we have started using the term "orphan" to also encapsulate situations where both the broker and the platform have agreed that the resource has failed but there may be broken resources left over on the broker side.

I believe we should take a hard stance here, clarifying that an "orphan" only refers to successfully provisioned resources that the platform doesn't know about. This way, it's clear that these are two separate situations, with potentially slightly different semantics.

**Comment by duglin** [comment]
I'm not sure I'm seeing much of a difference between the two cases as they all seem to fall under the general category of "we're not sure what state the broker's resource is in".  Perhaps "cleanup" is better than "orphan" but regardless of the term we use, I think the semantics of what's expected is the same - in both cases we want to delete the resource, no?

**Comment by mattmcneeney** [comment]
I think we have cleaned this up a bit, but please reopen if the terminology is still confusing.
