### ISSUE TITLE
Feature Request: Diagrams-as-code using MermaidJS

### ISSUE THREAD

**Issue by JJediny** [openservicebrokerapi/servicebroker#374]
Re: https://github.com/openservicebrokerapi/servicebroker/blob/master/diagram.md

Use Mermaid JS to generate API diagrams

https://mermaidjs.github.io/sequenceDiagram.html

## Example - Provisioning a service instance
![image](https://user-images.githubusercontent.com/6350035/33343975-3b69467a-d455-11e7-92fa-90382070bb08.png)

```
%% Sequence Diagram for Provisioning a Service Instance
sequenceDiagram
  participant Platform
  participant API  
  participant Service Broker

note over Platform: Provision service instance (synchronously)

Platform ->>+ Service Broker: PUT /v2/service_instances/:id

Service Broker -->> Platform:{ “dashboard_url”: ... }

note over Platform: Provision service instance (asynchronously)

Platform ->>+ Service Broker: PUT /v2/service_instances/:id?accepts_incomplete=true
Service Broker -->> Platform:{ “operation”: ... } 

loop Polling last operation

Platform ->>+ Service Broker: GET /v2/service_instances/:instance_id/last_operation
Service Broker ->>+ Service Broker:{ “state”: “in progress” }
Service Broker -->> Platform:{ “state”: “succeeded” }

end
```
----
https://mermaidjs.github.io/mermaid-live-editor/#/edit/JSUgU2VxdWVuY2UgRGlhZ3JhbSBmb3IgUHJvdmlzaW9uaW5nIGEgc2VydmljZSBpbnN0YW5jZQpzZXF1ZW5jZURpYWdyYW0KICBwYXJ0aWNpcGFudCBQbGF0Zm9ybQogIHBhcnRpY2lwYW50IEFQSSAgCiAgcGFydGljaXBhbnQgU2VydmljZSBCcm9rZXIKCm5vdGUgb3ZlciBQbGF0Zm9ybTogUHJvdmlzaW9uIHNlcnZpY2UgaW5zdGFuY2UgKHN5bmNocm9ub3VzbHkpCgpQbGF0Zm9ybSAtPj4rIFNlcnZpY2UgQnJva2VyOiBQVVQgL3YyL3NlcnZpY2VfaW5zdGFuY2VzLzppZAoKU2VydmljZSBCcm9rZXIgLS0-PiBQbGF0Zm9ybTp7IOKAnGRhc2hib2FyZF91cmzigJ06IC4uLiB9CgoKbm90ZSBvdmVyIFBsYXRmb3JtOiBQcm92aXNpb24gc2VydmljZSBpbnN0YW5jZSAoYXN5bmNocm9ub3VzbHkpCgogUGxhdGZvcm0gLT4-KyBTZXJ2aWNlIEJyb2tlcjogUFVUIC92Mi9zZXJ2aWNlX2luc3RhbmNlcy86aWQ_YWNjZXB0c19pbmNvbXBsZXRlPXRydWUKU2VydmljZSBCcm9rZXIgLS0-PiBQbGF0Zm9ybTp7IOKAnG9wZXJhdGlvbuKAnTogLi4uIH0gCgpsb29wIFBvbGxpbmcgbGFzdCBvcGVyYXRpb24KClBsYXRmb3JtIC0-PisgU2VydmljZSBCcm9rZXI6IEdFVCAvdjIvc2VydmljZV9pbnN0YW5jZXMvOmluc3RhbmNlX2lkL2xhc3Rfb3BlcmF0aW9uClNlcnZpY2UgQnJva2VyIC0-PisgU2VydmljZSBCcm9rZXI6eyDigJxzdGF0ZeKAnTog4oCcaW4gcHJvZ3Jlc3PigJ0gfQpTZXJ2aWNlIEJyb2tlciAtLT4-IFBsYXRmb3JtOnsg4oCcc3RhdGXigJ06IOKAnHN1Y2NlZWRlZOKAnSB9CmVuZAoKCgo

**Comment by JJediny** [comment]
If acceptable I'd love to make a PR just didn't want to do so if there wasn't support for the idea

**Comment by mattmcneeney** [comment]
@JJediny I think this is excellent and I would very much welcome a PR for this. The only query I have is what is the best way to automatically render these diagrams somewhere in the spec? Is it possible?

**Comment by JJediny** [comment]
@mattmcneeney could semi-automate the generation of a .png using a makefile and/or a Dockerfile to use https://github.com/mermaidjs/mermaid.cli . But it would require regenerating the .png manually (and for the committer to have nodejs/npm/yarn or docker) for ongoing updates/PRs if only using github markdown natively (and not Jekyll.gh-pages - https://kkpattern.github.io/2015/05/15/Embed-Chart-in-Jekyll.html | https://github.com/jasonbellamy/jekyll-mermaid )

## Example

`make all`
```
register_service.mmd -> register_service.png
provision_service.mmd -> provision_service.png
update_service.mmd -> update_service.png
deprovision_service.mmd -> deprovision_service.png
create_binding.mmd -> create_binding.png
delete_binding.mmd -> delete_binding.png
```

So on second thought this may be more trouble than it might be worth to maintain ¯\_(ツ)_/¯

**Comment by mattmcneeney** [comment]
We could add a travis CI check to check that if a `*.mmd` file is changed, that the associated `.png` file is changed. That would ensure that anyone changing a mermaid file has done the generation. Then we would just have to make sure that contributors could easily regenerate the .png files :)

**Comment by mattmcneeney** [comment]
@duglin is the travis CI master - I presume what I've said above would be relatively easy?

**Comment by duglin** [comment]
yea, I think we could do some kind of check like that.

**Comment by mattmcneeney** [comment]
@JJediny Thanks for putting the PR together! I think that this is something we should push forward with. If you can jump on next Tuesday's weekly call we could discuss this there with the wider group?

**Comment by mattmcneeney** [comment]
We have up to date workflow diagrams in the repo so closing this.
