### ISSUE TITLE
Add error codes to the spec to allow brokers to communicate about specific nature of failures

### ISSUE THREAD

**Issue by pmorie** [openservicebrokerapi/servicebroker#375]
During the November 28 F2F we collectively agreed that the spec should include error codes that a broker could return as part of an error response to provide information about the specific cause of a failure.

Some examples:

- Couldn't create a binding because an earlier update of an instance failed
- Update instance failed because the requested plan change was unsupported

Related to this: perhaps certain error codes could be designated as retryable so that the platform could automatically retry.

**Comment by mattmcneeney** [comment]
This is now resolved and we have a standard set of error codes in the spec.
