### ISSUE TITLE
Let's talk about Generic Broker Actions

### ISSUE THREAD

**Issue by n3wscott** [openservicebrokerapi/servicebroker#376]
More details required. AlI to think about this.

**Comment by duglin** [comment]
I think this is a dup of: https://github.com/openservicebrokerapi/servicebroker/issues/114
@n3wscott reopen if I'm incorrect.

**Comment by rhodie27** [comment]
Doug, this is about actions on a whole service or on the broker, in general. After 114 goes in we'd likely start up this conversation.

**Comment by duglin** [comment]
ok reopened

**Comment by Samze** [comment]
Proposal [doc](https://docs.google.com/document/d/1XjoJt8W_qh53Vm0Wci7oCaO9B410B5g4ULrVJHnqRjs/edit#heading=h.s00kwzxn1rxu) discussed at the F2F

**Comment by mattmcneeney** [comment]
Closing as this is now being discussed elsewhere
