### ISSUE TITLE
Explore options for making it possible to configure network connectivity issues

### ISSUE THREAD

**Issue by vaikas-google** [openservicebrokerapi/servicebroker#386]
Currently there's an assumption that Service Broker created Service Instances and Bindings are able to connect to each other automatically or that required steps are done out of band. This is not always possible and for example when consuming services for example from a k8s cluster running in GCP and a Service Broker that lives for example in AWS would mean that the network connectivity would either have to be wide open for anybody to connect to the created service or that the securing that connection is left for out of band.  

During the discussions at the F2F meeting, it was decided that we should investigate if we can make changes to the Service Bindings Create method which would allow us to achieve enough flexibility to support building the network connectivity. For example, this could contain a certificate which could then be used to create a mTLS tunnel, or create a VPN tunnel between the two clouds.

During Binding Create call, there are three places that this information could be created:
 parameters - this seems like the wrong place because typically this information would be shared between different brokers, and also it would mean that it will be more difficult to have proxies if they need to understand these parameters and hence it couldn't then be transparently introduced and there could be clashing field names in parameters.
 context - this seems like a place to add these fields, since it already contains information like what platform is making the request
 bind_resource - this seems like a place also to add these fields, since it contains information like the consuming application_id.

We should also schematize the returned binding so that in addition to Credentials, the Service Broker could return enough information that the platform could twiddle the additional resources necessary to form the network connection between the consuming application and the created binding endpoint.

We are going to investigate if there are enough commonalities so that we could standardize the fields that are passed back and forth since there are use cases where Istio can not be assumed to be the only solution to this matter.
@fmui @duglin who have also been interested in this topic and have explored / built solutions to address this problem and @fmui is going to start working on an Open Source implementation of some of these ideas.

**Comment by mattmcneeney** [comment]
Schematized binding response is being tracked in #392

**Comment by gberche-orange** [comment]
Related cf-dev@ mailing list thread  [Automating Security Groups and Brokered Services](http://cf-dev.70369.x6.nabble.com/cf-dev-Automating-Security-Groups-and-Brokered-Services-td8456.html) and [CF platform proposal doc](https://docs.google.com/document/d/1Irnjmu4gWrWjqF196xnl6IxZjH6Vif0NT9Mn6QuRjpg/edit#) from @sparameswaran on how CF cloudcontroller could leverage such support in the OSB API.

**Comment by mattmcneeney** [comment]
@vaikas-google is there anything from the work you've been doing you can share on this thread? I know that the schematised responses proposal @n3wscott is working on will help with this, but it'd be good to generate some more information around how platforms and brokers (both side need to configure routing) are going to make use of that proposal

**Comment by carolmorneau** [comment]
> ing list th

+1 
As tile authors, it'd be great to not have to implement ASG management within our service broker and let the platform do the magic.

**Comment by mattmcneeney** [comment]
This is now underway following #632
