### ISSUE TITLE
provide "cloud native" way for backup and recovery

### ISSUE THREAD

**Issue by cforce** [openservicebrokerapi/servicebroker#401]
Feature request.

Should be somehow a feature of API of OSB . 
The OSB story allows us to create instances and share credentials for day 1 operation for a devops database requirements. What is missing is a general purpose API that allows devops to schedule,manually so backups and restore for the binded services (so far the service provider suppport it, thta is an optional api).

For Service and restore the instance provisioning would also require to provision a storage account , preferable an s3 compliant  interface implementation. shall be offered.
I think back and storage is usefull in most domains of services, and even if restore is mor advanced the manually or scheduled backup to an defined instance binding acccount would be a first good step.

Use cases for API
1.  setup storage account for binding (could be simpler by having a logged in acccount all bindings have storage accounts by default)
2. setup schedule time table based with name by convention e.g "<shemaName>_<saveDate>"
3. trigger "save point" "x" manually 
4. restore save point name "x" for binding - could introduce unbinding and binding for all binded consumers because of downtime.

**Comment by mattmcneeney** [comment]
Hi @cforce 
Thank you for detailing your use cases.
We have had this request from many folks in the community and are currently discussing a possible solution in #114. Could you take a look at that and see if you think that will help you?

**Comment by duglin** [comment]
I'm going to assume that this issue is about adding new OSBAPI ops for the Platform to invoke against the broker/instance and NOT about extending the list of ops available to the application that is bound to the instance. And therefore is a dup of #114 and will close.  @cforce if I'm wrong please reopen it.
