### ISSUE TITLE
Route Service Binding phrasing

### ISSUE THREAD

**Issue by Samze** [openservicebrokerapi/servicebroker#410]
The Route Services section of [types of bindings](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#types-of-binding) of the spec specifies that:

`If a Platform supports route services, it MUST send a routable address, or endpoint, for the application along with the request to create a Service Binding using "bind_resource":{"route":"some-address.com"}.`

Taken as state, this implies that if the platform supports route services that it must send a routable address for all service bindings for any service. CF currently only sends the routable address if  `"required": ["route-forwarding"]` in the catalog for the service.

**Comment by mattmcneeney** [comment]
I think the spec. could be clearer here. What about:
```
When a Platform sends a request to create a Service Binding for a Service Instance for which the associated service has`"required": ["route-forwarding"]` in the catalog, it MUST send a routable address, or endpoint, for the application along with the request to create a Service Binding using "bind_resource":{"route":"some-address.com"}.
```

**Comment by mattmcneeney** [comment]
@duglin Need your magic wordsmithing here!

**Comment by duglin** [comment]
hmmm that proposal still implies that when the broker has "route-forwarding" enabled, the platform MUST use it.

How about if we replace:
- - -
There are a class of Service Offerings that intermediate requests to applications, performing functions such as rate limiting or authorization.

If a Platform supports route services, it MUST send a routable address, or endpoint, for the application along with the request to create a Service Binding using "bind_resource":{"route":"some-address.com"}. A Service Broker MAY support configuration specific to an address using parameters; exposing this feature to users would require a Platform to support binding multiple routable addresses to the same Service Instance.
- - -
with:
- - -
Routing services are a class of Service Offerings that intermediate requests to applications, performing functions such as rate limiting or authorization. To indicate support for routing services, the catalog entry for the service MUST include the `"requires":["route_forwarding"]` property.

When creating a routing service type of Service Binding, a Platform MUST send a routable address, or endpoint, for the application along with the request to create a Service Binding using "bind_resource":{"route":"some-address.com"}.
- - -
I think the "if" is implied (and doesn't need to be explicitly called out)
