### ISSUE TITLE
Mixed case Plans

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#422]
Right now the spec requires that plan names be all lowercase letters, however CF allows mixed-case letters. While we could look at this as bug in CF, since CF is the baseline implementation on which the spec is based (and we don't want to break existing brokers), I'm wondering if we need to loosen the language in the spec or ask CF to be spec compliant.  I'm leaning towards changing the spec.

**Comment by duglin** [comment]
@mattmcneeney @zrob can you guys confirm that CF allows uppercase letters in Plan names?

**Comment by duglin** [comment]
on today's call we tentatively agreed to change the spec to allow uppercase letters.  PR coming soon.

**Comment by mattmcneeney** [comment]
CF allows both plan names and service names to have mixed case, so it would be great to update the spec. to loosen the requirements on both of these fields.

_Interesting side note: When checking for unique service names and broker registration time, CF doesn't allow for two services to be registered regardless of case, i.e. "test" and "TEST". But it is possible to register a service called "MyService"._
