### ISSUE TITLE
Doesn't GET request need authentication?

### ISSUE THREAD

**Issue by leonwanghui** [openservicebrokerapi/servicebroker#432]
When I had a look at our [OpenAPI doc](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openservicebrokerapi/servicebroker/v2.13/openapi.yaml#/), I found that not all requests contain ```X-Broker-API-Originating-Identity``` parameter (specifically GET request doesn't contain). So it confuses me if it is safe to expose GET request (currently we have two GET requests) to the public, and IMO authentication SHOULD be guranteed in all user requests to accomplish access controller.

Just challenge me if you have any doubts : )

**Comment by duglin** [comment]
This is actually something we're running into as well. The problem we're running into is that some requests are more system-generated than user-initiated - like GET /v2/catalog.  We're still working on a proposal but our current thinking is that some system ID should be used in those cases.

Keep in mind though, even w/o this header the request is still required to have some kind of auth (even if just basic auth).

**Comment by leonwanghui** [comment]
Sure, please ping me if you finish the proposal, thx!发自我的iPhone------------------ Original ------------------From: Doug Davis  <notifications@github.com>Date: 周六,1月 27,2018 09:16To: openservicebrokerapi/servicebroker <servicebroker@noreply.github.com>Cc: Leon Wang <wanghui71leon@gmail.com>, Author <author@noreply.github.com>Subject: Re: [openservicebrokerapi/servicebroker] Doesn't GET request needauthentication? (#432)This is actually something we're running into as well. The problem we're running into is that some requests are more system-generated than user-initiated - like GET /v2/catalog.  We're still working on a proposal but our current thinking is that some system ID should be used in those cases.
Keep in mind though, even w/o this header the request is still required to have some kind of auth (even if just basic auth).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openservicebrokerapi/servicebroker","title":"openservicebrokerapi/servicebroker","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openservicebrokerapi/servicebroker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@duglin in #432: This is actually something we're running into as well. The problem we're running into is that some requests are more system-generated than user-initiated - like GET /v2/catalog.  We're still working on a proposal but our current thinking is that some system ID should be used in those cases.\r\n\r\nKeep in mind though, even w/o this header the request is still required to have some kind of auth (even if just basic auth)."}],"action":{"name":"View Issue","url":"https://github.com/openservicebrokerapi/servicebroker/issues/432#issuecomment-360947411"}}}

**Comment by leonwanghui** [comment]
@duglin Sure, please ping me if you finish the proposal, thx!

**Comment by zrob** [comment]
on call we discussed that some requests are made by the platform and not a user in the normal sense.  these cases include orphan mitigation and last operation polling.

do we have a concern that the broker's auth mechanism might prevent the platform from performing these operations?

does it make sense to reserve a general "platform" user name or to recommend using the user that is used in the basic auth broker linkage?

**Comment by mattmcneeney** [comment]
I believe that the purpose of the `X-Broker-API-Originating-Identity` header is to inform service brokers which end-user triggered a request. Since calls to fetch the catalog are sometimes not triggered by an end-user, then I think no `X-Broker-API-Originating-Identity` header makes the most sense in this case. Let me know if anyone still disagrees - closing for now.
