### ISSUE TITLE
can Platforms prematurely abort polling?

### ISSUE THREAD

**Issue by kibbles-n-bytes** [openservicebrokerapi/servicebroker#435]
Currently, we have no guidance as to whether the Platform is expected to make sure an async request it's started has finished before stopping polling. In the polling instance section, we specify the following:

> Responses with any other status code SHOULD be interpreted as an error or invalid response. The Platform SHOULD continue polling until the Service Broker returns a valid response or the maximum polling duration is reached.

I interpret this as meaning the Platform shouldn't abort at the first sign of an invalid response, though the "SHOULD" here makes it sound like the Platform's isn't really supposed to ever abort unless it has absolutely given up on the operation.

I think Platforms should have the leeway to decide if they want to stop polling an operation. One of the reasons to do this would be because it's decided the operation has timed out, but another reason could be if the user requested a provision shortly followed by a deprovision, and the Platform doesn't care anymore about the state of the provision. In this case, some brokers may even be able to also abort the provision themselves and speed up the whole process, while worst-case the Platform could retry the deprovision request until it's accepted.

**Comment by mattmcneeney** [comment]
The deprovisioning and unbinding sections of the spec now talk about what should happen in these scenarios. For example:

> If a Service Broker accepts the request to delete a Service Instance during the process of it being provisioned, then it MUST have the net effect of halting the current creation process and beginning the deletion of any resources associated with the Service Instance.
