### ISSUE TITLE
Relax the format of "CLI-friendly name"

### ISSUE THREAD

**Issue by mihnjong** [openservicebrokerapi/servicebroker#442]
The spec says "As of now, the spec says "The CLI-friendly name of the plan. MUST only contain alphanumeric characters and hyphens (no spaces). MUST be unique within the service. MUST be a non-empty string.", which is too strict to express semantic versions in plan names.

For example, "v1.0.0." violates the rule. Can we make it relax a bit even before going to 3.0?

There're a few discussions before (#305 #154), but it would be great if we allow some special characters such as period and underscores.

**Comment by leonwanghui** [comment]
I think this proposal could also be applied to `Description` field, just my thought : )

**Comment by duglin** [comment]
@leonwanghui what kind of "loosening" would you want to see on the "description" field? Its wide open now aside from it must be a non-empty string if present.

@mihnjong would adding periods to the list of valid chars be sufficient?

**Comment by leonwanghui** [comment]
@duglin What I mean is if there is some use cases to keep this filed required, because I didn't find any explanation in the spec.

**Comment by duglin** [comment]
@leonwanghui I think its only required for Service and Plan in the /v2/catalog endpoint - which makes some sense since you probably what some kind of info there to help end users know which one to pick. Are you suggesting we make it optional in those spots too? Or are you just asking for some text in the spec to explain why its required?

**Comment by leonwanghui** [comment]
To me the second option is better, we should avoid any confusion in explanation of all required fields.

**Comment by mihnjong** [comment]
@duglin Let me create a PR early next week.
@leonwanghui IMHO, "A short description of the service/plan" sounds self-explanatory (without description, you will not know what they are).

**Comment by mihnjong** [comment]
Not to break the compliance with k8s service catalog, we can follow the naming style at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

```
up to maximum length of 253 characters and consist of lower case alphanumeric characters, "-", and ".".
```

**Comment by mihnjong** [comment]
PR #452 is out for review.
