### ISSUE TITLE
OSB logo policy

### ISSUE THREAD

**Issue by fmui** [openservicebrokerapi/servicebroker#445]
What is our reuse policy regarding the OSB logo? I guess it is covered by the Apache license, but should we be more precise here? For example, we could add text like this:

> Everyone who supports the Open Service Broker API is encouraged to download and use the logo without cost or restriction. Downloading and/or using the Open Service Broker logo implies acceptance of the following conditions. It is expected that any person or entity using the Open Service Broker logo does so in an appropriate fashion, the logo is not modified, the design colors and aspect are retained and space around the logo is sufficient so as to prevent the logo from being construed as part of another graphic element.
> 
> The Open Service Broker API logo is not intended to imply certification or any official compliance status.

**Comment by duglin** [comment]
@chipchilders what does the CFF (or CF) do for stuff like this?

**Comment by chipchilders** [comment]
The TM policy is here > https://www.cloudfoundry.org/trademark/

The OSBAPI reference to that is here > https://www.openservicebrokerapi.org/governance

Specifically > 


Licensing and Trademarks
The licensing and copyright of the API specification and any software produced within the PMC will follow the CFF Intellectual Property Policy, including:
All contributions to the Open Service Broker API and related projects require the individual contributing to be covered by a CLA.
All work of the Open Service Broker PMC will be licensed using the Apache Software License version 2.
Labeling of all artifacts as “Copyright (c) YYYY CloudFoundry.org Foundation, Inc. All Rights Reserved.”
The use of the CFF trademarks and word marks is governed by CFF’s Trademark Usage Guidelines.
Implementations (consumer or provider) of the Open Service Broker API are encouraged to document which version(s) of the Open Service Broker API they support. References to the API itself should be referred to as the “Open Service Broker API”.

**Comment by chipchilders** [comment]
Have a look and let me know if there are any thoughts for improvement or clarity!

**Comment by duglin** [comment]
@fmui does @chipchilders's response answer your question?

**Comment by fmui** [comment]
Technically, everything is there. But I know from other standard working groups that people want/need an extra statement about the logo. Can they put it on their websites or in publications? Can it be used for marketing? Is there some kind of certification process to use the logo? The "Licensing and Trademarks" section talks about "API specification and any software". Does this cover the logo? How do I label the logo with a copyright statement?
This is all about clarity.

Additionally, at some point somebody will ask for his-res versions of the logo...

**Comment by mattmcneeney** [comment]
@avade on that note, is there a high res version of the logo you can add to the repo?

**Comment by chipchilders** [comment]
@fmui do you have any specific suggestions for what we should change? 

@mattmcneeney @duglin if the PMC wants to have us change the policy to support a specific goal, happy to help with that if the goal can be articulated!

@christopherclark Adding you to this thread... can you please work with Melissa L to get a high-res OSBAPI logo to @mattmcneeney so that he can add to the repo?

**Comment by christopherclark** [comment]
@chipchilders I have sent Matt the logo.

**Comment by mattmcneeney** [comment]
Logo added in #463. Thanks @christopherclark !
