### ISSUE TITLE
dashboard_client required fields

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/servicebroker#448]
In CF, if the `dashboard_client` field is included in the catalog, then we check that the object contains `id`, `secret` and `redirect_uri`. If any of those fields do not exist, we fail broker registration.

However, in the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#dashboard-client-object), these fields are not required.

Are other platforms using the `dashboard_client` object? If so, are the fields inside required? I'd like to mark these as required in the spec (or at least think about doing that in the future) to match up with CF's behaviour.

**Comment by duglin** [comment]
While I have no idea how common of a use case it is, there could be global, static, services that don't require those fields - right?

**Comment by mattmcneeney** [comment]
As in they only require `redirect_uri` and not `id` and `secret`? (That does kinda make sense, especially if there is no authentication being used)

**Comment by mattmcneeney** [comment]
Closing this as this is likely a CF-only issue.
