### ISSUE TITLE
408 (Request Timeout) is a client-side error and should not require orphan mitigation

### ISSUE THREAD

**Issue by nilebox** [openservicebrokerapi/servicebroker#449]
In the [orphan mitigation section](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans) there is a special case for 408 separate from other 4xx errors:

| Status Code Of Service Broker Response | Platform Interpretation Of Response | Platform Initiates Orphan Mitigation? |
| --- | --- | --- |
| 408 | Timeout failure | Yes |
| All other 4xx | Request rejected | No |

`408 Request Timeout` means:
> "The server did not receive a complete request message within the time that it was prepared to wait."

It's a client-side error just as other `4xx` codes, i.e. **server explicitly rejected the request** without processing it (hence no side effects that would require orphan mitigation). 
There is already a separate item for `Timeout` and `5xx` errors which require orphan mitigation, including the `504 Gateway Timeout` error code, in which case the platform indeed doesn't know whether broker has successfully provisioned a new instance or not.

**Comment by avade** [comment]
From the call today:

> The assumed broker behaviour is that it did no work as it never received a completed request.

**Comment by duglin** [comment]
I actually think the next sentence from the http spec is they key one:
> The client MAY repeat the request without modifications at any later time. 

Which, to me, implies that there should have been no impact/side-effect from this failed attempt.

**Comment by nilebox** [comment]
@duglin agreed. Can you update the spec please?
