### ISSUE TITLE
Minor naming inconsistencies around schemas

### ISSUE THREAD

**Issue by luksa** [openservicebrokerapi/servicebroker#450]
I'd like to point out a few inconsistencies related to how the various schema objects are named.

1. "[Schema object](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#schema-object)" should be changed to "Schemas object", since it contains two schemas (also, the type in the OSBAPI OpenAPI spec is already called `SchemasObject`. See [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml#L481).

2. "[Service Instances object](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#service-instances-object)" should be changed to "Service Instance Schema object" to match the OpenAPI spec [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml#L489)

3. "[Service Bindings Object](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#service-bindings-object)" should be changed to "Service Binding Schema object" to match the OpenAPI spec [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml#L497)

Also, since `ServiceInstanceSchema` contains multiple schemas, it should be called `ServiceInstanceSchemas` to keep it consistent with the `Schemas` object. Same for `ServiceBindingSchemas`.

**Comment by mattmcneeney** [comment]
@luksa These inconsistencies look legitimate and should be fixed. Do you want to open up a PR to do this?

**Comment by luksa** [comment]
Closing (fixed in #459)
