### ISSUE TITLE
Change how we link to type definitions inside the spec

### ISSUE THREAD

**Issue by luksa** [openservicebrokerapi/servicebroker#451]
I suggest we change the way we link to the definitions of OSBAPI types in the spec. 

For example, let's take the row that shows the "schemas" field in https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#plan-object. 

I suggest we replace the word "object" in the second column with the following text: "[Schema](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#schema-object) object". As shown here, the name of the type links to the description of said type.

Similarly, the second column in the "plans" row under [Service Objects](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#service-objects) would be "array of [Plan](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#plan-object) objects" or simply "[][Plan](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#plan-object)" instead of "array-of-objects" as we have now.

**Comment by luksa** [comment]
Something along the lines of: https://github.com/luksa/servicebroker/blob/9620a17665768dcde2f4d6a426d7d7eea2f6f9a1/spec.md#plan-object

**Comment by duglin** [comment]
@luksa want to open a PR so people can see the proposed edits in context?
ok if I assign this and #450 to you?

**Comment by luksa** [comment]
Closing (fixed by #459)
