### ISSUE TITLE
Spec should explicitly state that duplicate requests should return 202 AND the original operation.

### ISSUE THREAD

**Issue by khipkin** [openservicebrokerapi/servicebroker#453]
Currently, the spec says that `202 Accepted` should be returned if the work is in progress for provisioning, updating a service instance, binding, unbinding, and deprovisioning when another request is received for the same work. Readers can assume that the operation returned with `202` should be the same as was returned by the original request.

I believe that this should be an explicit requirement stated in the spec for each of provisioning, updating a service instance, binding, unbinding, and deprovisioning.

**Comment by mattmcneeney** [comment]
@khipkin Thanks for raising this. I think this makes sense and would be a useful piece of clarification in the spec. Do you want to raise a PR for this or are you happy for me to?

**Comment by khipkin** [comment]
I can send a PR! Thanks.

**Comment by khipkin** [comment]
First PR is for instance operations, requesting a merge into master.

Second PR will be for binding operations, requesting a merge into the async-bindings proposal branch.

**Comment by mattmcneeney** [comment]
@khipkin It looks like this is all good to go, so I'll close this.

**Comment by khipkin** [comment]
@mattmcneeney I was actually still waiting for the async-bindings proposal branch to get merged, since the async binding and unbinding descriptions still need to be updated.

**Comment by mattmcneeney** [comment]
Ah good point! I've updated the PR now #334. Can you double check that looks OK to you?
