### ISSUE TITLE
Spec should be uniform in naming entities

### ISSUE THREAD

**Issue by DevasiaThomas** [openservicebrokerapi/servicebroker#455]
This is with respect to Provisioning and Updating. For eg: in Provisioning its called space_guid but when it comes to Updating for previous values its called space_id. Can we make this uniform please?

**Comment by mattmcneeney** [comment]
@DevasiaThomas I totally agree. However the`space_id` field in the `previous_values` object has been [deprecated](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#previous-values-object) and will be removed in a future version of the spec. This will remove this inconsistency and so I don't think there is much else we can do at this time.

**Comment by DevasiaThomas** [comment]
@mattmcneeney Yes, I saw that for associated fields as well. I had this cool construct in Java using inheritance and a contains relationship to deal with the json request body for Update. And when things didn't map I was like "duh..." XD. Btw at the moment context's fields aren't defined properly - will it be left platform dependent or will you be defining it in the next version? I would like it if you guys defined it.

**Comment by mattmcneeney** [comment]
You may have seen this, but we have some of the `context` fields defined in [profile.md](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object). It's platform dependent and subject to change, hence it is in a separate 'spec' for now.

**Comment by DevasiaThomas** [comment]
Yeah I saw that. Thanks.
