### ISSUE TITLE
k8s backend

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#46]
Tracking issue

To prove our abstraction works beyond local storage.
- [x] create the storage resource on k8s
- [x] service brokers
  - [x] add broker #29 
  - [x] list brokers #29 & adjusted in #45
  - [x] get broker #45 
  - [x] delete broker  #47
  - [x] update broker #92
- [x] service definition
  - [x] add #84
  - [x] list #85
  - [x] get #85
  - [x] delete
  - [x] update #88
- [ ] service plans
  - [x] add #84
  - [ ] list
  - [x] get #85
  - [x] delete #91
  - [x] update #92
- [x] service instances
  - [x] add #88
  - [x] list #88
  - [x] get #88
  - [x] delete  #91
  - [x] update #89
- [x] service bindings
  - [x] add #89
  - [x] list #89
  - [x] get #89
  - [x] delete  #91
  - [x] update #92

**Comment by MHBauer** [comment]
Based on refactor by @duglin in #80, prioritize `add service` & `add service plan` to re-enable k8s backend.

**Comment by MHBauer** [comment]
Looking good!

**Comment by shalako** [comment]
I believe this issue belongs in a K8s project. This repo is not meant for development of a particular platform's marketplace controller. Can this be closed?

**Comment by duglin** [comment]
waiting on https://github.com/openservicebrokerapi/servicebroker/issues/102
