### ISSUE TITLE
Platform notion in case of the catalog endpoint

### ISSUE THREAD

**Issue by subhankarc** [openservicebrokerapi/servicebroker#460]
Hi,

In case of a broker which is consumed from two different envs, there is currently a way to find the consuming env through context in case of provisioning.

But for catalog API, there is no way to know consuming platform. If the broker needs to filter out some plans based on envs, this would be necessary. 

In that case, one option could be to register two different path in two different env and identify based on that.

Is there a recommendation to follow in this scenario?

**Comment by duglin** [comment]
each platform would typically have its own credentials for the broker - so that's another way of knowing.

**Comment by duglin** [comment]
Closing with the assumption that my response is sufficient

**Comment by subhankarc** [comment]
Hi @duglin 

So basically we should follow either of these two ways.

1. Register two different path in two different envs and identify based on that.
2. Identify based on the Users.

Is that understanding correct?

**Comment by duglin** [comment]
Yes. Either provide each platform with their own URL to the broker, or provide each platform with their own set of credentials (which you should do anyway so that you can revoke them on a per platform basis anyway).
