### ISSUE TITLE
Order of validation checks in OSB API

### ISSUE THREAD

**Issue by subhankarc** [openservicebrokerapi/servicebroker#468]
In case of async parameter check, [this](https://github.com/openservicebrokerapi/osb-checker/blob/master/2.13/tests/test/test.js#L531-L538) code sends an empty body and it does not send the accept_incomplete parameter in query.

[Service Fabrik broker](https://github.com/cloudfoundry-incubator/service-fabrik-broker) which checks for the mandatory parameters first, will send a Bad Request for the same and hence the test fails as the test expects Unprocessable Entity(422) error.

Is there a defined order of checks the broker has to do? If not, then the test should be enhanced.

The same issue is raised [here](https://github.com/openservicebrokerapi/osb-checker/issues/30) as well but as it is also related to the spec definition, I raise it here as well.

**Comment by duglin** [comment]
I agree that if the spec does not mandate the order of the checks then the checker tool shouldn't either. We would probably need to consider each situation on its own, but in general when a bad request could fail for more than one possible reason then the receiver of the message should be able to decide the order of the checks and therefore which reason it fails. 

Net: I think the checker tools needs to be fixed.

**Comment by subhankarc** [comment]
Thanks for your input. I too feel that the order of the check should not matter here.
 I would keep the issue on osb checker open then and close this.
