### ISSUE TITLE
PR review comments not signaling the LGTM approval.

### ISSUE THREAD

**Issue by n3wscott** [openservicebrokerapi/servicebroker#472]
If you use the github review approval and in that message add LGTM, the script does not update the PR to be approved. Only direct top level PR comments seem to work. Can we use a better way to approve things other than the current way with the master script editing the comments?

https://github.com/openservicebrokerapi/servicebroker/pull/466#pullrequestreview-103852657

**Comment by mhrivnak** [comment]
A proposal came up in the call to stop using the bot and instead use the github approval workflow alone. A question was raised about needing to count the number of reviews.

It appears that github allows you to specify how many reviews are required, so that may resolve that concern. See step 6 here:

https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

**Comment by duglin** [comment]
I can't figure out from the docs if its just reviews from maintainers or anyone - not sure I would want reviews from some random person to be counted in the official tally.

**Comment by mhrivnak** [comment]
This document seems fairly clear: https://help.github.com/articles/about-required-reviews-for-pull-requests/

"When required reviews are enabled, anyone with access to the repository can approve changes in a pull request. However, you won't be able to merge your pull request until the required number of reviewers **with write or admin permissions in the repository** approve your pull request's changes in their review."

**Comment by duglin** [comment]
ah, ok I was looking at the setting page and just saw this text:
When enabled, all commits must be made to a non-protected branch and submitted via a pull request with the required number of approving reviews and no changes requested before it can be merged into master. 

Which didn't answer my question

**Comment by n3wscott** [comment]
Also a note about the original misunderstanding (on my part) an LGTM as a Review Comment (ie: `Comment - Submit general feedback without explicit approval.`) does not count as an LGTM. LGTM only counts in comments made outside of the `Review Changes` button. 

Doug has enabled the bot to count `Review Changes` -> `Approve` to count towards the requirement of 4. 

So now you can have a mix of LGTM and Approve, and it works out as you expect. Just don't do `Review Changes` + LGTM. Use `Review Changes` OR LGTM PR comments.
