### ISSUE TITLE
clusterID should be cluster_id ?

### ISSUE THREAD

**Issue by n3wscott** [openservicebrokerapi/servicebroker#477]
No other json field inside the OSB spec has caps. It looks like the convention would be `clusterID` -> `cluster_id`.

**Comment by duglin** [comment]
It kind of depends on who owns the field - kube vs osb.  osb does prefer underscores but kube prefers w/o.  I went with clusterID because I viewed it as a kube thing (since its data about a kube cluster) but if the group wants it with an underscore I don't mind switching it.

**Comment by n3wscott** [comment]
My gut says requiring caps in a json payload will cause pain is why I bring it up and osb likes the `_` which is why I suggest `cluster_id` vs `clusterid` but I don't really care which wins.

**Comment by duglin** [comment]
what if we go with `clusterid` ? no underscore.  While I can go either way, I do have a slight preference for kube data to follow kube's pattern.

**Comment by n3wscott** [comment]
`clusterid ` is fine with me like I said (I kinda dislike the `_` in the current spec but don't tell anyone)

**Comment by duglin** [comment]
@pmorie @MHBauer you guys ok with `clusterid` ?

**Comment by MHBauer** [comment]
yes
