### ISSUE TITLE
What does plan_updateable apply to?

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#491]
See: https://github.com/kubernetes-incubator/service-catalog/issues/1906

Does it just control whether you can change the "plan" or does it also indicate whether you can update the existing Instance's parameters (w/o changing the plan)?

We should clarify this in the spec.

/cc @luksa

**Comment by n3wscott** [comment]
@Samze That is how I was understanding the property too.

**Comment by mattmcneeney** [comment]
It doesn't look like there is anything else to do here, so I'll close it. Please re-open if I'm mistaken.

**Comment by luksa** [comment]
I've revisited this and there is something else to do. The spec specifically says that if `plan_updateable` is false, the platform is not allowed to update the service instance at all:

> If "plan_updateable": true is declared for a plan in the Catalog endpoint, the Platform MAY request an update of a Service Instance using the given plan. *Otherwise, Platforms MUST NOT make an update request to the Service Broker for any Service Instance using the given plan*.

I've submitted a PR that clarifies this: #519
