### ISSUE TITLE
Make this project easier for people to understand and get started with

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/servicebroker#492]
From the recent F2F, we should look to:
* Write an executive summary describing why this project exists, why open-ness is important, and the basics of the specification (who wants to take this?) and *why should you care*
* Add this information to this repository and the [openservicebrokerapi.org](openservicebrokerapi.org) website (@duglin or myself can do this)
* Make sure this repository and the [openservicebrokerapi.org](openservicebrokerapi.org) website have easy to understand information and links

It was also mentioned that we could look to do this as part of the upcoming v2.14 release.

**Comment by mattmcneeney** [comment]
Any volunteers to help me draft the executive summary? I can then take care of updating all of the relevant sites

**Comment by n3wscott** [comment]
I would love to help with this, I have some opinions that might not be globally shared though so we should draft something and iterate on it. I don't have time to think about this until after May 15 though.

**Comment by n3wscott** [comment]
Ok I am ready to start the talking :D

**Comment by mattmcneeney** [comment]
Great @n3wscott! If you want to take a first stab at it and then either drop it in here, a google doc or email it over to me, I can take a second look and then get the various websites updated!

**Comment by mattmcneeney** [comment]
_Sorry... hit the wrong button_

**Comment by mattmcneeney** [comment]
We added some more information on this project to the www.openservicebrokerapi.org homepage and added some more useful info to the getting started page in this repo, so closing this.
