### ISSUE TITLE
Create a high-level OSBAPI design doc

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#495]
At the 4/15/2018 F2F we talked about how perhaps we should have an example/exec summary/high-level/why should I care/design doc.  When and why you would use the optional bits of the spec.

Basically, more guidance for people trying to learn about the spec and its use cases.

**Comment by n3wscott** [comment]
I am also interested in this doc.

**Comment by duglin** [comment]
dup of https://github.com/openservicebrokerapi/servicebroker/issues/492, closing
