### ISSUE TITLE
we should use the github release feature

### ISSUE THREAD

**Issue by n3wscott** [openservicebrokerapi/servicebroker#499]
we are using branches as releases. We should use releases.

**Comment by leonwanghui** [comment]
It's a good idea to me. For github release, it will generate a tag automatically when publishing a new release, and developers can check into different tags directly without switching another branch.

**Comment by duglin** [comment]
@leonwanghui what did you mean by "check into different tags" ?  Tags are not branches so you can't "check into a tag" w/o first creating a new branch based on that tag.  Isn't that correct?  I still feel like a git newbie at times so I could be wrong.

**Comment by leonwanghui** [comment]
@duglin  For example, if there is new release called `v2.14` published on github, then a new tag `v2.14` will be generated automatically in master branch. And after developers download code from master branch, they can switch to the `v2.14` tag by running `git checkout v2.14`. Does it make clear?

**Comment by duglin** [comment]
@leonwanghui yes, being able to "check out" from a tag makes sense, it was the idea of "check in" to a branch that confused me.

**Comment by zeisss** [comment]
FYI: Tags are not branch specific, they are only based on a branch. When you create a tag/release it is independent of the original branch, which might get updated or deleted afterwards.

**Comment by clemensdiebold** [comment]
I think this issue can be closed because there are already four releases published. @fmui
