### ISSUE TITLE
What error code to use for rejecting concurrent bind requests?

### ISSUE THREAD

**Issue by kibbles-n-bytes** [openservicebrokerapi/servicebroker#501]
The spec says that for the "concurrent requests that mutate the same resource", it is expected that the error response from the broker contains the "ConcurrencyError" error code. What about in the case that the broker is rejecting a concurrent bind request? Is it expected/acceptable for the broker to use this error code?

**Comment by n3wscott** [comment]
I would support expanding the error to cover both.

**Comment by mattmcneeney** [comment]
Agreed. Can you submit a PR @kibbles-n-bytes ?

**Comment by mattmcneeney** [comment]
The binding section in the spec now says:
> Additionally, if the Service Broker rejects the request due to a concurrent request to create a Service Binding for the same Service Instance, then this error MUST be returned (see Blocking Operations).

Closing this!
