### ISSUE TITLE
Proposal: how we think about v3 and beyond 

### ISSUE THREAD

**Issue by n3wscott** [openservicebrokerapi/servicebroker#502]
Context
--------

In the April 2018 F2F we spent a lot of time talking about the "v3" future. The debate mixed to ideas: 

1. The OSBAPI has some crufty stateless assumptions that make the api awkward because there are redundant fields where the broker should know how to look this data up.

2. The OSBAPI does not follow modern RESTful guidelines.

Proposal
---------

We declare v3 to be API basically compatible with v2 except some cleanup. We adjust it to follow some of the ideas we have developed in the async allowed world and work them in as first class rather than as extra parameter, we make an assumption that there is some state being stored in the broker, full CRUD is assumed, etc (we decide these details later). But all of the current changes get brought along into v3 (generic actions and Json schema... etc). But this comes out much quicker than a rewrite.

Then we say v4 is a pivot on the API and we do the real full refactor, if still wanted after v3 and we take a look at what a fancy API would look like. Mostly a rewrite.

**Comment by pmorie** [comment]
I think the a "clean up" v3 is a good idea, and probably more achievable than an outright rewrite or full reimagination.

**Comment by pmorie** [comment]
...at least as an incremental step.

**Comment by mattmcneeney** [comment]
From my perspective, the main benefit of this would be to increase the readability of the spec, removing a few 'required but deprecated' fields. I'm not sure we gain much else from this unless I'm mistaken.

The downsides are broker authors are going to have to support two sets of endpoints (`/v2` and `/v3`) which behave very similarly, and then in the future they will have to support three sets of endpoints. This could be frustrating, and my guess is it would take a long time to see most brokers move with this change, and then even longer with `v4`.

**Comment by n3wscott** [comment]
@mattmcneeney yes  fewer 'required but deprecated' fields, but also perhaps we can take half steps towards v4 and remove service id and plan id from instance delete, for example. I can think of a few other concessions made for stateless brokers that make the api cumbersome to interact with, and perhaps even is not RESTful for how we do UPDATE instance.

**Comment by mattmcneeney** [comment]
Closing this for the time being. We will need to have a v3 discussion at some point in the future, but bearing in mind the work this will likely require for many service providers, I think we should put the 'clean up' on hold until we have some stronger reasons to make such a change.
