### ISSUE TITLE
Pain point: Returning 200 for existing instance

### ISSUE THREAD

**Issue by krancour** [openservicebrokerapi/servicebroker#505]
The following is excerpted from the spec for [provisioning responses](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#response-2)

> 200 OK MUST be returned if the service instance already exists, is fully provisioned, and the requested parameters are identical to the existing service instance. The expected response body is below.

> 409 Conflict MUST be returned if a service instance with the same id already exists but with different attributes. The expected response body is {}, though the description field MAY be used to return a user-facing error message, as described in Broker Errors.

I want to call attention to the "requested parameters are identical" having been a pain point for us.

First, this is an apples to oranges comparison. A _request_ may have parameters, but an existing instance has _attributes_ which are _derived from, but not necessarily identical to_ the provisioning parameters on the original request that brought about the existence of that service instance.

By way of example, suppose that in the absence of some optional parameter x, that parameter x is defaulted to a random value or something opaque, like a UUID. There is now an impedance between the parameters of the provisioning request and the attributes of the service and a straight comparison isn't possible.

If the spirit of the portion of the spec in question is reasonably interpreted as "if the provisioning request would result in a service instance that is logically identical to the existing service instance," then this is problematic because the impedance described above may make that determination impossible.

When x matches perfectly, logical equivalence is obvious. Things are _really_ fuzzy when x does not match perfectly. If there is no match is it because:

1. One request provided a value for x and the other did not. The one value doesn't match the generated value. These are not logically equivalent because one request "didn't care" about the value of x and the other did.
1. Both requests provided values for x and they were different. These are obviously not logically equivalent.
1. Neither request provided a value for x. These _are_ logically equivalent because neither request "cared" about the value of x.

If it's not possible to know which of those three cases you have encountered, then the logical equivalence of two things as a function of parameter x is indeterminate. One _could_ sort this all out by tracking a lot of additional state. (Would need to remember _original_ provisioning paramters. i.e. _Before_ missing optional params had generate default values applied.) Personally, I'd rather not do that, but for stateless brokers (which seem to be a thing), it may be impossible to sort this out.

**What am I asking for?**

Let's revisit the notion that the following existing bit of spec involves an apples to oranges comparison:

> 200 OK MUST be returned if the service instance already exists, is fully provisioned, and the requested parameters are identical to the existing service instance. The expected response body is below.

If we can agree on that and can subsequently agree that this impedance is problematic, then I would wish for us to collectively come to some consensus on how we can remediate that flawed bit of spec.

fwiw, in an ideal world, I'd like to _always_ return a 409 when a provisioning request is received with an instance ID that already exists. While it might not be possible to amend the spec in such fashion without causing a BC, I'd like to understand the practical implications of making such a choice in our own broker. Under what conditions are the known and well understood platforms (k8s svc-cat and CF) going to send _duplicate_ requests that would force a broker to determine whether a request would logically result in a resource identical to one that already exists.

All of this applies to bindings also.

**Comment by n3wscott** [comment]
I am not so sure it is apples to oranges. The spec is asking you to either 1, keep around the original parameters. Or 2, be able to convert or understand given parameters result in instance attributes. 

So it is not so much apple is an orange, it is more of apple can make the same orange.

**Comment by krancour** [comment]
@n3wscott sounds like our interpretations aren't that far off from one another.

> it is more of apple can make the same orange

I'm proposing that determination cannot always be made.

**Comment by duglin** [comment]
@krancour I'm going to make you the owner of this one - hope that's ok.

**Comment by krancour** [comment]
Yup.

**Comment by duglin** [comment]
AI for all - please provide your usecases for when multiple provision requests might be sent to the broker.

**Comment by krancour** [comment]
To recap some of the discussion from today's OSB meeting:

(These are notes of sentiments that individuals expressed. They are not direct quotes.)

@krancour: In some circumstances, the attributes of an instance aren't a 1:1 mapping to provisioning parameters-- and you can't necessarily always reverse engineer what the provisioning parameters were.

@pmorie : In such cases, it seems brokers would need to "remember" original provisioning parameters-- which nearly mandates statefulness. Raises the specter of the larger question of what the spec says (even implicitly) about stateful vs stateless brokers.

@pmorie: Duplicate provisioning requests from the platforms are an inevitability.

@duglin: We should try to solve this issue without taking on the broader stateful vs stateless question, if we can.

AI-- @krancour to propose something.

**Comment by krancour** [comment]
Since platforms generate and supply instance IDs, if a duplicate provisioning request for a given instance ID comes in, it's a reasonable assumption that both the original and the dupe _both_ came from the (same) platform.

Assuming duplicate requests are sent as a consequence of some unfortunate circumstance (like a crashed process), it's also reasonable to conclude that provisioning parameters would not have changed between the original request and the duplicate. 

What I propose below takes it for granted that provisioning parameters do not change between an original and duplicate provisioning request.

With that in mind, I propose we change provisioning text as follows:

> 200 OK MUST be returned if the service instance already exists ___and is___ fully provisioned ~~, and the requested parameters are identical to the existing service instance~~. The expected response body is below.

This communicates the existence of an instance in a way that doesn't present as an error and it does so without taking parameters into account.

The following stays the same, since it wasn't as specific as the above WRT behavior for duplicate requests:

> 202 Accepted MUST be returned if the Service Instance provisioning is in progress. The operation string MUST match that returned for the original request. This triggers the Platform to poll the Service Instance Last Operation Endpoint for operation status. Note that a re-sent PUT request MUST return a 202 Accepted, not a 200 OK, if the Service Instance is not yet fully provisioned.

The following is eliminated in its entirety:

> ~~409 Conflict MUST be returned if a service instance with the same id already exists but with different attributes. The expected response body is {}, though the description field MAY be used to return a user-facing error message, as described in Broker Errors.~~

Existing language for update is not very specific about how duplicate requests are handled, so I do not believe there is anything to correct in that regard.

**Comment by krancour** [comment]
We could note for the sake of platforms that older brokers might return a 409. Existing brokers that account for that shouldn't back out any logic for handling 409s.

**Comment by mhrivnak** [comment]
According to the [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.4), in a case where a PUT request is received for an existing resource, a 200 response implies that the resource's existing "representation is successfully modified in accordance with the state of the enclosed representation." We can work with that.

If we assume equivalence between any existing service instance and the representation in a follow-on PUT request (nothing in the RFC dictates how we make the comparison), it's not unreasonable to return a 200. That would imply that the current representation, whether it was modified or not, fulfills the intent of the request. If our spec clearly documents that the representation in the body of a PUT request is never compared to an existing representation, I think @krancour's proposed change is reasonable.

Of course that all depends on whether it's ok to assume equivalence, or whether someone has a use case for changing parameters between PUT requests on the same resource.

**Comment by krancour** [comment]
There was some pushback on this in the OSB API call today.

An assumption upon which the proposed change was predicated was that platforms would _not_ change params between two (ostensibly duplicate) provisioning (PUT) requests because sending a duplicate PUT request is presumably and edge case that occurs when a platform process has died after sending the PUT request, but before receiving or precessing the response. In such cases, the duplicate request would presumably be identical to the original in all ways and would _not_ have different parameters-- because why would it?

Some have challenged this assumption-- citing alternative scenarios which I don't quite understand in which a second PUT request for the same instance id is _not_ a result of what I described above. Can I ask people to please volunteer the details of any of those cases here?

cc @n3wscott @duglin

**Comment by krancour** [comment]
While I do still think there's still an issue here, it doesn't seem there has been widespread consensus on that point. In my own broker, we've made some architectural changes to negate the impact that this perceived issue had on us, so I'm going to close this instead of using mine or anyone else's bandwidth to try and convince anyone there's an issue here. In the absence of more important issues, I might feel differently, but time is better spent elsewhere. Happily closing this.
