### ISSUE TITLE
Should platforms always send deprovision request when failed to update the service instance?

### ISSUE THREAD

**Issue by leonwanghui** [openservicebrokerapi/servicebroker#508]
## Background
As the spec says:
`If the successful response includes a state of failed then the Platform MUST send a deprovision request to the Service Broker to prevent an orphan being created on the Service Broker`.

## Problem
Here is a use case below:
Service Broker A is published for providing volume service. After user B provisioned a volume service instance, he wants to resize the volume by calling `UpdateInstance` method. Then for some reasons A fails to complete update operation and it has to return `failed` state in the response of polling last operation. According to current spec definition, platform will deprovision the volume service instance automatically, but it is unacceptable for B because it would cause data loss.

## Proposed solution
For this specific scenario, I think both platform and service brokers could do some work to avoid the problem:
* Add a `state` of `rolled back` with the response of polling last operaion to indicate the repair work of service brokers
* Any service broker which supports rolling back feature MAY return this state to inform platforms everything is fine even though the update operation fails
* Platform should  perceive this state and keep the original parameter of service instance

**Comment by leonwanghui** [comment]
@duglin @n3wscott Please take a look at this issue, thanks!

**Comment by leonwanghui** [comment]
Hi @duglin , I got your point but IMO there is still some missing parts int the spec to indicate it. I can explain what I found in async update operation.

Firstly, there is no word to explain how platform would treat 5xx, from what I can see, the platform will try to deprovision the instance as long as it detects the `state` of `failed`.

Secondly, 5xx is normally returned for indicating server errors and it could be used for some internal errors occured in service broker. It's a bit odd to express it as rolled back meaning, one of the problems is those sevice brokers which doesn't support rolled back may return 5xx and then how can platform treat them differently?

I know it is kind of too big change to add another state, but it's the best option to fix the issue if the problem can not be solved the hole.

**Comment by duglin** [comment]
On today's call we talked about removing:
`If the successful response includes a state of failed then the Platform MUST send a deprovision request to the Service Broker to prevent an orphan being created on the Service Broker.` from the spec since we believe this was done in error. This was added back when we only had async provision, and we missed that the text would then apply to async binding - that was a mistake.

Everyone ok with removing it and treating it as  "fix" to the spec even though technical its a breaking change?

**Comment by leonwanghui** [comment]
@duglin It ok to me, thx!

**Comment by mattmcneeney** [comment]
SGTM

**Comment by duglin** [comment]
@leonwanghui did you want to open a PR for this?  I'm not hearing any objection
