### ISSUE TITLE
Inconsistency in asynchronous text surrounding 422

### ISSUE THREAD

**Issue by Samze** [openservicebrokerapi/servicebroker#520]
The spec contains both a MUST and a SHOULD on whether brokers return 422 & `AsyncRequired` if they do not support a synchronous request. 

`
If this parameter is not included in the request, and the Service Broker can only provision a Service Instance of the requested plan asynchronously, the Service Broker MUST reject the request with a 422 Unprocessable Entity.
`
[link](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#parameters-1)

`
If the parameter is not included or is set to false, and the Service Broker cannot fulfil the request synchronously (guaranteeing that the operation is complete on response), then the Service Broker SHOULD reject the request with the status code 422 Unprocessable Entity and a response body containing error code "AsyncRequired"(see Service Broker Errors).  
`
[link](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#asynchronous-operations)

`
422 Unprocessable Entity | MUST be returned if the Service Broker only supports asynchronous provisioning for the requested plan and the request did not include ?accepts_incomplete=true. The response body MUST contain a response body containing error code "AsyncRequired" (see Service Broker Errors).
`
[link](https://github.com/duglin/servicebroker/blob/d7e3267c429c9aa97c836ac436067782aaea5f0e/spec.md#response-2)

There a bunch of places where this is inconsistent. I'm guessing this was just a mistake and that a broker MUST return 422 and MUST return `AsyncRequired` if it does not support sync.

Happy to create a PR.

**Comment by duglin** [comment]
+1 to making it a MUST and to a PR - thanks!  Although, I'd like it if the PR also removed the duplicate text in the first place - just avoid this from happening again.
