### ISSUE TITLE
Feature Request: Last operation on bind / unbind operations

### ISSUE THREAD

**Issue by philbrookes** [openservicebrokerapi/servicebroker#525]
There is currently the ability to describe and read the last operation performed in a provision / deprovision / update, it would be beneficial to also have this ability for bind and unbind actions to update a last_operation parameter on the serviceBinding object.

When binding or unbinding a service which implements a bind/unbind playbook it can take a little while to complete, and being able to provide feedback to the user explaining what is currently happening would be useful to help them understand the delay.

**Comment by duglin** [comment]
@philbrookes see: https://github.com/openservicebrokerapi/servicebroker/pull/334

**Comment by philbrookes** [comment]
@duglin thanks, I missed that, I'll close this issue.
