### ISSUE TITLE
Incompatible change in v2.12: the broker MUST return 200 OK if the binding already exists 

### ISSUE THREAD

**Issue by fmui** [openservicebrokerapi/servicebroker#528]
In the v2.11 spec, the broker had a choice to return 200 OK when the platform sends identical parameters for an exiting binding.
The expected broker behavior changed in v2.12 to a MUST.

v2.11:

> 200 OK  May be returned if the binding already exists and the requested parameters are identical to the existing binding.

v2.12:

> 200 OK  MUST be returned if the binding already exists and the requested parameters are identical to the existing binding.

Although v2.11 was ambiguous, we are now in a situation where v2.11 brokers may not work with platform supporting v2.12 or v2.13.

**Comment by duglin** [comment]
Closing since #540 is closed/merged.
