### ISSUE TITLE
What is the change policy across major versions?

### ISSUE THREAD

**Issue by williammartin** [openservicebrokerapi/servicebroker#536]
While reading the [change policy](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#change-policy), it seems to be written as if either each version of the OSBAPI would be a different spec, or that there can be no breaking changes across major version changes? 

For example, `Existing endpoints and fields MUST NOT be removed or renamed.` makes sense for compatibility across minor versions, but I suspect this is not a guarantee the OSBAPI wants to make across major versions?

Do we need to add a small note to this effect?

**Comment by duglin** [comment]
Hmm, I think it was written with the assumption of just minor version changes - not major. Want to open a PR to clarify that?

**Comment by williammartin** [comment]
Maybe something as simple as updating the header to `Change Policy (minor versions)` would be enough to satisfy this?

**Comment by duglin** [comment]
Yup - sounds reasonable to me
