### ISSUE TITLE
Empty body on service instance update clarification

### ISSUE THREAD

**Issue by Samze** [openservicebrokerapi/servicebroker#538]
The specification states that an update of a service instance allows updating parameters or changing plan id. The [body](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-5) of the update states that both `plan_id` and `parameters` are optional. 

We do not clearly state that sending a update request with an empty body is not supported. We should probably mention this explicitly.

Note: in CF today we do not allow the user to perform an update without specifying either property.

**Comment by leonwanghui** [comment]
One quick question is can you explain a little bit about `empty`? IMO, set a nil body or an empty JSON can both be considered as `empty`.

**Comment by duglin** [comment]
Is there any reason to not just let it be a no-op?

**Comment by Samze** [comment]
@fmui mentioned that service manager send updates without a plan_id or parameters. Perhaps we just let brokers decide how to handle this request, I can see in most cases it be a no-op.
