### ISSUE TITLE
What is the broker response for a no-op update?

### ISSUE THREAD

**Issue by Samze** [openservicebrokerapi/servicebroker#539]
When the platform sends an update request the broker can return a 200 OK (forgetting async for a moment) to state that has processed the proposed changes (either parameters or plan id). What is not defined is the broker's behaviour if the platform sends another request with the same proposed changes and the broker does nothing.

For parameters we cannot necessarily assume that the endpoint is idempotent because a broker could have a parameter like `"upgrade": true`. But plan changes can be more black or white.

Do we want to add any clarifying text in the spec to guide broker authors on what to do when an update results in a no-op?

**Comment by duglin** [comment]
What kind of advise are you thinking of? My initial reaction is that it just returns a 200 and doesn't change anything on the instance.

**Comment by duglin** [comment]
@fmui any thoughts on this?
