### ISSUE TITLE
Cannot run tools/verify-phrases.sh on OSX

### ISSUE THREAD

**Issue by williammartin** [openservicebrokerapi/servicebroker#542]
Seems like this is an issue on OSX since I'm running this from master branch and it fails locally but passes on CI. 

```
± wm |master U:1 ✗| → ./tools/verify-all.sh
...
Verify terminology and RFC keywords
> ./tools/../profile.md
./tools/../tools/verify-phrases.sh: line 157: ${phrase^^} : bad substitution
```

Anyone else seeing this? My bash-fu is not great.

**Comment by mattmcneeney** [comment]
This still seems to be broken on OSX
```
❯ ./tools/verify-phrases.sh
./tools/verify-phrases.sh: line 157: ${phrase^^} : bad substitution
```

@duglin did you ever manage to look into a fix last year? Need your BASH wizardry :)

**Comment by duglin** [comment]
I thought I fixed this before... guesss not. Here ya go:  https://github.com/openservicebrokerapi/servicebroker/pull/649

**Comment by mattmcneeney** [comment]
Thank you @duglin !
