### ISSUE TITLE
Should the spec be more specific about Content-Type header?

### ISSUE THREAD

**Issue by williammartin** [openservicebrokerapi/servicebroker#543]
I notice a bunch of the example `curl` requests on the spec set the `Content-Type` to `application/json`. Is this actually part of the specification and if so, should we make that explicit somewhere?

**Comment by duglin** [comment]
wow - how did we miss that?  ;-)  want to open a PR?

Maybe we should create a new top-level section for "HTTP Headers" and put the version header, originating identity header and this new one under there as sub-sections?

**Comment by williammartin** [comment]
Sure I'll open a PR and we can chat. Not sure I want to put this together with OSBAPI specific headers quite yet but maybe we could refactor later if it looks like they should be. Will do the simple thing first.
