### ISSUE TITLE
Service Offering vs Service

### ISSUE THREAD

**Issue by Samze** [openservicebrokerapi/servicebroker#552]
In our [Terminology](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#terminology) section we define the follow terms:

> Service: A managed software offering that can be used by an Application. Typically, Services will expose some API that can be invoked to perform some action. However, there can also be non-interactive Services that can perform the desired actions without direct prompting from the Application.
> 
> Service Offering: The advertisement of a service that a Service Broker supports.

To me that means that the Service Offering is the thing in the catalog with an ID and the Service is what logical function is provided to the application.

However throughout the spec, we use service to mean service offering. For example, `ID of the service from the catalog. If present, MUST be a non-empty string.`

I guess this is a result of the catalog having a `services` array. We have a [Service Object](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-object) described as a `Schema of service objects` but the metadata object is described as `An opaque object of metadata for a Service Offering.`

These two terms are pretty confusing to new readers. Could we clarify things? Happy to attempt a PR.

**Comment by mattmcneeney** [comment]
+1 to a PR
