### ISSUE TITLE
Is the 2.14 spec contradictory around orphan mitigation?

### ISSUE THREAD

**Issue by williammartin** [openservicebrokerapi/servicebroker#563]
Hey all,

I'm trying to understand the orphan mitigation sections of the specification and right now it seems to be contradictory. There may be more cases, but the sections that jumped out to me were 4** status code section in the [orphans](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphans) section and the instructions on what to do under certain response codes from the [provision operation](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-3)

The relevant snippets of text are:

| Status Code Of Service Broker Response | Platform Interpretation Of Response | Platform Initiates Orphan Mitigation? |
| --- | --- | --- |
| ... | ... | ... |
| All other 4xx | Request rejected | No |
| ... | ... | ... |

vs.

> Responses with any other status code MUST be interpreted as a failure and a deprovision request MUST be sent to the Service Broker to prevent an orphan being created on the Service Broker

where status codes defined in the 4** range are 400, 409, and 422.

Am I missing something here like the table is generic and can be overridden by specific endpoint instructions, or is this contradictory?

Thanks,

Will

**Comment by Samze** [comment]
I think this is a mistake in the provision operation section. In CC we follow the guidance set out in the orphan mitigation table and do not orphan mitigate for 4xx codes.
