### ISSUE TITLE
Add plan_updateable to plans

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#582]
Right now `plan_updateable` is a flag on the Service in the Catalog, and it tells the Platform whether or not people can switch plans for that Service. However, that doesn't really help w.r.t. knowing if people can switch from any particular plan.

Proposal: add an "updateable" (yes with misspelling) to the Plan struct so that Platforms can know if users will be allowed to update services of *this* plan to another. Granted it won't tell them which ones they can migrate to, but its at least better than nothing like they have today. This also would not remove the need for the Broker to reject an upgrade if the Platform ignore this new field.

What do people think?

**Comment by duglin** [comment]
correct

**Comment by mattmcneeney** [comment]
How many use cases do we know of where only some plan migrations are allowed (i.e. `small` to `large` is allowed, but `large` to `small` isn't)? I'll do some digging on my side to see if this is a problem for any of the brokers I know of

**Comment by duglin** [comment]
I'm not sure how often it does happen but it happens enough for us that our product guys are asking for it :-)

**Comment by jmrodri** [comment]
This is related to https://github.com/openservicebrokerapi/servicebroker/issues/217

**Comment by MHBauer** [comment]
Why with misspelling?

**Comment by mattmcneeney** [comment]
Closing this issue as it was solved in #595
