### ISSUE TITLE
Section about HTTP headers is missing for a few GET requests

### ISSUE THREAD

**Issue by fmui** [openservicebrokerapi/servicebroker#585]
The spec does not define the HTTP headers for "Polling Last Operation for Service Bindings" and "Fetching a Service Instance".  They should match the headers definition of in the "Catalog Management" section.

**Comment by duglin** [comment]
It appears that all of the operation "Headers" sections are basically the same, or should be - some are missing the Originating Identity header. What do people think about creating a global HTTP Headers section where we talk about the headers in general, for all ops. And remove the op-specific header sections. Then we can include other headers (optional HTTP-defined headers) that people might consider using.  If, in the future, some operation has its own HTTP headers (e.g. perhaps etag for `get /catalog`) then we can have an op-specific Headers section.

Also see: #584

**Comment by fmui** [comment]
+1 for having a global headers section.

**Comment by mattmcneeney** [comment]
@duglin is going to put a PR together for this!

**Comment by mattmcneeney** [comment]
This is done and can be closed!
