### ISSUE TITLE
Compatibility Matrix vs Platform Features Page?

### ISSUE THREAD

**Issue by williammartin** [openservicebrokerapi/servicebroker#588]
Is one of these pages redundant?

https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/compatibility.md
https://github.com/openservicebrokerapi/servicebroker/wiki/Platform-Features

**Comment by mattmcneeney** [comment]
We have fixed this!

**Comment by duglin** [comment]
made the wiki point to the compat page
