### ISSUE TITLE
Response code for asynchronous delete operations

### ISSUE THREAD

**Issue by subhankarc** [openservicebrokerapi/servicebroker#601]
In case of asynchronous delete operation, both `200` and `410` are valid response code with state attribute in the body set as either `in progress`, `succeeded` or `failed`.

Is there a differentiation between `200` and `410` for the case of delete? Can a broker always send `410` for delete case? Or does it have to differentiate between the case where it was already deleted and return `410` only in that case?

According to [this doc](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#response-1) there does not seem to be a differentiation and I felt sending 410 for all delete cases seems not a problem. Is this a right conclusion?

Would like to hear opinion on the same.

**Comment by mattmcneeney** [comment]
@subhankarc It sounds like you're talking about the [Polling Last Operation for Service Instances](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-last-operation-for-service-instances) endpoint.

A `200 OK` status code can be returned with `"state": "in progress"`, `"state": "succeeded"` or `"state": "failed"`.

A `410 Gone` status code implies that `"state": "succeeded"`, and so cannot be returned with `"state": "in progress"` or `"state": "failed"`.

A `200 OK { "state": "succeeded" }` is equivalent to `410 Gone` for a delete operation, so you can return a `410 Gone` if you wish for all delete operations **once they have completed**.

Does that make sense?

**Comment by subhankarc** [comment]
@mattmcneeney yes I was talking about the last operation endpoint. 

So as I understand, if we return 410 for all delete cases that should be fine. Thanks for your prompt reply.

**Comment by mattmcneeney** [comment]
Yes - as long as the delete operation has completed successfully. If it is in progress or has failed, you'll need to return a 200 with the `state` field set appropriately.

Closing this issue but please feel free to reopen if anything else comes to mind!

**Comment by subhankarc** [comment]
Sure, thanks again!
