### ISSUE TITLE
Should we allow for a list of updateable plan targets?

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#602]
in #595 we talk about allowing for a particular plan to indicate if it can be upgradable. What do people think about allowing the plan to also state which plans its upgradable to? Just an array of strings/plan-names.

**Comment by duglin** [comment]
Sent https://groups.google.com/forum/#!topic/open-service-broker-api/IuFwo_L8vds to get feedback

**Comment by jhiemer** [comment]
Really good idea, current plan update mechanisms is completely not sufficient.

**Comment by mattmcneeney** [comment]
I'm going to close this as this doesn't seem to be a high priority problem, but if anyone disagrees please reopen this issue (or create a new one) so we can discuss this again.
