### ISSUE TITLE
Align our "valid chars in names/fields" with CF

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#603]
We're running into a situation where the spec says that service names "MUST only contain alphanumeric characters, periods, and hyphens (no spaces)", but we have existing service brokers that use underscores and CF allows this. While we could ask CF to change to match the spec I think its more important to support the existing brokers and change the spec to align with what CF does today.

We should:
1 - ask a CF person to provide the exact checks (if any) that it does for each of the fields - mainly the human readable fields, but technically we should check all of them if the spec tries to restrict it
2 - modify the spec to match

**Comment by duglin** [comment]
Assign to Will

**Comment by williammartin** [comment]
Hi @duglin, when you say:

> ask a CF person to provide the exact checks (if any) that it does for each of the fields - mainly the human readable fields, but technically we should check all of them if the spec tries to restrict it

I just want to get some clarification. You would like us to go through the specification, enumerate all the places the specification places restriction on naming, and cross reference these with any validation that CF does on these fields?

**Comment by duglin** [comment]
@williammartin correct - then we can make the spec match what CF does

**Comment by duglin** [comment]
@williammartin any update on this?

**Comment by duglin** [comment]
were you going to open a PR?

**Comment by williammartin** [comment]
Whoever gets to the story next will open a PR.

**Comment by duglin** [comment]
@williammartin looking at https://www.pivotaltracker.com/story/show/160591651 - I see where it talks about what the spec says, but I don't see where it talks about what CF does. Or is that one of the comments and I'm just missing it?

**Comment by williammartin** [comment]
Look for "CC, if present," italic comments

**Comment by duglin** [comment]
Ah, thanks!

**Comment by duglin** [comment]
@williammartin this can be closed now, right?

**Comment by williammartin** [comment]
@henryaj I think you PRed some changes right?

**Comment by henryaj** [comment]
Yes, https://github.com/openservicebrokerapi/servicebroker/pull/609 has been merged.

**Comment by duglin** [comment]
great thanks- closing
