### ISSUE TITLE
How to expose service operations through servicebroker?

### ISSUE THREAD

**Issue by chaitanya9186** [openservicebrokerapi/servicebroker#610]
I have a service which has operations like create/update/delete/read/etc. I understand provisioning/deprovisioning and binding/unbinding the service and service instances, but I am still confused how will the broker able to expose the underlying operations before provisioning?

Is there any one went in this path? 

Thanks.

**Comment by mattmcneeney** [comment]
Hey @chaitanya9186 Apologies for the delayed response to your question.

I'm not sure I understand what you're asking. Please could you elaborate for me? Thanks!
