### ISSUE TITLE
Fetching a service binding does not include service id.

### ISSUE THREAD

**Issue by eruvanos** [openservicebrokerapi/servicebroker#614]
## Problem
Request to fetch a service binding  does not include any information about the related service.
For service brokers providing multiple services they have to identify which service should be called.

While the spec enforces now the service id in `last operation for service instances`, it does not in `last operation for service bindings`.  
This can be worked around by manipulating the `operation` string, adding the service id in async responses.

To fetch a specific binding the service broker has either to ...

- ask all services for a binding or
- keep a mapping of binding ids to services, which would bring state for the broker itself

Better would be to get the service id in the request as a parameter.

## Background
I do maintain a python server implementation of the open service broker api. ([OpenBrokerAPI](https://github.com/eruvanos/openbrokerapi))
Since a while a go, users mentioned that they would like to host multiple services in one broker. Which is now a feature in the framework, but looks like it is not easily to keep with an upgrade to spec version 2.14.

**Comment by duglin** [comment]
@eruvanos do you need the plan-id too?  Also, note that service-id and plan-id are optional for last-op for instances. So, how do you deal with this when they're not present?

**Comment by eruvanos** [comment]
@duglin the broker framework requires each service implemented in his own class. 
So that in this case the plan id is not required because the service id is enough to delegate incoming calls to the right object.

For the last operation of service instances the framework does not use the optional parameters, but add service id on async responses in front of the operation string. On requests to last_operation the operation string is split into service id and original operation string, which was given from the server.

```
Provision, Update, Deprovision --[if async]--> operation=service-id + 'operation string from service'
Last Operation --> service-id, operation = 'incoming operation string'.split()
```

**Comment by mattmcneeney** [comment]
You can now [fetch a service instance](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) with `GET /v2/service_instances/:instance_id`, and the `service_id` and `plan_id` information is contained in the response. So as long as you know what service instance the binding is on, you can fetch this information as of [v2.14](https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v214).

Hopefully this will help this use case. Closing this issue, but please let me know if I've missed something and there is still a problem.

**Comment by eruvanos** [comment]
@mattmcneeney 
Hi, this does not really solve my issue, but I thing I will drop the multi service feature in the framework to support the new API. It looks like, that the API is developing into a direction, where a multi service implementation becomes harder and harder.

**Comment by mattmcneeney** [comment]
Reopening this issue following [this discussion](https://cloudfoundry.slack.com/archives/C5WH3RDLZ/p1562227034107100) on Slack.

The ask is for the `GET /v2/service_instances/:instance_id` and `GET /v2/service_instances/:instance_id/service_bindings/:binding_id` endpoints to contain two query parameters - `service_id` and `plan_id`. This is to support brokers which need to know this information to talk to some other system in order to respond to these requests.

@fmui @jberkhahn any thoughts on this?

**Comment by jberkhahn** [comment]
Would they be required? Seems like we should have added them in the first place, but it would be nice if those endpoints matched the others, but it might be too late now.

**Comment by mattmcneeney** [comment]
They would have to be optional now - but I think that's OK. PR inbound!

**Comment by fmui** [comment]
If they are optional, the broker has to be prepared that they are not provided. This means the broker has to implement retrieving the service and plan ID anyway. Does adding these parameters really provides value?

**Comment by mattmcneeney** [comment]
It would allow some stateless service brokers to support these endpoints
*if* the IDs were provided
