### ISSUE TITLE
Can service instance have multiple bindings?

### ISSUE THREAD

**Issue by Karthik-M-L** [openservicebrokerapi/servicebroker#619]
Hi,

Can service instance have two bindings credential and route service. 
We already have service broker which creates route service instance, but now we have created a service that has credential. We don't want two service broker for different service(route service and normal service). Is there any way we can achieve this?

Regards,
Karthik M L

**Comment by duglin** [comment]
Yes however it is up to the implementation of the broker to decide if the same credentials are returned for each binding or if a different set is returned each time. The description of the service should tell uses which model is supported. 

Thanks,
-Doug

**Comment by duglin** [comment]
Closing since I think this is resolved. Feel free to re-open if more discussion is needed.
