### ISSUE TITLE
service key creation on provision

### ISSUE THREAD

**Issue by Karthik-M-L** [openservicebrokerapi/servicebroker#622]
Hi,

I want to create service key  automatically on creation of service instance. Is there any configuration available such that it will call create binding automatically after service instance creation, if not please let me know how to achieve it.

Regards,
Karthik M L

**Comment by duglin** [comment]
@Karthik-M-L as of today there is no way to do it w/o a bit of a hack. For example, you could create a service that doesn't support bind() at all (metadata's "bindable" is false), and then just return whatever creds you need on the createInstance response flow - as an extension. Of course, this will only work for your specialized platform code - not CF or K8s.

What is the environment, or platform, you're using?  And, is it not possible to just immediately call bind() right after the provision?  What's the usecase you're trying to solve?

Another option, might be to have the broker create the binding as part of the createInstance() but then have the bind() API just return the (already created) binding info/creds.

**Comment by Karthik-M-L** [comment]
Hi,

We are using SAP cloud foundary, our service instance creation is in cf but the application consuming is not in cf. So instead of two steps creating service instance and creating service key, we want to reduce it to one step.

Regards,
Karthik M L

**Comment by duglin** [comment]
How do you plan on getting the credentials to the app?

**Comment by Karthik-M-L** [comment]
We are thinking of maintaining the credentials in the destination or secure store.

**Comment by Karthik-M-L** [comment]
_"And, is it not possible to just immediately call bind() right after the provision?"_

If I call bind after provision, how will platform get to know that I have created a service key. Is there any way we can send notification to platform??

**Comment by mattmcneeney** [comment]
Hey @Karthik-M-L 
I think your best path for doing this is to create a script which calls `cf create-service`, waits for the provision to complete, and then calls `cf create-service-key`. There is no automated way to do this today in CF.

**Comment by mattmcneeney** [comment]
Closing this, but let me know if you still believe there is a problem we could help solve.
