### ISSUE TITLE
be very explicit about types

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#629]
Spec says the header must be `application/json` but I don't think explicitly anywhere says that the body is json. Might want to link to `https://www.json.org/` ?

I'm raising this based on some question of what a `string` is, and unfortunately json.org isn't helpful here. I know I mainly live in a UTF8 world, but I am not sure what javascript/json believe strings are.

**Comment by mattmcneeney** [comment]
@fmui thinks `application/json` implies UTF8. Is this a good enough answer?
If not, do you want to open a PR @MHBauer ?
