### ISSUE TITLE
OSB implementation sample for C#

### ISSUE THREAD

**Issue by VenkateshSrini** [openservicebrokerapi/servicebroker#644]
Hi All,
Do we have an sample implementation of OSB in C#. My need will be to pull container from a repo. and also the backing services container from docker hub and create a host of services. Do we have a sample of that ?

**Comment by fmui** [comment]
Not sure if the [Getting Started documen](https://github.com/openservicebrokerapi/servicebroker/blob/master/gettingStarted.md#service-broker-libraries)t helps. There is a link to a .NET library.

**Comment by mattmcneeney** [comment]
@VenkateshSrini Did you take a look at https://github.com/AXOOM/OpenServiceBroker ? Does that help?

**Comment by VenkateshSrini** [comment]
Hi,
Thanks for checking. I went through the code and understood. I will be soon creating a few for putting services in market place. Thanks again for all your help. I truly appreciate it
