### ISSUE TITLE
Add billing type to cost structure

### ISSUE THREAD

**Issue by pschrey2** [openservicebrokerapi/servicebroker#645]
Hi,
As more and more cloud providers (Azure, IBM) are simplifying their cost model, and as it eases the automation of updating these parameters in the service broker, I would like to add an extra parameter to the suggested [costs object](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cost-object): billingType (string).
Instead of defining unit: "GB HOURLY", "GB MONTHLY", "TB HOURLY" or "TB MONTHLY"
use unit: "GB" or "TB" and billingType: "HOURLY" or "MONTHLY"
To be downwards compatible we can keep this extra parameter optional for now.

**Comment by williammartin** [comment]
If I understand you correctly you are suggesting changing:

```
"costs": [
  {
    "amount": {
      "usd": 1
    },
    "unit": "GB MONTHLY"
  }
]
```

to

```
"costs": [
  {
    "amount": {
      "usd": 1
    },
    "unit": "GB",
    "billingType": "MONTHLY"
  }
]
```

Can you talk a little more about what advantages this provides? How do you think platforms can semantically understand what they'd need to display? Perhaps whether or not the billing type has actually been provided?

Is there something else you're trying to convey with the billing type like periodicity?

Thanks!

**Comment by williammartin** [comment]
Any thoughts about the questions above?

**Comment by mattmcneeney** [comment]
Closing, but please re-open if this remains a problem.

**Comment by aegershman** [comment]
Apologies for hijacking, just throwing in my unsolicited thoughts-- I'm under the impression the spec doesn't make guarantees on the enumeration of `unit` options (MB, "MegaByte", "Megabit", GB, MBi, etc.) let alone the time interval (MINUTES, DAILY, MONTH, MONTHLY, etc).

Even if the `unit` and `billingType` (maybe better named `billingInterval`?) were broken out into their own keys, it doesn't seem there are standards on how they'd be parsed in downstream systems.

By the way, I'm entirely talking out of my butt and don't know anything about this, hence unsolicited thoughts 😉
