### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by georgi-lozev** [openservicebrokerapi/servicebroker#651]
Does it make sense to introduce a way to standardize the information provided from contributors when opening an issue/PR?
https://help.github.com/en/articles/about-issue-and-pull-request-templates

Sometimes it's hard to understand the problem that a particular PR or issue tries to solve.
Linking some kind of design documents or prior discussions is not always the case as well.

**Comment by mattmcneeney** [comment]
I can have a go at finding a suitable issue template (maybe from the CF CC) to see if that helps the quality of inbound issues and eliminates some back and forth.

**Comment by mattmcneeney** [comment]
@georgi-lozev What do you think of the template I just added? https://github.com/openservicebrokerapi/servicebroker/tree/master/.github/issue_template.md
