### ISSUE TITLE
Add K8S and CF annotations to context object and CF bind resource

### ISSUE THREAD

**Issue by gberche-orange** [openservicebrokerapi/servicebroker#654]
**What is the problem?**

As an application developer, I need some implicit context from my platform to be provided to services I provision which includes:
* where to direct service-related alerts when the service is out of its SLA (e.g. a slack channel, or email address, or paging number)
* an application/organization unit attached to the application for associating the service with chargeback/inventories/cmdb 

As an application developer, I would like the annotations provided to my services to default to the ones I have set in my platform, so I don't have to explicitly define them on every service I request provisionning of (e.g. as explicit parameters)

Example of platform hosted annotations may set:
* [cloudfoundry annotations](http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#metadata) which can be set or [orgs](http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#organizations), [spaces](http://v3-apidocs.cloudfoundry.org/version/3.68.0/index.html#spaces), apps, and soon service-instances (currently [being implemented](https://www.pivotaltracker.com/n/projects/966314/stories/164144574))
* [K8S annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) which can be set for instance on my namespace, or a [ServiceInstance](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/)

**Who does this affect?**

* Application developers: (implicitly) set annotations
* Service authors: their broker read and use annotations
* potentially platform operators: may operate intermediate layers such as "Peripli Service Manager" that would read/use such annotations, potentially without service authors being aware of the existence of such annotations.

**Do you have any proposed solutions?**

The [CF and K8S Context](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) get enriched with a set of annotations:
*  for CF, the following fields containing a subset of the corresponding entity annotations, formatted as a json hash with key/value string pairs
   *  `organization_annotations` 
   *  `space_annotations` 
   *  `instance_annotations`
*  for K8S, the following fields containing a subset of the corresponding entity annotations (i.e. [public ones](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) starting with a non empty prefix), formatted as a json hash with key/value string pairs
   *  `namespace_annotations` 
   *  `serviceinstance_annotations`

The context gets populated during service provisionning. When annotations gets updated in platforms, the service instance may , and during update of the annotations which trigger a call to the update endpoint, similar to behavior introduced in #544 

The [CF bind resource object](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-bind-resource-object), gets extended with the following the following field containing a subset of the corresponding entity annotations (i.e. [public ones](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) starting with a non empty prefix), formatted as a json hash with key/value string pairs:
* `app_annotations`
* (potentially in the future `servicebinding_annotations` )

Since currently service bindings don't support updates (see #123), changes to CF app annotations require a new service binding to be communicated to service brokers.

**Additional context**

Platforms may choose to provide fine-grain opt-in or opt-out to their users for publishing annotations to service brokers. Some platform may have registered some 3rd party non trusted service brokers in their marketplace, and it might not be desireable to have all of the corporate specific annotations be disclosed to those non trusted brokers.

/CC @laurzca @mattmcneeney @georgi-lozev

**Comment by jberkhahn** [comment]
Once a binding is created in k8s Service Catalog, the namespace and the instance that binding belongs to can't change, so we wouldn't need to update the annotations for those.

**Comment by gberche-orange** [comment]
@mattmcneeney jberkhahn thanks for your reviews!

> Do you envision this information being sent in the context object, and these new fields being documented in profile.md?

yes

> Recreating a binding will likely mean credentials will change, and the app will have to be restarted which may have downtime. I'm not sure this will be acceptable to developers for just metadata changes.

> Once a binding is created in k8s Service Catalog, the namespace and the instance that binding belongs to can't change, so we wouldn't need to update the annotations for those.

Maybe we can defer annotations in service bindings 's context (i.e., `app_annotations`) to later and rather wait for feedback from service authors and applications developers from their usage of annotation in service instance 's context.

**Comment by waterlink** [comment]
@gberche-orange 

That sounds like a solid idea. I do have a question about this:



> The [CF and K8S Context](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) get enriched with a set of annotations:
> 
> * for CF, the following fields containing a subset of the corresponding entity annotations, formatted as a json hash with key/value string pairs
>   
>   * `organization_annotations`
>   * `space_annotations`
>   * `instance_annotations`
> * for K8S, the following fields containing a subset of the corresponding entity annotations (i.e. [public ones](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) starting with a non empty prefix), formatted as a json hash with key/value string pairs
>   
>   * `namespace_annotations`
>   * `serviceinstance_annotations`

Why use different keys for annotations, when simple `annotations` that is a list of objects with an annotation type `{ "annotation_type": "space_annotation", … }`. Am I missing something? What do you think?

**Comment by fmui** [comment]
@waterlink: I like the idea. The [Service Manager](https://github.com/Peripli) has also annotations. (They are called labels, but it's the same idea.) Having something like an `annotation_type` would make it easy for us to also expose the Service Manager annotations.

**Comment by mattmcneeney** [comment]
Hey @gberche-orange Are you happy to put a PR together to add this feature to the spec?

My only concern is that people may add sensitive information to resource metadata, and they may not want that shared with service providers. For example, I may add an annotation to my CF organziation that looks like:
```
team: some-team
email: admin@my-company.com
```

How do you think we can find out whether or not sharing all resource metadata with service providers could be a security issue for some users? Do we need to make this an opt-in feature?

**Comment by gberche-orange** [comment]
@waterlink 

> Why use different keys for annotations, when simple annotations that is a list of objects with an annotation type { "annotation_type": "space_annotation", … }. Am I missing something? What do you think?

I'm not sure this factorization into a single `annotations` key is really bringing simplicity:
- this requires defining a `annotations` new structure in the specs
- it would make the parsing harder for service authors
- it would become inconsistent with the existing `id` and `name` keys. Why would annotations be treated differently than `name` ? Would we then have a structure for name such as ```{ "name_type": "space", "value":"my_space_name" }```

@fmui 
> I like the idea. The Service Manager has also annotations. (They are called labels, but it's the same idea.) Having something like an annotation_type would make it easy for us to also expose the Service Manager annotations.

Since the context object support additional properties, as defined in [profile.md extract below](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object-properties), could it make sense for service manager to define its own `service_manager_labels` key

> Platforms MAY choose to provide additional properties beyond the ones defined in this document. 
Would you expect the [ServiceManager-specific labels](https://github.com/Peripli/specification/blob/visibility-labels/api.md#labels) to be added within the CF and K8S context

> I like the idea. The Service Manager has also annotations. (They are called labels, but it's the same idea.) Having something like an annotation_type would make it easy for us to also expose the Service Manager annotations.

@mattmcneeney 

> Are you happy to put a PR together to add this feature to the spec?

Yes, I'll submit a PR in the next days when I get back in office.

> How do you think we can find out whether or not sharing all resource metadata with service providers could be a security issue for some users? Do we need to make this an opt-in feature?

As a 1st step, we can leverage [K8S annotations naming conventions](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) reproduced below to allow users to distinguish between public annotations (shared with all brokers) and private annotations (not shared with brokers): 

> Annotations are key/value pairs. Valid annotation keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

> If the prefix is omitted, the annotation Key is presumed to be private to the user. Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add annotations to end-user objects must specify a prefix.

As a 2nd step, if users need to be able to selectively control that some brokers don't get published public annotations, then we can consider associating a new `ConfidentialityPolicy` field to the broker when it gets registered in the platform, e.g. [create-service-broker](http://cli.cloudfoundry.org/en-US/cf/create-service-broker.html) SERVICE_BROKER USERNAME PASSWORD URL `[--space-scoped]` `--confidentiality-policy=trusted|semi-trusted|untrusted` with

* `trusted` (default): public annotations, names and opaque ids gets published (user, space, org, service instance)
* `semi-trusted`: only names and opaque ids gets published 
* `untrusted`: only opaque ids gets published

**Comment by waterlink** [comment]
@gberche-orange 

> * this requires defining a `annotations` new structure in the specs

Yes, that would require a new structure.

> * it would make the parsing harder for service authors

If service authors are interested only in a few specific annotations (e.g.: `space` and `org`), then yes, the polymorphic list will be harder. If service authors are interested in processing all annotations whatever they are (common polymorphic code doing the processing), then the list will be more straightforward.

**Thinking more about it, it seems that service authors will need specific annotations instead of all of them at once. Is that assumption true?**

> it would become inconsistent with the existing id and name keys. Why would annotations be treated differently than name? Would we then have a structure for name such as { "name_type": "space", "value":"my_space_name" }

My feeling here is that `annotation` and `name/id` conceptually are so different (one is a single string value, and another is a full hash with any amount of keys and values), that consistency between them is not a concern.

So I think that decision here should depend on the previous point: what would be simpler for service authors.

**Comment by gberche-orange** [comment]
@waterlink 

> Thinking more about it, it seems that service authors will need specific annotations instead of all of them at once. Is that assumption true?

For the use-cases I have in my company, service authors expect users to set/override annotations at different levels: org, space, service-instance. The service broker logic therefore fetches the org-annotations and then overrides it with space-annotations, and finally overrides it with service-instance-annotations. Having distinct keys seems to match well this use-case.

**Comment by waterlink** [comment]
@gberche-orange 

> For the use-cases I have in my company, service authors expect users to set/override annotations at different levels: org, space, service-instance. The service broker logic, therefore, fetches the org-annotations and then overrides it with space-annotations, and finally overrides it with service-instance-annotations. Having distinct keys seems to match well this use-case.

👍

**Comment by gberche-orange** [comment]
@mattmcneeney @waterlink 

I've submitted #658 with the individual new keys. I believe this keeps it simple for service authors, and consistent with the existing properties, even though this comes with the expense of a bit of duplication in the specs text across the `*_annotations` keys.
