### ISSUE TITLE
Do we need to update swagger.yaml to latest version?

### ISSUE THREAD

**Issue by leonwanghui** [openservicebrokerapi/servicebroker#656]
**What is the problem?**
`swagger.yaml` only supports 2.13 version, and it's out of date compared to current specification.

**Who does this affect?**
Currently I'm working for [https://github.com/openservicebrokerapi/osb-checker/pull/77](https://github.com/openservicebrokerapi/osb-checker/pull/77), and I want to leverage `go-swagger` tool to generate source code automatically from specification, but then I found the `swagger.yaml` only supports v2.13.

**Do you have any proposed solutions?**
If there is no concern to modify `swagger.yaml` file, I'm willing to help update it to latest version.

**Additional context**
Add reviewers: @mattmcneeney @fmui @jberkhahn @tinygrasshopper

**Comment by mattmcneeney** [comment]
Hey @leonwanghui 
We've been trying to keep the swagger spec in line with the spec on the master branch, but it seems like some stuff got dropped!
Thanks for putting this together. I think having the master branch swagger always being aligned with the spec.md is important.

**Comment by mattmcneeney** [comment]
We should create a Pull Request template reminding contributors to update both the openapi and swagger docs when submitting a change.

**Comment by mattmcneeney** [comment]
I have added a very simple PR template to help us remember to update these files!
