### ISSUE TITLE
Should we add Swagger/OpenAPI testing into our CI?

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/servicebroker#664]
**What is the problem?**
As demonstrated by #662, it is possible for PRs to inadvertently break our swagger/openAPI docs today as we do not check these in Travis CI. This isn't good for folks relying on these tools.

**Who does this affect?**
Maintainers of this repo.

**Do you have any proposed solutions?**
We could add a step to our CI pipeline to check these files for errors.

**Comment by leonwanghui** [comment]
@mattmcneeney This issue should be closed since it's resolved by #666

**Comment by mattmcneeney** [comment]
Good spot - thanks @leonwanghui  !
