### ISSUE TITLE
Undefined HTTP Response code when the X-Broker-API-Version HTTP header is missing

### ISSUE THREAD

**Issue by aukhatov** [openservicebrokerapi/servicebroker#673]
**What is the problem?**
Undefined HTTP Response code when the `X-Broker-API-Version` HTTP header is missing.

**Who does this affect?**
If the response code will change to another code then it could break backward compatibility.

**Do you have any proposed solutions?**
More clearly define the response code when the `X-Broker-API-Version` header is missing, like `412 Precondition ` or `400 Bad Request `.

**Comment by waterlink** [comment]
@aukhatov 

Thank you for opening this issue!

It shouldn’t be a `412 Precondition` because it implies that client provided a pre-condition header, which it didn’t in this scenario.

So `400 Bad Request` sounds like a more legit response status code in this case.

What do you think?

**Comment by baleev** [comment]
I think, according to the spec the 400 status is more relevant, however it would be more clear to give note about what  - "mandatory data" is meant there. Including headers and request body

**Comment by aukhatov** [comment]
Hi @waterlink, it would be okay.

**Comment by mattmcneeney** [comment]
@waterlink has kindly agreed to open a PR for this one
