### ISSUE TITLE
Java code generated from swagger.yaml using swagger-codegen-cli causes NPE

### ISSUE THREAD

**Issue by MosheElisha** [openservicebrokerapi/servicebroker#693]
Hi,

1. Generate Java code from the [swagger.yaml](https://github.com/openservicebrokerapi/servicebroker/blob/e953ad2b478264900f6376ec886bb5921073aac2/swagger.yaml) using swagger-codegen-cli with this command:

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i "/tmp/swagger.yaml" -l jaxrs-cxf -o /tmp/project`

2. Use the generated classes in a spring boot application and enable the Swagger2Feature:

`endpoint.setFeatures(Collections.singletonList(new Swagger2Feature()));`

You get a `java.lang.NullPointerException: null at io.swagger.models.refs.GenericRef.<init>(GenericRef.java:44)` attached [npe.log](https://github.com/openservicebrokerapi/servicebroker/files/3588975/npe.log)

The cause is probably the generated model class [Object.java.txt](https://github.com/openservicebrokerapi/servicebroker/files/3588979/Object.java.txt) which is generated without properties according to the definition in https://github.com/openservicebrokerapi/servicebroker/blob/e953ad2b478264900f6376ec886bb5921073aac2/swagger.yaml#L799

The workaround is to delete the generated Object.java file and let all the classes that uses it (for example, `ServiceBindingVolumeMountDevice.mountConfig`) to use `java.lang.Object` instead.

**Comment by mattmcneeney** [comment]
Thanks for raising this @MosheElisha - we will see if we can find someone to look into this next week.

**Comment by jberkhahn** [comment]
see #696

**Comment by pivotal-marcela-campo** [comment]
Closing as this was fixed with [PR](https://github.com/openservicebrokerapi/servicebroker/pull/696) already merged
