### ISSUE TITLE
Open Service Broker Example: following OAuth

### ISSUE THREAD

**Issue by joshianurag21** [openservicebrokerapi/servicebroker#716]
**What is the problem?**
Need a sample (example) of service broker which follows Oauth for Auth. Most of the sample brokers are following basic auth only. 

**Who does this affect?**
N/A

**Do you have any proposed solutions?**
N/A

**Additional context**
Just exploring service brokers, from blog (https://www.openservicebrokerapi.org/category/blog)
came to know that non-basic auth is also supported for service broker. But didn't get any sample broker following this, most of them follow basic auth.

**Comment by Samze** [comment]
Hi @joshianurag21 thanks for the question.

The [Google Service Broker](https://github.com/GoogleCloudPlatform/gcp-service-broker) takes advantage of the `bearer token` support we have in the specification and uses a flavour of oauth to authentication with Google's Services. 

There is also a [proposal](https://github.com/openservicebrokerapi/servicebroker/issues/530) to bring a more formal method of doing OAuth between Platforms and Brokers.

**Comment by joshianurag21** [comment]
Hi @Samze thanks for the response. Proposal looks good, any idea when this would be available as specification.

**Comment by Samze** [comment]
@joshianurag21 there is no timeline for it right now. Since the specification does support OAuth flow out-of-band today, does this support what you are trying to achieve?
