### ISSUE TITLE
Handling missing or unknown state during polling is undefined

### ISSUE THREAD

**Issue by ransombriggs** [openservicebrokerapi/servicebroker#719]
**What is the problem?**

There is no guidance on how to handle either a missing or unknown `state` during polling is undefined.  What should the platform do if the broker passes back `{}` or `{"state": "garbage"}` during polling?  For now we are retrying until the polling interval is reached, but am not certain if that is the right behavior.

**Who does this affect?**

This affect platform authors

**Do you have any proposed solutions?**

Off the top of my head there are two options:
1. Continue polling until a defined `state` or polling interval reached
1. Perform orphan mitigation

**Comment by Samze** [comment]
As discussed on 18/08/2020 call, we are closing this.
