### ISSUE TITLE
Service Instance response doesn't include context on fetch

### ISSUE THREAD

**Issue by rsampaio** [openservicebrokerapi/servicebroker#720]
**What is the problem?**

The response of fetching information from Service Instance doesn't include the context field, context can be generated by the Service Broker and can contain useful information for the platform.

An example we have in our platform is a customer using a private plan:
* Customer provision a private plan
* Broker creates a VPC for the service instance and communicate the `service_name` back so customers can create a private endpoint
* Since this is context information generated by the broker and not provided by the User it doesn't make sense to return this value in `parameters`.

**Who does this affect?**
Service Broker Authors, Platforms and Developers

**Do you have any proposed solutions?**
A potential solution would be to include the field `context` on the response of fetching a Service Instance, I create a Pull Request with this change which I will link to this issue shortly.

**Additional context**
In addition to the `context` field, I wonder if the response should also include the `metadata` provided in the creation of the service instance as well as information about maintenance

**Comment by gberche-orange** [comment]
@rsampaio should this issue be closed now that https://github.com/openservicebrokerapi/servicebroker/pull/721 got merged ? It seems the PR was missing the `close` keyword for closing it issue automatically
