### ISSUE TITLE
website no longer has "How service brokers work" image

### ISSUE THREAD

**Issue by pburkholder** [openservicebrokerapi/servicebroker#725]
**What is the problem?**

https://www.openservicebrokerapi.org/ is missing an image: https://www.openservicebrokerapi.org/wp-content/uploads/sites/21/2018/09/howitworks.svg

**Who does this affect?**

Anyone wanting to learn more about OSBAPI

**Do you have any proposed solutions?**

Update the webpage? Reload the image?

**Additional context**
Sorry if this is the wrong repo, not sure where else to file this. 

Here's how it's archived on the wayback machine:

![image](https://user-images.githubusercontent.com/1211146/90141056-9d05ac80-dd48-11ea-9885-24f24fc0e78d.png)

Here's how it looks now:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1211146/90141161-beff2f00-dd48-11ea-8903-452e2647ce92.png">

**Comment by Samze** [comment]
Thanks @pburkholder, I will look into this

**Comment by Samze** [comment]
This is now fixed, thanks @pburkholder
