### ISSUE TITLE
support unattended service instance updates

### ISSUE THREAD

**Issue by alexwo** [openservicebrokerapi/servicebroker#726]
**What is the problem?**
Allow platforms to trigger unattended service instance updates

**Who does this affect?**

-  broker authors: allow indicating if a broker support unattended-upgrades or not

- platform authors: allows a platform to trigger an automatic update if the service broker supports it

- developers/operators: can manually trigger an update

### Get catalog
-  new  version_info_available **boolean** to indicate if unattend_upgades are supported for a service plan offering

### Provision Service Instance
- The return value on provision should indicate the current technical instance version
for example ```{version:"9.6.2"}```
Assumption: all versions are semver compatible
	
### Service Instance Update
a new **update_version** parameter can be passed to indicate the desired upgrade to apply.

###  New /v2/:service_plan_catalog_id/available_versions
GET /v2/:service_plan_catalog_id/available_versions

Response: JSON document with service plan upgrade options 

```javascript
{
   "updates":[
      {
         "version":"9.6.1",
         "description":"Remove public execute privilege from contrib"
      },
      {
         "version":"9.6.4",
         "description":"Fix incorrect volatility markings"
      }
   ]
}
```

> Returns the list of all available upgrade versions
> Only available in case unattended upgrades are allowed for a service plan (**version_info_available** boolean)

## Flows:
1. User triggered upgrades 
  The user triggers an upgrade by calling the update API

1. Unattended upgrades by the platform
To allow unattended-upgrades, a platform can provide the capability to define maintenance windows ( out of spec scope ). the platform can query the API (/v2/:service_plan_catalog_id/available_versions) within the maintenance window timeframe to determine if there are upgrades available, in case there are, the platform can upgrade the service instance by executing the update service instance API and specifying the required uprgade_version.

**Comment by liorokman** [comment]
1. Maybe change the flag name in the Catalog to `version_info_available` in order to be more clear as to what this flag requires from the Broker developer. 
1. Maybe change the new endpoint to `/v2/:service_plan_catalog_id/available_versions` to make it clear what this endpoint is about.
