### ISSUE TITLE
Not Able to return 410 status code via get instance last operation call in async service broker

### ISSUE THREAD

**Issue by chourasiya** [openservicebrokerapi/servicebroker#733]
**What is the problem?**
Not Able to return 410 status code via get instance last operation call in async service broker.

**Who does this affect?**
It affects user experience as instance already deleted but not getting proper status code. 
 
**Do you have any proposed solutions?**
Right now for solving this issue i try to throw ServiceInstanceDoesNotExistException class which return 410 in case of delete call but on get last operation call i am getting 422. 

**Additional context**
Can someone provide me sample code how i can return 410 status code in get instance last response call.

**Comment by Samze** [comment]
@chourasiya I think this is a framework specific problem you're having. This repository is for the specification itself. It looks like `ServiceInstanceDoesNotExistException` is part of https://github.com/spring-cloud/spring-cloud-open-service-broker.
