### ISSUE TITLE
In case of X-broker-api-version code and spec not working synchronously

### ISSUE THREAD

**Issue by chourasiya** [openservicebrokerapi/servicebroker#736]
**What is the problem?**
In service broker specification X-Broker-API-Version must be present in the request but when i import service broker code and run, it's api working without this header as well. Can anyone tell me what i have to do to match with specification. 
Dependency : 
spring-cloud-starter-open-service-broker 3.1.1.RELEASE
Open Service Broker API v2.15 

**Who does this affect?**
We try to find out weather it's correct behavior or spec meaning is something different. 
  

**Do you have any proposed solutions?**

**Additional context**
![image](https://user-images.githubusercontent.com/17027923/106581386-cde0d480-6568-11eb-9e31-349897fff962.png)

**Comment by Samze** [comment]
Hey @chourasiya I think this is an issue with the `spring-cloud-starter-open-service-broker 3.1.1.RELEASE` library and not the specification. You can find that repository [here](https://github.com/spring-cloud/spring-cloud-open-service-broker)
