### ISSUE TITLE
Adding a new column in the existing table to indicate the default values for any specific field

### ISSUE THREAD

**Issue by sengupta-saikat** [openservicebrokerapi/servicebroker#758]
**What is the problem?**
It is a little difficult to quickly grasp the default values for any specific fields of a Service Offering/Plan. It's mentioned in the long description hence takes some time to spot.

**Who does this affect?**
It's a cosmetic change hence no impact to anyone.

**Do you have any proposed solutions?**
Simply adding a new column showing the default values would be great. I can raise a PR if allowed.

**Additional context**
None

**Comment by pivotal-marcela-campo** [comment]
Closing stale issue. Please re-raise if this is still an issue.
