### ISSUE TITLE
Change open service broker configuration to clone cloud source repo using HTTPS instead of SSH

### ISSUE THREAD

**Issue by NitishGupta9282** [openservicebrokerapi/servicebroker#760]
Hi in our environment we are using osb which is used to clone cloud source repo using ssh. We want it to change repo using https instead of ssh. can you plsh guide me, how to do the required changes?

**Comment by pivotal-marcela-campo** [comment]
Closing stale issue which doesn't seem related to the OSBAPI. Please raise a new one if this is still an issue/
