### ISSUE TITLE
Convert spec to be more RFC2119 and less CF-specific

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/servicebroker#93]
Right now the spec is written like its a subset of the CF docs, which is it  :-)  but we need to make it more stand-alone and so a re-org is probably needed. While doing that we should make it more normative by adding the appropriate RFC2119 keywords to make it clear what's required/optional for people wanting to implement the spec.

**Comment by MHBauer** [comment]
I `SHALL` take a stab at a rough outline. First time writing a spec. :-)

**Comment by MHBauer** [comment]
see #95 for a start. I have several PRs ready to go after that merges to clean up the language and sections.

**Comment by pmorie** [comment]
On a semi-related note I would love for the spec to be markdown. I object on principle to writing raw html in the year 2016.

**Comment by MHBauer** [comment]
@pmorie you and me both. I didn't want to mess with the conversion before I had to. I had to massage some of the tables from html into markdown, and I'll hit the rest of them in the future. I left the `pandoc` invocation I used in the PR.

**Comment by shalako** [comment]
@duglin I think this one can be closed? Or do you want to keep it open to review the doc coming from CF?

**Comment by duglin** [comment]
I'd prefer to leave it open because if the current work is more of a "move" then I suspect it'll still need some work to use the RFC2119 stuff.

**Comment by duglin** [comment]
Closing this as we have other issues/PRs in flight that should cover this.
