### ISSUE TITLE
cost structure in existing spec is ill-defined

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#94]
This is all currently optional, so I'm not sure how important it is to nail it down as part of a spec. Discussion did seem rather concerned with uses that allowed charging.  I was trying to write down a swagger definition and having trouble with this part of the definition of a plan object.

cost is defined on a plan.

api.md defines it as 'cost'
catalog-metadata.md defines it as 'costs'

the structure of the 'cost' object is defined in terms of usd, which is obviously somewhat centered on a specific currency. As well as using that currency as a key in an object, which is not good.

It is unclear about how multiple costs combine together if they exist.

**Comment by angarg12** [comment]
This is a relevant point for us because being able to display a service cost is a requirement of one of our customers.

I agree that we should do a pass on the spec and refine the current definition. It is in our TODO list but right now it is low priority so we haven't started working on it.

**Comment by shalako** [comment]
I believe the issue @MHBauer is referring to is only that the example in the api spec doesn't match the suggested field in http://docs.cloudfoundry.org/services/catalog-metadata.html.

I believe it's reasonable to update the example in the api spec to match, if removes some confusion. It doesn't change the spec, as this field is not in the spec.

I'll include the change with my PR to migrate the spec from CF.

**Comment by mattmcneeney** [comment]
@shalako I believe this bug is resolved. Would you or @MHBauer like to confirm and close this issue? Thanks

**Comment by shalako** [comment]
The example in the spec has been updated, and we discuss in [profile.md](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) that `cost` is part of `metadata` and not defined in the spec.

> api.md defines it as 'cost'
> catalog-metadata.md defines it as 'costs'

The AppDirect broker uses `costs`, and this is used in the PWS web UI.
 
> the structure of the 'cost' object is defined in terms of usd, which is obviously somewhat centered on a specific currency. As well as using that currency as a key in an object, which is not good.
> It is unclear about how multiple costs combine together if they exist.

Though there are likely better schemas; the current one used by Pivotal does allow for multiple currencies:

```
"costs": [
  {
    "amount": {
      "usd": 649.0,
      "yen": 1000,
      "euro": 700
    },
    "unit": "MONTHLY"
  }
]
```

I would say we close this and if someone would like to see costs defined in the specification, they should open a new issue.

**Comment by MHBauer** [comment]
Current spec and such seems fine now.
