### ISSUE TITLE
Identify pattern for *experimental* flags/extentions

### ISSUE THREAD

**Issue by MHBauer** [openservicebrokerapi/servicebroker#98]
From https://github.com/openservicebrokerapi/servicebroker/pull/95#issuecomment-258163461

> 
> In v2.10 volume services are no longer experimental.
> 
> Note that there was a breaking change for volume services from v2.9 to 2.10
> when the "experimental" flag was removed.
> 
> As part of this WG I would love to discuss the use of "experimental" API
> specs. Not sure that it worked well in this case.

**Comment by shalako** [comment]
Changing the title to clarify the goal of this issue

**Comment by mattmcneeney** [comment]
@MHBauer @shalako I don't believe there is anything to do regarding this anymore. Should we close this issue?

**Comment by shalako** [comment]
I believe this is being addressed with our docs for alpha features #228. Closing.
